### ISSUE TITLE
Cannot extract character data from Sybase

### ISSUE THREAD

**Issue by cmhh** [r-dbi/odbc#111]
I'm trying to query Sybase, and I get the following error for any query that returns `char` or `varchar` fields (possibly others, but this is what's failing so far):

```as.is
Error in new_result(connection@ptr, statement) : std::bad_alloc
```

My driver reports as `SQL Server Version: 15.7.0`, though the full specification in `/etc/odbcinst.ini` is:

```as.is
[Sybase]
Description=Sybase ODBC Driver
Driver=/opt/sybase/DataAccess64/ODBC/lib/libsybdrvodb.so
FileUsage=-1
UsageCount=1
```

I can use this driver successfully with `RODBC`, and with `DBI` + `odbc` as long as all the columns in the result set are some numeric variant.

I've tried `odbc` versions 1.1.1 and 1.1.1.9000.

Not a reproducible example, but this is a typical session:

```r
hsf <- DBI::dbConnect(odbc::odbc(),
                      Driver="Sybase",
                      Server="wprdsyb03",
                      Database="hs_frame_prod",
                      Port=5000,
                      UID=Sys.info()["user"],
                      PWD=rstudioapi::askForPassword("Sybase password:"))

res <- DBI::dbGetQuery(hsf, "select top 10 * from household")
```

I don't know if it's useful, but `odbc::odbcListColumns(hsf)` returns:

```as.is
Error in UseMethod("odbcListColumns") : 
  no applicable method for 'odbcListColumns' applied to an object of class "c('SQL Server', 'OdbcConnection', 'DBIConnection', 'DBIObject')"
```

(`odbcListObjects` works, but takes quite a long time).

This is not particularly critical as we're moving from Sybase to MS SQL Server, but thought I'd post on the off-chance that there was something obvious going on here...

**Comment by jimhester** [comment]
Can you show the results of `dbGetInfo(hsf)` and 

```r
library(DBI)
# connect as shown
res <- dbSendQuery(hsf, "SELECT TOP 10 * FROM household")
dbColumnInfo(res)
```

I am guessing the Sysbase driver is reporting a column width that is too wide for the memory of your machine. We may have to include a maximum value to deal with drivers which do this.

**Comment by cmhh** [comment]
Unfortunately, `dbSendQuery()` produces the same errors as above (`Error in new_result(connection@ptr, statement) : std::bad_alloc`).  But here's `dbGetInfo()`:

```r
> dbGetInfo(hsf)
$dbname
[1] "hs_frame_prod"

$dbms.name
[1] "SQL Server"

$db.version
[1] "15.7.0"

$username
[1] "cxhansen"

$host
[1] ""

$port
[1] ""

$sourcename
[1] ""

$servername
[1] "wprdsyb03"

$drivername
[1] "Adaptive Server Enterprise (ANSI)"

$odbc.version
[1] "03.52"

$driver.version
[1] "15.7.0.1300"

$odbcdriver.version
[1] "03.51"

$supports.transactions
[1] TRUE

attr(,"class")
[1] "SQL Server"  "driver_info" "list"  
```

Thanks.
