### ISSUE TITLE
Teradata: connecting, disconnecting, and checking for validity often throws an error

### ISSUE THREAD

**Issue by ronblum** [r-dbi/odbc#125]
### Issue Description and Expected Result
Connections to Teradata occasionally include a pop-up that says:
-    "R code execution error."

Usually, this is paired up with an error in the output, typically:
-   Error in connection_sql_tables(connection@ptr, catalog, schema, name,  : 
-   nanodbc/nanodbc.cpp:4274: HY000: [RStudio][ODBC Teradata Driver] (6) Internal Error 

Note: the error occurs often, but not consistently. The code may have to be run several times.

### Database
Teradata 16.10.0004

### Reproducible Example
```{r}
#Verify basic connection.
library(DBI)

# Fill in DBCName and Username
con <- dbConnect(odbc::odbc(), Driver="teradata", DBCName = "", Username = "", Password = rstudioapi::askForPassword("Database password:"))
#Verify dbConnect worked and returns TRUE
dbIsValid(con)

#Verify dbDisconnect()
dbDisconnect(con)

#Verify dbDisconnect worked and returns FALSE
dbIsValid(con)

```

<details>
<summary>Session Info</summary>

Session info -----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.2 (2017-09-28)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.383)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Zulu                        
 date     2017-10-22                  

Packages ---------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 assertthat   0.2.0      2017-04-11 CRAN (R 3.4.2)                    
 backports    1.1.1      2017-09-25 CRAN (R 3.4.2)                    
 base       * 3.4.2      2017-09-29 local                             
 base64enc    0.1-3      2015-07-28 CRAN (R 3.4.2)                    
 bindr        0.1        2016-11-13 CRAN (R 3.4.2)                    
 bindrcpp     0.2        2017-06-17 CRAN (R 3.4.2)                    
 bit          1.1-12     2014-04-09 cran (@1.1-12)                    
 bit64        0.9-7      2017-05-08 cran (@0.9-7)                     
 blob         1.1.0      2017-06-17 cran (@1.1.0)                     
 boxr       * 0.3.4      2017-01-12 CRAN (R 3.4.2)                    
 broom        0.4.2      2017-02-13 CRAN (R 3.4.2)                    
 callr        1.0.0      2016-06-18 CRAN (R 3.4.2)                    
 clipr        0.3.3      2017-06-19 CRAN (R 3.4.2)                    
 compiler     3.4.2      2017-09-29 local                             
 config       0.2        2016-08-02 CRAN (R 3.4.2)                    
 curl         3.0        2017-10-06 CRAN (R 3.4.2)                    
 datasets   * 3.4.2      2017-09-29 local                             
 DBI        * 0.7        2017-06-18 cran (@0.7)                       
 dbplyr     * 1.1.0.9000 2017-10-19 Github (edgararuiz/dbplyr@ed02b4a)
 devtools     1.13.3     2017-08-02 CRAN (R 3.4.2)                    
 digest       0.6.12     2017-01-27 CRAN (R 3.4.2)                    
 dplyr      * 0.7.4      2017-09-28 CRAN (R 3.4.2)                    
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.2)                    
 foreign      0.8-66     2015-08-19 CRAN (R 3.2.2)                    
 git2r        0.19.0     2017-07-19 CRAN (R 3.4.2)                    
 glue         1.1.1      2017-06-21 CRAN (R 3.4.2)                    
 graphics   * 3.4.2      2017-09-29 local                             
 grDevices  * 3.4.2      2017-09-29 local                             
 grid         3.4.2      2017-09-29 local                             
 hms          0.3        2016-11-22 CRAN (R 3.4.2)                    
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.2)                    
 httpuv       1.3.5      2017-07-04 CRAN (R 3.4.2)                    
 httr         1.3.1      2017-08-20 CRAN (R 3.4.2)                    
 jsonlite     1.5        2017-06-01 CRAN (R 3.4.2)                    
 knitr        1.17       2017-08-10 CRAN (R 3.4.2)                    
 lattice      0.20-33    2015-07-14 CRAN (R 3.2.1)                    
 lazyeval     0.2.0      2016-06-12 CRAN (R 3.4.2)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.4.2)                    
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.2)                    
 methods    * 3.4.2      2017-09-29 local                             
 mime         0.5        2016-07-07 CRAN (R 3.4.2)                    
 mnormt       1.5-5      2016-10-15 CRAN (R 3.4.2)                    
 nlme         3.1-124    2016-01-20 CRAN (R 3.2.3)                    
 odbc       * 1.1.3.9000 2017-10-19 Github (edgararuiz/odbc@a289050)  
 openssl      0.9.7      2017-09-06 CRAN (R 3.4.2)                    
 parallel     3.4.2      2017-09-29 local                             
 pkgconfig    2.0.1      2017-03-21 CRAN (R 3.4.2)                    
 plyr         1.8.4      2016-06-08 CRAN (R 3.4.2)                    
 psych        1.7.8      2017-09-09 CRAN (R 3.4.2)                    
 purrr        0.2.4      2017-10-18 cran (@0.2.4)                     
 R6           2.2.2      2017-06-17 CRAN (R 3.4.2)                    
 Rcpp         0.12.13    2017-09-28 CRAN (R 3.4.2)                    
 reprex       0.1.1      2017-01-13 CRAN (R 3.4.2)                    
 reshape2     1.4.2      2016-10-22 CRAN (R 3.4.2)                    
 rlang        0.1.2      2017-08-09 CRAN (R 3.4.2)                    
 rmarkdown    1.6        2017-06-15 CRAN (R 3.4.2)                    
 rprojroot    1.2        2017-01-16 CRAN (R 3.4.2)                    
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.2)                    
 shiny        1.0.5      2017-08-23 CRAN (R 3.4.2)                    
 sparklyr     0.6.3      2017-09-19 CRAN (R 3.4.2)                    
 stats      * 3.4.2      2017-09-29 local                             
 stringi      1.1.5      2017-04-07 CRAN (R 3.4.2)                    
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.2)                    
 tibble       1.3.4      2017-08-22 CRAN (R 3.4.2)                    
 tidyr        0.7.1      2017-09-01 CRAN (R 3.4.2)                    
 tools        3.4.2      2017-09-29 local                             
 utils      * 3.4.2      2017-09-29 local                             
 whisker      0.3-2      2013-04-28 CRAN (R 3.4.2)                    
 withr        2.0.0      2017-07-28 CRAN (R 3.4.2)                    
 xtable       1.8-2      2016-02-05 CRAN (R 3.4.2)                    
 yaml         2.1.14     2016-11-12 CRAN (R 3.4.2)          

</details>

**Comment by ronblum** [comment]
Going through step by step, instead of running all the code quickly—such as running a markdown chunk—works fine. Perhaps this is an issue with the Teradata sandbox. However, the pop-up seems superfluous, and the user can see the failure with the information in the output.

**Comment by nwstephens** [comment]
Does this happen on all OS's?

**Comment by ronblum** [comment]
I was seeing the issue on Ubuntu 16 pointing to Teradata. Now, though, I've not been able to reproduce it on Ubuntu 16—but I've sporadically done so on SUSE 12 and RedHat 7. In addition, I've now seen the same issue with Ubuntu 16 pointing to SQL Server and Postgres, and SUSE 12 pointing to Postgres. It's similarly sporadic, and I'm seeing these now because I'm intentionally running them much more often. The problem only occurs if I run an entire chunk containing a series of steps. If I run slowly, step by step, everything is fine.

The functions I've seen present the error ("Error in connection_sql_tables(connection@ptr, catalog, schema, name"):
- SQL Server & Teradata: dbWriteTable() and dbDisconnect()/dbIsValid()
- Postgres: dbConnect() and dbRemoveTable()/dbExistsTable()

Note that the processes complete as expected and the subsequent tasks run, despite the errors and the pop-ups.

**Comment by ronblum** [comment]
Likely due to creating (and closing) lots of DB connections in the same R session. The solution is to end the R session and start a new one before creating a new DB connection.

**Comment by afpapa2** [comment]
I'm having the exact same issue as ronblum. The issue seems to happen only when I run code in blocks, but now when I step through line by line.

I'm going to be moving this code to an R shiny application.  I'm hoping this doesn't throw errors at users. Hopefully will be fixed soon.

**Comment by jimhester** [comment]
I don't know what the cause of this would be, but I can't imagine it being something wrong in the R package, so am closing this.
