### ISSUE TITLE
Unable to execute query under Rscript.exe

### ISSUE THREAD

**Issue by nzbart** [r-dbi/odbc#131]
### Issue Description and Expected Result
Script that runs correctly in interactive mode fails when run with RScript.exe.

The script runs fine when I source it from RStudio or the R.exe command line, however I get the following error when running from the command line using RScript.exe:

```text
PS> & 'C:\Program Files\R\R-3.4.2\bin\Rscript.exe' '.\Repro.R'
Loading required package: odbc
Error in .setupMethodsTables(fdef, initialize = TRUE) :
  trying to get slot "group" from an object of a basic class ("NULL") with no slots
Calls: dbGetQuery ... initialize -> as -> .getMethodsTable -> .setupMethodsTables
Execution halted
```

### Database
SQL Server 2016 on Windows 10.

### Reproducible Example
``` r
require(odbc)
#> Loading required package: odbc

con <- dbConnect(
  odbc::odbc(),
  driver = "ODBC Driver 13 for SQL Server",
  server = "(local)",
  trusted_connection = "yes")
dbGetQuery(con, "select 1")
#>    
#> 1 1
```
<details>
<summary>Session Info</summary>

I'm running the latest version of odbc:

``` r
require(pacman)
#> Loading required package: pacman
p_version(odbc)
#> [1] '1.1.3'
```

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.2 (2017-09-28)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_New Zealand.1252    
#>  tz       Pacific/Auckland            
#>  date     2017-11-14
#> Packages -----------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.1.1   2017-09-25 CRAN (R 3.4.1)
#>  base      * 3.4.2   2017-09-28 local         
#>  compiler    3.4.2   2017-09-28 local         
#>  datasets  * 3.4.2   2017-09-28 local         
#>  devtools    1.13.4  2017-11-09 CRAN (R 3.4.2)
#>  digest      0.6.12  2017-01-27 CRAN (R 3.4.0)
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.4.2)
#>  graphics  * 3.4.2   2017-09-28 local         
#>  grDevices * 3.4.2   2017-09-28 local         
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.0)
#>  knitr       1.17    2017-08-10 CRAN (R 3.4.2)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.0)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.1)
#>  methods   * 3.4.2   2017-09-28 local         
#>  Rcpp        0.12.13 2017-09-28 CRAN (R 3.4.2)
#>  rmarkdown   1.6     2017-06-15 CRAN (R 3.4.2)
#>  rprojroot   1.2     2017-01-16 CRAN (R 3.4.0)
#>  stats     * 3.4.2   2017-09-28 local         
#>  stringi     1.1.5   2017-04-07 CRAN (R 3.4.0)
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.4.0)
#>  tools       3.4.2   2017-09-28 local         
#>  utils     * 3.4.2   2017-09-28 local         
#>  withr       2.1.0   2017-11-01 CRAN (R 3.4.2)
#>  yaml        2.1.14  2016-11-12 CRAN (R 3.4.0)
```

</details>

**Comment by jimhester** [comment]
Rscript does not load the methods package in it's default packages which is why you get an error.

But the real issue here is you need to attach the `DBI` package, rather than odbc.

Substituting `library(DBI)` for `require(odbc)` makes this work as expected.

**Comment by nzbart** [comment]
Thanks, @jimhester - that caused the `methods` packaged to be loaded, and my script works correctly now.

**Comment by mkirzon** [comment]
@jimhester i've run into a really similar issue but in my case its during `devtools::check()` of another package that calls `DBI::dbGetQuery(...)` in its `.onLoad()`. 
Troubleshooting this reveals to me that in one of the checks ("checking whether the namespace can be loaded with stated dependencies"), it essentially starts a clean R session without base packages like methods loaded. Examining the search() path at .onLoad during that particular tests proves the error - 
![image](https://user-images.githubusercontent.com/5666220/97367054-b0171b80-1865-11eb-8f69-da05c44e7ac3.png)

What do you suggest doing in that case? I could run `require(methods)` within the `.onLoad()` but that also is incorrect design.

**Comment by shrektan** [comment]
The latest R (since3.5?) already solves this. It loads the  methods package in Rscript. If you can update your R version, things will get simpler.

**Comment by mkirzon** [comment]
@shrektan i ran with 3.5.0 and 3.6.3 and still get the same issue
