### ISSUE TITLE
Getting 'std::bad_alloc' error in R when connecting to impala odbc

### ISSUE THREAD

**Issue by anchal02** [r-dbi/odbc#132]
Trying to build a connection with impala odbc driver in R terminal.

library(implyr)
library(dplyr)
library(odbc)
drv <- odbc::odbc()
impala = src_impala( 
               drv = drv,
               driver = "Cloudera ODBC Driver for Impala 64-bit",
               dsn = "ImpalaDSN" )

Gets error:
terminate called after throwing an instance of 'std::bad_alloc'
what(): std::bad_alloc

**Comment by jimhester** [comment]
Not sure the cause of the bad alloc, but I think you will have better success tracking this down at the [implyr issue tracker](https://github.com/ianmcook/implyr/issues)
