### ISSUE TITLE
dbReadTable(con, "Stand") does not work

### ISSUE THREAD

**Issue by mateusz1981** [r-dbi/odbc#135]
### Issue Description and Expected Result

library(odbc)
con <- dbConnect(odbc::odbc(), "xxxxxx")
data <- dbReadTable(con, "Bestand")
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbReadTable’ for signature ‘"Microsoft SQL Server", "character"’
but functions as 
dbListTables(con, table_name = "f%")
dbListFields(con, "Bestand")

works fine
### Database
Microsoft SQL server

**Comment by colearendt** [comment]
Can you try to add `library(DBI)` to the top of your code, and then run to see if you get the same issue?  `dbReadTable` is not exported from the `odbc` package, I don't think.  

Also, note that the [`reprex`](http://reprex.tidyverse.org/articles/reprex.html) package can help you create more easily reproducible examples, easier to read code, etc.  Just use `reprex::reprex({<<my code here>>})`.
