### ISSUE TITLE
dbDisconnect doesn't always close the connection after a committed transaction

### ISSUE THREAD

**Issue by chrishaug** [r-dbi/odbc#137]
I'm having an issue with transactions in `odbc` and closing the connection afterwards. Please let me know if there's something I'm missing. Thanks.

### Issue Description and Expected Result

If an explicit transaction is started with `odbc::dbBegin`, and then committed with `odbc::dbCommit`, then `odbc::dbDisconnect` does not appear to actually close the connection with the database. 

If you try to call `dbDisconnect` a second time, the "Connection already closed" warning message appears, `dbIsValid` is `FALSE`, and the entry for that connection does disappear from the RStudio "Connections" pane, but the connection does not appear to be actually closed at the database. For example, DB2 will list that connection as still open with the "db2 list applications" command, and Access will not delete its lock file (*.laccdb). Restarting R seems to close the connection.

The behavior is the same whether or not any actual work is done within the transaction. If work is done, committing does seem to work (changes are visible in the DB). If the transaction is cancelled with `dbRollback` instead, the subsequent `dbDisconnect` appears to work correctly.

I'm more interested in getting it to work with DB2, but I had tried Access as well to see if it was driver/database-specific. I would try others but I don't have any other drivers installed.

### Database

IBM DB2 LUW 10.5.1, MS Access 2016

### Reproducible Example
Since the unwanted behavior is visible even when no work is done in the transaction, no specific table definitions or data should be required. I use a blank, brand new Access database file below, which seemed the easiest.

```r
cstr <- "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=C:/blank_database.accdb;"
conn <- odbc::dbConnect(odbc::odbc(), .connection_string = cstr)

odbc::dbBegin(conn)
odbc::dbCommit(conn)

odbc::dbDisconnect(conn)
```

**Comment by jimhester** [comment]
I believe this is the same issue as https://github.com/r-dbi/odbc/issues/136 and should be fixed in the devel version of odbc.
