### ISSUE TITLE
R breaks when I state a wrong server in dbConnect() using SQL Server

### ISSUE THREAD

**Issue by maxPunck** [r-dbi/odbc#139]
### Issue Description and Expected Result
dbConnect(odbc::odbc(), .connection_string = ...) works fine except for one issue:
If there is a wrong or misspelled Server in the connection string, R will state "Keine Rückmeldung" ("No response") and, well, won't respond anymore. I'm using Rx64 3.4.1.

### Database
SQL Server 2014

### Reproducible Example

```r
library(DBI)

cs <- "Driver={SQL Server};
        Server=XYZ;
        Database=testDB;
        UID=;
        Pwd=;
        trusted_connection=TRUE;" 

con <- dbConnect(odbc::odbc(), .connection_string = cs)
```

**Comment by cj-wilson** [comment]
I have a similar issue.  The configuration where I specify a user name (local) will hang or fail to login.  I can run osql scripts through both the local user and domain auth.

<<<this hangs
Microsoft SQL Server 2012
$drivername
[1] "SQLSRV32.DLL"
$odbc.version
[1] "03.80.0000"
$driver.version
[1] "06.01.7601"
$odbcdriver.version
[1] "03.52"
$supports.transactions
[1] TRUE

con <- DBI::dbConnect(odbc::odbc(),
                      Driver    = "SQL Server",
                      Server    = mssql_host,
                      Database  = database,
                      UID       = "test_user",
                      PWD       = rstudioapi::askForPassword("Database password"),
                      Port      = 1433)

<<<this works
con <- DBI::dbConnect(odbc::odbc(),
                      driver = "SQL Server",
                      server = "mssql_host",
                      database = database,
                      trusted_connection = TRUE,
                      Port = 1433)

**Comment by jimhester** [comment]
Note to self: nanodbc exposes a `timeout` parameter we can use to timeout a connection after a period of time.

**Comment by jimhester** [comment]
You are now able to specify a timeout to `dbConnect`.

e.g. to timeout the connection attempt after 15 seconds
```r
library(DBI)
con <- dbConnect(odbc::odbc(), 
  Driver = "{SQL Server}",
  Server = "XYZ",
  Database = "testDB",
  UID = "foo", 
  Pwd = "bar",
  timeout = 15)
```

**Comment by vpanfilov** [comment]
@jimhester, thanks! When can we expect the next CRAN release?

**Comment by fpirotti** [comment]
I also find this issue very important. It can also hang a log of apps developed with R (i.e. Shiny) that use connection to a DB server which is temporarily unavailble.

**Comment by jimhester** [comment]
There was a CRAN release in June, this is in odbc v1.1.6.

**Comment by hannes101** [comment]
I am still seeing this issue, even though I defined a timeout the command trying to establish a connection just hangs and blocks the R session. odbc 1.2.2 and DBI 1.1.0 on R 3.6.1
