### ISSUE TITLE
can't write chinese characters to sql server correctly

### ISSUE THREAD

**Issue by shizidushu** [r-dbi/odbc#143]
> sessionInfo()
    R version 3.4.3 (2017-11-30)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 16.04 LTS
    
    Matrix products: default
    BLAS: /usr/lib/libblas/libblas.so.3.6.0
    LAPACK: /usr/lib/lapack/liblapack.so.3.6.0
    
    locale:
      [1] LC_CTYPE=en_US.UTF-8          LC_NUMERIC=C                 
    [3] LC_TIME=en_US.UTF-8           LC_COLLATE=en_US.UTF-8       
    [5] LC_MONETARY=en_US.UTF-8       LC_MESSAGES=en_US.UTF-8      
    [7] LC_PAPER=en_US.UTF-8          LC_NAME=en_US.UTF-8          
    [9] LC_ADDRESS=en_US.UTF-8        LC_TELEPHONE=en_US.UTF-8     
    [11] LC_MEASUREMENT=en_US.UTF-8    LC_IDENTIFICATION=en_US.UTF-8
    
    attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
      [1] dplyr_0.7.4 DBI_0.7    
    
    loaded via a namespace (and not attached):
      [1] RSQLServer_0.3.0 Rcpp_0.12.14     dbplyr_1.1.0     assertthat_0.2.0
    [5] R6_2.2.2         odbc_1.1.3       magrittr_1.5     rlang_0.1.6     
    [9] blob_1.1.0       bindrcpp_0.2     tools_3.4.3      bit64_0.9-7     
    [13] glue_1.2.0       purrr_0.2.4      bit_1.1-12       hms_0.4.0       
    [17] yaml_2.1.16      compiler_3.4.3   pkgconfig_2.0.1  rJava_0.9-9     
    [21] bindr_0.1        tibble_1.3.4    

I install mssql-server-linux docker container on my computer. Then I write dataframe contains chinese to 
mssql. But I get "?" for all chinese character when I collect the table from mssql.

## Docker Pull Microsoft SQL Server for Linux
```
docker pull store/microsoft/mssql-server-linux:2017-GA
docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 -d microsoft/mssql-server-linux:2017-GA
```

## Install Microsoft ODBC Driver on Ubuntu 16.04
Follow the instructions in this link:
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server

```
sudo su 
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
exit
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install msodbcsql
# optional: for bcp and sqlcmd
sudo ACCEPT_EULA=Y apt-get install mssql-tools
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
source ~/.bashrc
# optional: for unixODBC development headers
sudo apt-get install unixodbc-dev
```

## Create a test database in mssql docker container
Connect to Microsoft SQL Server

```
docker exec -it <container_id|container_name> /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P <your_password>
```

create a test database
```
CREATE DATABASE biDB
SELECT Name from sys.Databases
GO
```

## Write a table contains chinese to Sql Server and then fetch it

```
library(DBI)
library(dplyr)
con <- dbConnect(odbc::odbc(),
                 .connection_string = "Driver={ODBC Driver 13 for SQL Server};",
                 server = "192.168.1.88", Database = "biDB", UID = "sa",
                 PWD = "yourStrong(!)Password", Port = 1433)

test_df <- data.frame(x = c("一", "十"), y = "中文", z = "chinese")
copy_to(con, test_df, "test_tb",
        temporary = FALSE,
        overwrite = TRUE,
        indexes = list(c("x")))

tbl(con, "test_tb") %>% collect()
```

## Here is the results
```
# A tibble: 2 x 3
      x     y       z
  <chr> <chr>   <chr>
1     ?    ?? chinese
2     ?    ?? chinese
```

SSMS shows the columns:

```
x(var(char(255),null)
y(var(char(255),null)
z(var(char(255),null)
```

However, I just find RSQLServer works today.

```
con <- dbConnect(RSQLServer::SQLServer(),
                 server="192.168.1.88",
                 port=1433,
                 database = "biDB",
                 properties=list(useNTLMv2="false",
                                 user="sa",
                                 password="yourStrong(!)Password")
)
```

**Comment by jimhester** [comment]
If the database is using a different native encoding than your local session you need to specify it with the `encoding` parameter to `dbConnect()`, see `?odbc::dbConnect` for more details.

**Comment by shizidushu** [comment]
I don't know the text encoding of the sql server. I only find the Collation name (SQL_Latin1_General_CP1_CI_AS) of the SQL Server database.

**Comment by shrektan** [comment]
@shizidushu you may try to use GB2312 as the encoding.

**Comment by shizidushu** [comment]
After adding `encoding = 'GB2312'`, it errors when `copy_to`
    > copy_to(con, test_df, name = "test_tb",
              +         temporary = FALSE,
              +         overwrite = TRUE,
              +         indexes = list(c("x")))
    Error in nchar(as.character(x)) : invalid multibyte string, element 1

**Comment by shizidushu** [comment]
I find I can write chinese correctly in SSMS and then check the data types. It is `nchar(10)`. So I set the `filed.types` of dbWriteTable. It works now (under ubuntu).

    library(DBI)
    library(dplyr)
    library(odbc)
    
    con <- DBI::dbConnect(odbc::odbc(), 
                          Driver = "ODBC Driver 13 for SQL Server", 
                          server = "192.168.1.88", Database = "biDB", UID = "sa",
                          PWD = "yourStrong(!)Password", Port = 1433)
    
    test_df <- data.frame(x = c("一", "十"), y = "中文", z = "Chinese")
    dbWriteTable(con, 'test_df', test_df,
                 temporary = FALSE,
                 overwrite = TRUE,
                 field.types = c(x = "nchar(10)", y = "nchar(10)", z = "nchar(10)"))
    
    
    tbl(con, "test_df") %>% collect()
    
    
    dbDisconnect(con)


However, I find this solution doesn't work in Windows 10. It returns:

    > tbl(con, "test_df") %>% collect()
    # A tibble: 2 x 3
    x                      y           z           
    <chr>                  <chr>       <chr>       
      1 "Nä¸€      "           "ä¸­æ–‡    " "chinese   "
    2 "å\u008d\u0081       " "ä¸­æ–‡    " "chinese   "

    > sessionInfo()
    R version 3.4.3 (2017-11-30)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows >= 8 x64 (build 9200)
    
    Matrix products: default
    
    locale:
      [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    
    
    attached base packages:
      [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
      [1] odbc_1.1.3  dplyr_0.7.4 DBI_0.7    
    
    loaded via a namespace (and not attached):
      [1] Rcpp_0.12.14     utf8_1.1.3       crayon_1.3.4     dbplyr_1.2.0     assertthat_0.2.0
    [6] R6_2.2.2         magrittr_1.5     pillar_1.0.1     cli_1.0.0        rlang_0.1.6     
    [11] blob_1.1.0       bindrcpp_0.2     tools_3.4.3      bit64_0.9-7      glue_1.2.0      
    [16] bit_1.1-12       hms_0.4.0        compiler_3.4.3   pkgconfig_2.0.1  bindr_0.1       
    [21] tibble_1.4.1

**Comment by shizidushu** [comment]
@shrektan You're right. The problem lies in the encoding. I have to set the encoding right. If the collation is Chinese_PRC_CI_AS, I will have to set it to WINDOWS-1252. Then I can read table contains chinese.

It's not easy to write data contains unicode to sql server using R. It may behave differently accorrding to the operating system and collation. And it seems unworthy to write to sql server using R. So I close this issue.

**Comment by shrektan** [comment]
@shizidushu Encoding issue is really hard, especially on Windows. Regarding to writing to sql server, if you don't care cross-platform ability, I suggest you write a wrapper to call the sql server command `BCP` directly. It's super fast and stable.

**Comment by aryoda** [comment]
> I don't know the text encoding of the sql server. I only find the Collation name (SQL_Latin1_General_CP1_CI_AS) of the SQL Server database.

IMHO if you use a `nvarchar` column all strings are stored in unicode encoding ("n" = "international"?).

The `Collation` setting in MS SQL Server does only specify how strings are sorted and compared (case sensitive or not, normalize accents or not...) so IMHO the collation does not help (or disturb) in case of encoding problems.

I am just preparing another code example with mixed encodings (native, latin1 and UTF8) to make the encoding problem more clear and reproducible for all databases supported by `odbc` and open an issue then...
