### ISSUE TITLE
Oracle connectivity

### ISSUE THREAD

**Issue by UpsideDownRide** [r-dbi/odbc#144]
I have a problem connecting to Oracle DB using ODBC. ODBC drivers are installed and when I test connection through ODBC admin tool in windows it is ok. However, in R I'm running into the following problem:

    con <- dbConnect(odbc::odbc(), "ORACLEDNS")
    Error: nanodbc/nanodbc.cpp:950: 28000: [Oracle][ODBC][Ora]ORA-01005: null password given; logon denied

Adding PWD results in R session being unresponsive without providing any type of error. 

    con <- dbConnect(odbc::odbc(), "ORACLEDNS", PWD = "password")

How can I debug the issue, what might be the problem?

DB Version:

Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production

**Comment by jimhester** [comment]
I am not sure, are you able to connect to the same DNS using `RODBC` or `ROracle`?

**Comment by edgararuiz** [comment]
Hi, can you compare the entries in the ORACLEDNS and this page: http://db.rstudio.com/databases/oracle/ ?  I'm wondering if there may be a setting that the admin tool is automatically sending, such as port number, that is not set automatically by `odbc`.

**Comment by copernican** [comment]
It may be necessary to pass the `uid` argument (the default is `NULL`) if you 

- have not saved a User ID for the DSN in the ODBC Data Source Administrator
- want to connect as a user other than the one saved

```r
con <- DBI::dbConnect(odbc::odbc(), dsn = dsn, pwd = pwd)
#> Error: nanodbc/nanodbc.cpp:950: 28000: [Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied
```
And with the `uid` argument:
```r
con <- DBI::dbConnect(odbc::odbc(), dsn = dsn, uid = uid, pwd = pwd)
DBI::dbListTables(con, schema_name = "SYS", table_name = "DUAL")
#> [1] "DUAL"
```

**Comment by smitsrr** [comment]
It looks like this issue was resolved for the requester, or at least the requester figured it out. 

I'm having a problem getting R to recognize my data source names. I have both User DSN and System DSN's configured, and connected. Yet when I pass:

`
dw_con = DBI::dbConnect(odbc::odbc(), dbname="DSN_NAME")
`
I get:
`
Error: nanodbc/nanodbc.cpp:950: IM002: [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified
`

**Comment by copernican** [comment]
Try `dsn = "DSN_NAME"` (rather than `dbname`) per the `odbc::dbConnect()` documentation.

**Comment by smitsrr** [comment]
`
dw_con = DBI::dbConnect(odbc::odbc(), "REDDBTST")
Error: nanodbc/nanodbc.cpp:950: 28000: [Oracle][ODBC][Ora]ORA-01005: null password given; logon denied
 `

**Comment by copernican** [comment]
It appears you may need to pass the `uid` and `pwd` arguments, as shown above.

**Comment by edgararuiz** [comment]
Right, the DSN more likely does not contain the credentials.

**Comment by smitsrr** [comment]
Why does this document imply that using DSN's are a way to secure deployed content? 
http://db.rstudio.com/best-practices/managing-credentials/

Is this only if Kerberos is used?

**Comment by edgararuiz** [comment]
Even without Kerberos, the use of DSNs will allow you to avoid adding the server name/IP and database name in the code.

**Comment by jimhester** [comment]
These connection issues are not anything we can address in the odbc package, so I will close this issue.

Unfortunately setting up and connecting to oracle databases is very complicated :(
