### ISSUE TITLE
R session corrupts if ODBC connection doesn't return a data.frame

### ISSUE THREAD

**Issue by shrektan** [r-dbi/odbc#145]
### Issue Description and Expected Result

As you know, `ODBC` is not always used to connect a database, there're data services provide API via ODBC connection. We send correponding query command to the connection and it returns the data. 

However, if the api thinks the query command is invalid or it can't be returned as a data.frame, it returns a character error message.

It works fine on `RODBC` because `RODBC` simply return the error message to R. 

In the contrast, `odbc` will try to parse the character error message to a `data.frame` and it leads to the corruption of the R session.

The expected result is an R error message. It should not leads to the corruption of R sessions.

### Database
The data service is [Tinysoft](http://www.tinysoft.com.cn). I'm afraid that you can't reproduce since it's not for free.

### Reproducible Example
As mentioned above, the api is not free, so you can't reproduce it. 

#### works fine in RODBC
```r
sql <- "setsysparam(pn_stock(), 'SZ000002'); return close();"
rodbc_conn <- RODBC::odbcConnect("Tinysoft")
RODBC::sqlQuery(rodbc_conn, sql, stringsAsFactors = FALSE)
# [1] "S1000 -1 General error---Execute: unsupported return type"                                    
# [2] "[RODBC] ERROR: Could not SQLExecDirect 'setsysparam(pn_stock(), 'SZ000002'); return close();'"
```

#### R session corrupts in odbc
```r
conn <- DBI::dbConnect(odbc::odbc(), "Tinysoft", encoding = "GB2312")
DBI::dbGetQuery(conn, sql)
```

**Comment by jimhester** [comment]
You should be using `DBI::dbExecute()` if the results of your query are not a table.

**Comment by shrektan** [comment]
@jimhester Thanks for your reply but I tried and `DBI::dbExecute()` still break the r session. Again, `RODBC` will be fine. Any ideas?

**Comment by jimhester** [comment]
I would suggest running R in a debugger and seeing where it crashes.

**Comment by shrektan** [comment]
I suspect that it's an issue from the api itself. So I will close issue for now. Thanks for the help.
