### ISSUE TITLE
dbConnect can hang forever with certain odbc drivers

### ISSUE THREAD

**Issue by vpanfilov** [r-dbi/odbc#148]
### Issue Description and Expected Result
Connecting to MS SQL Server with Microsoft ODBC Driver 13.1 hangs forever if DB server is unavailable This issue can be tested with odbc driver only, no need of actual MS SQL Server running. Just specify random IP adrress or even *localhost* as the `host` parameter.

### Database
MS SQL Server with "Microsoft ODBC Driver 13.1 for SQL Server". Result is the same for connecting both from Windows and Linux machines.

### Reproducible Example

1. Install official Microsoft ODBC Driver 13.1:

    - [Linux/MacOS](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server)
    - [Windows](https://docs.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server)

2.  Run this example (no need of MS SQL Server):
```r
library(odbc)
library(DBI)
conn <- dbConnect(odbc::odbc(), Driver = "ODBC Driver 13 for SQL Server", Server = "localhost", UID = "test", PWD = "test")
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.3 (2017-11-30)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Russian_Russia.1251         
#>  tz       Europe/Moscow               
#>  date     2018-01-23
#> Packages -----------------------------------------------------------------
#>  package   * version date       source        
#>  backports   1.1.2   2017-12-13 CRAN (R 3.4.3)
#>  base      * 3.4.3   2017-12-06 local         
#>  compiler    3.4.3   2017-12-06 local         
#>  datasets  * 3.4.3   2017-12-06 local         
#>  devtools    1.13.4  2017-11-09 CRAN (R 3.4.3)
#>  digest      0.6.14  2018-01-14 CRAN (R 3.4.3)
#>  evaluate    0.10.1  2017-06-24 CRAN (R 3.4.1)
#>  formatR     1.5     2017-04-25 CRAN (R 3.4.2)
#>  graphics  * 3.4.3   2017-12-06 local         
#>  grDevices * 3.4.3   2017-12-06 local         
#>  htmltools   0.3.6   2017-04-28 CRAN (R 3.4.1)
#>  knitr       1.18    2017-12-27 CRAN (R 3.4.3)
#>  magrittr    1.5     2014-11-22 CRAN (R 3.4.1)
#>  memoise     1.1.0   2017-04-21 CRAN (R 3.4.2)
#>  methods   * 3.4.3   2017-12-06 local         
#>  Rcpp        0.12.15 2018-01-20 CRAN (R 3.4.3)
#>  rmarkdown   1.8     2017-11-17 CRAN (R 3.4.3)
#>  rprojroot   1.3-2   2018-01-03 CRAN (R 3.4.3)
#>  stats     * 3.4.3   2017-12-06 local         
#>  stringi     1.1.6   2017-11-17 CRAN (R 3.4.2)
#>  stringr     1.2.0   2017-02-18 CRAN (R 3.4.1)
#>  tools       3.4.3   2017-12-06 local         
#>  utils     * 3.4.3   2017-12-06 local         
#>  withr       2.1.1   2017-12-19 CRAN (R 3.4.3)
#>  yaml        2.1.16  2017-12-12 CRAN (R 3.4.3)
```

</details>

**Comment by vpanfilov** [comment]
Sorry, just noticed that my bug report duplicates https://github.com/r-dbi/odbc/issues/139.

**Comment by viksvig** [comment]
The official documents does not say anything about the configuration. I have freetds and unixodbc but want to replace with ODBC driver 13.1. Can you explain me the steps or link where I can find the steps for Linux server
