### ISSUE TITLE
Inconsistent error about prepared statement already existing

### ISSUE THREAD

**Issue by timabe** [r-dbi/odbc#151]
### Issue Description and Expected Result
I'm running R Markdown documents with SQL chunks on a scheduler, and using `odbc::odbc()` to establish my connection to my Redshift database. 

These documents run daily, and I'd say about 30% of the time the runs result in this error:

```
nanodbc/nanodbc.cpp:1587: 42P05: ERROR: prepared statement "_PLAN0x506b440" already exists;
```

The strange thing is the error is inconsistent - I'm not changing the code. Like I mentioned, it works about 70% of the time, the successes seem random.

These queries are just `SELECT` queries. I'm not, as far as I know, creating prepared statements. 

### Database
```
> SELECT VERSION();

PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1582
```

I've googled the error but almost nothing comes up. Any ideas?

**Comment by colearendt** [comment]
Hey @timabe!  Thanks for the note.  It sounds like a prepared statement may be created "behind the scenes" by some of the functions you are calling.  Can you provide a [minimal reproducible example](https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/) that shows some of the functions that you are calling in this pipeline?  

I suspect that the name there (`"_PLAN0x506b440"`) is randomly generated and so if the same name gets randomly generated twice in the wrong context then an error is thrown.  This would explain the intermittent nature of the issue.

**Comment by mjpdenver** [comment]
This happens to me as well.  

I can't provide an example, since I am working on internal redshift AWS databases, but in a task where I query a list of tables with a for loop,  using dbplyr to summarize the files, I will get the following error in random and inconsistent places.  This doesn't occur using RODBC queries.

Error: <SQL> 'SELECT count(*) AS "n()"
FROM "datatable1"'
  nanodbc/nanodbc.cpp:1587: 42P05: ERROR: prepared statement "_PLAN0x10f82370" already exists;
Error while executing the query

**Comment by mjpdenver** [comment]
I have tried inserting  sys.sleep() as well as disconnecting and reconnecting between  queries.  The latter helps a bit more, but not consistently and  obviously this gets cumbersome.  As I mentioned, this doesn't happen with - for example a loop using RODBC's sqlQuery.

**Comment by javierluraschi** [comment]
Ran:

```r
for (i in seq_len(100)) {
  print(paste("Retrieved ", length(DBI::dbGetQuery(con, "SELECT * FROM \"dbo\".\"sysdac_history_internal\"")), "records."))
}
```

Against a SQL Azure database and couldn't hit this issue, I think we need a repro like colearendt suggests with instructions starting from scratch, as in, install DB, run this R script. Might help to provide a docker image if the setup is more complex, etc.

**Comment by jimhester** [comment]
We now support direct execution via specifying `immediate = TRUE` which would avoid the implicit prepared queries (and presumably this issue).
