### ISSUE TITLE
Cannot install odbc on SUSE Linux Server 11

### ISSUE THREAD

**Issue by mhsilvav** [r-dbi/odbc#152]
### Issue Description and Expected Result
When installing odbc package using R CMD INSTALL got a compilation errors:  [time_zone_info.o] Error 1 and [cctz/libcctz.a] Error 2, and I'm unable to install the package :...7

### OS
<pre>
$ cat /etc/SuSE-release
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 4
</pre>

### Reproducible Example
<pre>
$ R CMD INSTALL odbc_1.1.5.tar.gz
* installing *source* package ‘odbc’ ...
** package ‘odbc’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
PKG_CFLAGS=-DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG=8
PKG_LIBS=-L/usr/lib64 -lodbc
** libs
(cd cctz && \
make libcctz.a CC="gcc -std=gnu99" CXX="gcc-4.7 -std=c++11" AR="ar" ARFLAGS=rv CXXPICFLAGS="-fPIC")
make[1]: Entering directory `/tmp/RtmpAQxWrP/R.INSTALLb80935cc7d04/odbc/src/cctz'
gcc-4.7 -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_format.o src/time_zone_format.cc
gcc-4.7 -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_if.o src/time_zone_if.cc
gcc-4.7 -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_impl.o src/time_zone_impl.cc
gcc-4.7 -std=c++11  -Wall -Iinclude -std=c++11 -pthread  -O -fPIC -MMD  -c -o time_zone_info.o src/time_zone_info.cc
src/time_zone_info.cc: In function ‘int32_t cctz::{anonymous}::Decode32(const char*)’:
src/time_zone_info.cc:215:14: error: ‘UINT32_MAX’ was not declared in this scope
src/time_zone_info.cc: In function ‘int64_t cctz::{anonymous}::Decode64(const char*)’:
src/time_zone_info.cc:223:14: error: ‘UINT64_MAX’ was not declared in this scope
src/time_zone_info.cc: In member function ‘cctz::Breakdown cctz::TimeZoneInfo::LocalTime(int64_t, const cctz::TransitionType&) const’:
src/time_zone_info.cc:715:40: error: ‘INT64_MAX’ was not declared in this scope
src/time_zone_info.cc:720:40: error: ‘INT64_MIN’ was not declared in this scope
make[1]: *** [time_zone_info.o] Error 1
make[1]: Leaving directory `/tmp/RtmpAQxWrP/R.INSTALLb80935cc7d04/odbc/src/cctz'
make: *** [cctz/libcctz.a] Error 2
ERROR: compilation failed for package ‘odbc’
</pre>

<details>
<summary>Session Info</summary>
<pre>
Microsoft R Open 3.4.1
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2017 Microsoft Corporation
Using the Intel MKL for parallel mathematical computing (using 6 cores).
Default CRAN mirror snapshot taken on 2017-09-01.
See: https://mran.microsoft.com/.

devtools::session_info()

Session info ------------------------------------------------------------------
 setting  value
 version  R version 3.4.1 (2017-06-30)
 system   x86_64, linux-gnu
 ui       X11
 language (EN)
 collate  en_US.UTF-8
 tz       <NA>
 date     2018-01-30

Packages ----------------------------------------------------------------------
 package       * version date       source
 base          * 3.4.1   2017-09-06 local
 compiler        3.4.1   2017-09-06 local
 datasets      * 3.4.1   2017-09-06 local
 devtools        1.13.4  2017-11-09 CRAN (R 3.4.1)
 digest          0.6.12  2017-01-27 CRAN (R 3.4.1)
 graphics      * 3.4.1   2017-09-06 local
 grDevices     * 3.4.1   2017-09-06 local
 memoise         1.1.0   2017-04-21 CRAN (R 3.4.1)
 methods       * 3.4.1   2017-09-06 local
 RevoUtils       10.0.5  2017-09-06 local
 RevoUtilsMath * 10.0.0  2017-04-19 local
 stats         * 3.4.1   2017-09-06 local
 utils         * 3.4.1   2017-09-06 local
 withr           2.0.0   2017-07-28 CRAN (R 3.4.1)
</pre>
</details>

**Comment by jimhester** [comment]
It is hard to say for sure, but I think this indicates your compiler does not have full C++11 support. I would recommend trying to compile the package with a newer version of g++ if possible.
