### ISSUE TITLE
MSSQL Connection Description

### ISSUE THREAD

**Issue by berkorbay** [r-dbi/odbc#155]
### Issue Description and Expected Result

In the readme part connecting to MS SQL or SQL Server is not represented properly. After checking `odbcinst.ini` you can find the proper driver name. The latest driver name for Linux is "ODBC Driver 17 for SQL Server". You can add the code below.  Many other sources use "SQL Server" only which returns driver not found error.

### Database
SQL Server on Linux

### Reproducible Example

```r
con <- DBI::dbConnect(odbc::odbc(),
                      driver = "ODBC Driver 17 for SQL Server",
                      server = "<SERVER_IP_OR_localhost>",
                      database = "<YOUR_DB_NAME>",
                      uid = "<YOUR_DB_USER_ID>",
                      pwd = "<YOUR_DB_USER_PASS>")
```

**Comment by colearendt** [comment]
Hey @berkorbay.  Thanks for the note.  The value necessary when selecting a "Driver" will depend on the `odbcinst.ini` file that is present on your system, as you rightly point out.  For instance, on my system, `odbcinst.ini` looks like:

```
[SQLServer]
Driver = /opt/...
```
So I would connect with something like:
```r
con <- DBI::dbConnect(odbc::odbc(),
                      driver = "SQLServer",
                      server = "<SERVER_IP_OR_localhost>",
                      database = "<YOUR_DB_NAME>",
                      uid = "<YOUR_DB_USER_ID>",
                      pwd = "<YOUR_DB_USER_PASS>")
```

As a result of this being a somewhat arbitrary value that is system-dependent, I don't think this particular value is necessary to change.  If there is a section of the docs that could make this more clear, please feel free to point it out or suggest a PR!  Referencing line numbers can be helpful as well. 
 Thanks!

**Comment by jimhester** [comment]
As mentioned this setting is entirely arbitrary and system dependant.
