### ISSUE TITLE
Communication error connecting to db2 via IBM's odbc driver

### ISSUE THREAD

**Issue by colearendt** [r-dbi/odbc#160]
### Issue Description and Expected Result

When connecting via a DSN using `isql -v db2` or `dbConnect(odbc(), "db2")`, things work fine.  However, when copying the exact parameters into a `dbConnect` statement directly, we have issues.  I am hopeful that there is a parameter that needs to be defined that has a different default for the DSN and when using `dbConnect` directly.

### Database
Output of `db2level`
```
DB21085I  This instance or install (instance name, where applicable:
"db2inst1") uses "64" bits and DB2 code release "SQL10055" with level
identifier "0606010E".
Informational tokens are "DB2 v10.5.0.5", "s141128", "IP23633", and Fix Pack
"5".
Product is installed at "/home/db2inst1/sqllib".
```

### Reproducible Example
Admittedly, the reproducible example is in one sense easy enough, and in another sense tricky to communicate in a github issue.  I have included driver trace logs below so that the `reprex` will hopefully not be necessary.  If it is, please let me know and I will be happy to illustrate or share the necessary dockerfiles to make it reproducible locally.

The error message itself:
```
Error: nanodbc/nanodbc.cpp:950: 08001: [unixODBC][IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "::1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "99", "", "".  SQLSTATE=08001
```

successful trace with `isql`
```
isql -v db2
```
<details>
<pre>
[ODBC][371][1520903859.321585][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x55be4ba20750
[ODBC][371][1520903859.321614][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55be4ba20750
[ODBC][371][1520903859.321624][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x55be4ba21050
[ODBC][371][1520903859.321632][SQLConnect.c][3732]
                Entry:
                        Connection = 0x55be4ba21050
                        Server Name = [db2][length = 3 (SQL_NTS)]
                        User Name = [NULL]
                        Authentication = [NULL]
                UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'

[ODBC][371][1520903859.721912][SQLConnect.c][4310]
                Exit:[SQL_SUCCESS]
[ODBC][371][1520903859.721941][SQLGetFunctions.c][151]
                Entry:
                        Connection = 0x55be4ba21050
                        Id = SQLMoreResults
                        Supported = 0x55be4b4c9010
[ODBC][371][1520903859.721950][SQLGetFunctions.c][186]
                Exit:[SQL_SUCCESS]
                        Supported = 0x55be4b4c9010 -> 1
[ODBC][371][1520903861.365909][SQLDisconnect.c][208]
                Entry:
                        Connection = 0x55be4ba21050
[ODBC][371][1520903861.424814][SQLDisconnect.c][379]
                Exit:[SQL_SUCCESS]
[ODBC][371][1520903861.424836][SQLFreeHandle.c][284]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55be4ba21050
[ODBC][371][1520903861.424846][SQLFreeHandle.c][333]
                Exit:[SQL_SUCCESS]
[ODBC][371][1520903861.424854][SQLFreeHandle.c][219]
                Entry:
                        Handle Type = 1
                        Input Handle = 0x55be4ba20750
</pre>
</details>

Successful `dbConnect` using DSN:
```r
dbConnect(odbc(),"db2")
```

<details>
<pre>
[ODBC][375][1520904005.747087][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x561640ac2a00
[ODBC][375][1520904005.747122][SQLSetEnvAttr.c][189]
                Entry:
                        Environment = 0x561640ac2a00
                        Attribute = SQL_ATTR_ODBC_VERSION
                        Value = 0x3
                        StrLen = -5
[ODBC][375][1520904005.747133][SQLSetEnvAttr.c][364]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904005.747141][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x561640ac2a00
[ODBC][375][1520904005.747151][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x56164234bc00
[ODBC][375][1520904005.747163][SQLFreeHandle.c][284]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x56164234bc00
[ODBC][375][1520904005.747171][SQLFreeHandle.c][333]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904005.747178][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x561640ac2a00
[ODBC][375][1520904005.747185][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x56164234bc00
[ODBC][375][1520904005.747194][SQLSetConnectAttr.c][396]
                Entry:
                        Connection = 0x56164234bc00
                        Attribute = SQL_ATTR_LOGIN_TIMEOUT
                        Value = (nil)
                        StrLen = 0
[ODBC][375][1520904005.747202][SQLSetConnectAttr.c][671]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904005.747212][SQLDriverConnect.c][728]
                Entry:
                        Connection = 0x56164234bc00
                        Window Hdl = (nil)
                        Str In = [dsn=db2][length = 7 (SQL_NTS)]
                        Str Out = 0x7fff06ca1d80
                        Str Out Max = 2048
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'

[ODBC][375][1520904006.097755][SQLDriverConnect.c][1697]
                Exit:[SQL_SUCCESS]
                        Connection Out [[DSN=DB2;UID=db2inst1;PWD=*********;][length = 35 (SQL_NTS)]]
[ODBC][375][1520904006.097879][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_IDENTIFIER_QUOTE_CHAR (29)
                        Info Value = 0x7fff06ca6300
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca62de
[ODBC][375][1520904006.097897][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.097938][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_TXN_CAPABLE (46)
                        Info Value = 0x7fff06ca613e
                        Buffer Length = 0
                        StrLen = (nil)
[ODBC][375][1520904006.097951][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.097963][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_ODBC_VER (77)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.097972][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.097981][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_VER (7)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.097990][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.097998][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_ODBC_VER (10)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098006][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098014][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_NAME (6)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098023][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098031][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_SERVER_NAME (13)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098040][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098049][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DATA_SOURCE_NAME (2)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098056][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098064][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_USER_NAME (47)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098080][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098089][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DBMS_VER (18)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098099][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098107][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DBMS_NAME (17)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098115][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.098123][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DATABASE_NAME (16)
                        Info Value = 0x7fff06ca5d10
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5cee
[ODBC][375][1520904006.098131][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.111969][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_TXN_CAPABLE (46)
                        Info Value = 0x7fff06ca61ce
                        Buffer Length = 0
                        StrLen = (nil)
[ODBC][375][1520904006.111993][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112004][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_ODBC_VER (77)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112014][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112022][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_VER (7)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112034][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112042][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_ODBC_VER (10)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112050][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112057][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DRIVER_NAME (6)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112065][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
        [ODBC][375][1520904006.112073][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_SERVER_NAME (13)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112081][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112089][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DATA_SOURCE_NAME (2)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112095][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112102][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_USER_NAME (47)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112110][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112118][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DBMS_VER (18)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112127][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112134][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DBMS_NAME (17)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112142][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
[ODBC][375][1520904006.112150][SQLGetInfo.c][554]
                Entry:
                        Connection = 0x56164234bc00
                        Info Type = SQL_DATABASE_NAME (16)
                        Info Value = 0x7fff06ca5da0
                        Buffer Length = 1024
                        StrLen = 0x7fff06ca5d7e
[ODBC][375][1520904006.112158][SQLGetInfo.c][617]
                Exit:[SQL_SUCCESS]
</pre>
</details>

And the failure with `dbConnect` directly:

```r
dbConnect(drv=odbc(), Driver=..., Host=..., Port=..., ...) #same parameters as DSN
```

<details>
<pre>
[ODBC][351][1520903671.279373][__handles.c][460]
                Exit:[SQL_SUCCESS]
                        Environment = 0x55d8ede2fbe0
[ODBC][351][1520903671.279411][SQLSetEnvAttr.c][189]
                Entry:
                        Environment = 0x55d8ede2fbe0
                        Attribute = SQL_ATTR_ODBC_VERSION
                        Value = 0x3
                        StrLen = -5
[ODBC][351][1520903671.279421][SQLSetEnvAttr.c][364]
                Exit:[SQL_SUCCESS]
[ODBC][351][1520903671.279430][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55d8ede2fbe0
[ODBC][351][1520903671.279438][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x55d8ee1faf60
[ODBC][351][1520903671.279451][SQLFreeHandle.c][284]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55d8ee1faf60
[ODBC][351][1520903671.279458][SQLFreeHandle.c][333]
                Exit:[SQL_SUCCESS]
[ODBC][351][1520903671.279466][SQLAllocHandle.c][375]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55d8ede2fbe0
[ODBC][351][1520903671.279474][SQLAllocHandle.c][493]
                Exit:[SQL_SUCCESS]
                        Output Handle = 0x55d8ee1faf60
[ODBC][351][1520903671.279482][SQLSetConnectAttr.c][396]
                Entry:
                        Connection = 0x55d8ee1faf60
                        Attribute = SQL_ATTR_LOGIN_TIMEOUT
                        Value = (nil)
                        StrLen = 0
[ODBC][351][1520903671.279490][SQLSetConnectAttr.c][671]
                Exit:[SQL_SUCCESS]
[ODBC][351][1520903671.279499][SQLDriverConnect.c][728]
                Entry:
                        Connection = 0x55d8ee1faf60
                        Window Hdl = (nil)
                        Str In = [Driver=DB2;Host=db2;UID=db2inst1;Port=50000;Database=test;PWD=*********][length = 71 (SQL_NTS)]
                        Str Out = 0x7ffe97fb9460
                        Str Out Max = 2048
                        Str Out Ptr = (nil)
                        Completion = 0
                UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2LE'

                DIAG [08001] [IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Communication API being used: "SOCKETS".  Location where the error was detected: "::1".  Communication function detecting the error: "connect".  Protocol specific error code(s): "99", "", "".  SQLSTATE=08001

[ODBC][351][1520903671.357135][SQLDriverConnect.c][1454]
                Exit:[SQL_ERROR]
[ODBC][351][1520903671.357164][SQLGetDiagRec.c][686]
                Entry:
                        Connection = 0x55d8ee1faf60
                        Rec Number = 1
                        SQLState = 0x7ffe97fbdc72
                        Native = 0x7ffe97fbdb84
                        Message Text = (nil)
                        Buffer Length = 0
                        Text Len Ptr = 0x7ffe97fbdb82
[ODBC][351][1520903671.357177][SQLGetDiagRec.c][723]
                Exit:[SQL_SUCCESS_WITH_INFO]
                        SQLState = 08001
                        Native = 0x7ffe97fbdb84 -> -30081
                        Message Text = [NULLPTR]
[ODBC][351][1520903671.357204][SQLGetDiagRec.c][686]
                Entry:
                        Connection = 0x55d8ee1faf60
                        Rec Number = 1
                        SQLState = 0x7ffe97fbdc72
                        Native = 0x7ffe97fbdb84
                        Message Text = 0x55d8edf1a9b0
                        Buffer Length = 337
                        Text Len Ptr = 0x7ffe97fbdb82
[ODBC][351][1520903671.357214][SQLGetDiagRec.c][723]
                Exit:[SQL_SUCCESS]
                        SQLState = 08001
                        Native = 0x7ffe97fbdb84 -> -30081
                        Message Text = [[unixODBC][IBM][CLI Driver] SQL30081N  A communication error has been detected. Communication protocol being used: "TCP/IP".  Co]
[ODBC][351][1520903671.357292][SQLFreeHandle.c][284]
                Entry:
                        Handle Type = 2
                        Input Handle = 0x55d8ee1faf60
[ODBC][351][1520903671.357302][SQLFreeHandle.c][333]
                Exit:[SQL_SUCCESS]
[ODBC][351][1520903671.357309][SQLFreeHandle.c][219]
                Entry:
                        Handle Type = 1
                        Input Handle = 0x55d8ede2fbe0
</pre>
</details>

**Comment by jimhester** [comment]
Are you sure this is not the issue with unixODBC, where versions prior to 2.3.1 do not support specifying the library location as the `DRIVER=` attribute? See the release notes at http://www.unixodbc.org/

**Comment by colearendt** [comment]
I'm not sure!  I haven't heard of that before.  I suspect that it is not the case, since it looks like I have a newer version of unixodbc installed.

```
rstudio@test-process:/wrk$ apt list | grep 'unixodbc'

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

kamailio-unixodbc-modules/stable 4.4.4-2 amd64
opensips-unixodbc-module/stable 2.2.2-3 amd64
unixodbc/stable,now 2.3.4-1 amd64 [installed]
unixodbc-bin/stable 2.3.0-4+b1 amd64
unixodbc-dev/stable,now 2.3.4-1 amd64 [installed]
```

**Comment by jimhester** [comment]
The solution to this turned out to be needing to use `Hostname` rather than `Host` with a connection string. https://www.ibm.com/support/knowledgecenter/en/SSEPGG_9.5.0/com.ibm.db2.luw.apdv.cli.doc/doc/r0008795.html
