### ISSUE TITLE
Batches of SQL statements and direct execution

### ISSUE THREAD

**Issue by khotilov** [r-dbi/odbc#163]
The use case is that I have various templated SQL scripts with multiple statements in each for doing some data loading, cleaning and transformation tasks, where the statements do not return back any data as results. I run such batch queries using `RODBC::sqlQuery(con, query)` with no problem, since this function calls `SQLExecDirect` under the hood. With the DBI interface, I guess, `dbSendStatement` or `dbExecute` would be appropriate functions for that purpose.

However, the only possible way to execute queries in the odbc package is via prepared statements (where it calls `SQLPrepare` and then `SQLExecute`). And the problem is that batch queries cannot be run as prepared statements (at least with Vertica):
```
Error in new_result(connection@ptr, statement) : 
  nanodbc/nanodbc.cpp:1344: 42601: ERROR 2446:  Cannot insert multiple commands into a prepared statement
```
In principle, in order to switch to odbc, I could try parsing my scripts into individual statements and executing those one-by-one. However, it seems wasteful to create and execute hundreds of prepared statement requests, especially when there's no real need for using prepared statements. Also, databases are sometimes set up to auto-adjust user priority when a user is sending too many rapid-fire requests.

Were there any plans to add the direct execution? The nanodbc does offer some methods for that. And I can contribute if there would be interest.

**Comment by jimhester** [comment]
There are no plans to add it currently, but I would definitely be open to a PR adding the functionality.

**Comment by krlmlr** [comment]
Similar problems occur in _RMariaDB_, some queries can only be executed directly and not as prepared statements. We're considering support for direct execution to _DBI_ when called as follows:

```r
dbSendStatement(..., params = list())
```

See https://github.com/r-dbi/DBI/issues/268#issuecomment-441718245 for more context.
