### ISSUE TITLE
dbListFields use of catalog parameter

### ISSUE THREAD

**Issue by meztez** [r-dbi/odbc#166]
### Issue Description and Expected Result
Is there a way to use the catalog parameter in dbListFields as with dbListTables to list the fields in a table in a different catalog than the one currently connected to?

dbListTables(con,catalog="CATALOG") works fine and list the tables in the catalog.
dbListFields(con,name="TABLE",catalog="CATALOG") returns character(0)

I would expect it to return the fields in CATALOG..TABLE. Table isn't empy, connecting directly to CATALOG and using dbListFields(con,"TABLE") works. I only have issues when using a different CATALOG than the one connected to.

I look into the source code but if anyone has an idea how to accomplish this, it would be appreciated.

Thanks

### Database
$dbms.name
[1] "NetezzaSQL"

$db.version
[1] "07.02.0001 Release 7.2.1.4-P2 [Build 50271]"

### Reproducible Example

**Comment by jimhester** [comment]
I recently made a change in the [devel version of odbc](https://github.com/r-dbi/odbc/commit/b6783cfd9a380b5dfa77274017d71daf9bb3626d) that exposes this, so 

```r
devtools::install_github("r-dbi/odbc")`
```

And you should be able to do this

**Comment by meztez** [comment]
You know you are the best right? Thanks a bunch
