### ISSUE TITLE
dbGetQuery returns 0 results when executing Stored Procedure

### ISSUE THREAD

**Issue by martindut** [r-dbi/odbc#173]
I'm building up a SQL string like 
sql <- "EXEC sp_name 'aaa', 'bbb'"
I then use 
`res <- DBI::dbGetQuery(con, sql)`
but this returns 0 obs. of 0 variables. The Stored Procedure actually fires because it does some other stuff that I can see happens, but it doesn't return results. If I run the sql statement directly on SQL Server, it returns the results as expected.

I'm using a Azure SQL Server database. This used to work when I was still using RSQLSERVER.
My con object:
`con <- DBI::dbConnect(odbc::odbc(),
                      Driver = "SQL Server",
                      Server = "xxxxxxx.database.windows.net",
                      Database = "abc",
                      UID = "xxxxxx",
                      PWD = "*********",
                      Port = 1433)`

**Comment by aryoda** [comment]
Are you using  `SET NOCOUNT ON` as the first line in your stored procedure?

**Comment by ruiyiz** [comment]
@aryoda has it right. I ran into a similar situation where the proc returns data fine in DataGrip, but returns an empty data frame when executed using dbGetQuery. Adding `SET NOCOUNT ON` as the first line of the stored proc solved the problem. Thanks!

**Comment by martindut** [comment]
Thanks @aryoda, that worked for me too!

**Comment by aryoda** [comment]
@martindut Great to hear that! Can you please close this issue (if you have the rights to do this).

Perhaps you can add a tag **"Microsoft SQL Server"** which is not obvious until I looked into the driver you are using for the ODBC connection.

**Comment by martindut** [comment]
Sorry, not sure how to add a label
