### ISSUE TITLE
Switch to change default Timezone behaviour

### ISSUE THREAD

**Issue by totalgit74** [r-dbi/odbc#177]
### Issue Description and Expected Result
Currently, even though the timezone parameter is set when using dbconnect time still come back from dB queries as UTC. Although the dates returned are technically correct it is less than useful for data to show in the view or console output as 2018-04-22 14:00 UTC when the real value should be 2018-04-23 AEST, which is the value returned by RODBC queries.
This is especially painful when looking at large data frames containing multiple date columns as in View() the timezone isn’t visible. Although I believe you can override this by setting datecolumn <- c(datecolumn) it is inefficient for large datasets (24+m rows), and the conversion is likely performed twice - once to UTC and once back to the desired timezone.

### Possible solution
A parameter on the dbconnect and/or the query functions in odbc to override the default “convert to UTC” behaviour to instead utilise the timezone that has been provided on the connection. This would default to the current behaviour but at least allow users to obtain RODBC equivalent behaviour where desired.

**Comment by krlmlr** [comment]
Upstream issue: https://github.com/r-dbi/DBI/issues/269.

**Comment by krlmlr** [comment]
A solution is outlined in #275 and implemented in #294.

**Comment by jimhester** [comment]
Closed by #294
