### ISSUE TITLE
Feature Request: Optional Argument in odbc::dbConnect to give the Option of returning Tibbles

### ISSUE THREAD

**Issue by jtelleria** [r-dbi/odbc#185]
Would it be possible to add in odbc::dbConnect() an Optional Argument that allows that dbGetQuery / dbReadTable / etc. return Tibbles instead of data.frames?

Example:
```
con <- odbc::dbConnect(dsn="MyDNS", class = "tibble"|"data.frame")
```
Thank you,

Juan

**Comment by jimhester** [comment]
See #3 for some discussion on why we currently return data.frame rather than a tibble. I doubt it will be changed unless the DBI specification changes in the future.

**Comment by jtelleria** [comment]
StringAsFactors.... But the change is happening in the Connection, not in the Downstream Functions.... Will think about it :)

Thank you.
