### ISSUE TITLE
oracle data types VARCHAR vs VARCHAR2

### ISSUE THREAD

**Issue by washcycle** [r-dbi/odbc#189]
I am suggesting that we change VARCHAR to VARCHAR2, I'd be willing to create the pull request, but I want to know what you think, or if there is a reason to use VARCHAR over the recommended VARCHAR2?

"VARCHAR datatype is synonymous with the VARCHAR2 datatype. To avoid possible changes in behavior, always use the VARCHAR2 datatype to store variable-length character strings."

https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT1822

**Comment by jimhester** [comment]
No, no reason, I just didn't know about this distinction.

Please create a PR to make the change! 

https://stackoverflow.com/a/1171200/2055486 has some more details on the reasoning (for my future reference).
