### ISSUE TITLE
uniqueidentifier field returning a list of raw vectors

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/odbc#193]
### Issue Description and Expected Result

In the table I mentioned in #171, one column named `FILEGUID` is of type `uniqueidentifier`. If such a field is selected in a query, the column will be a list of raw vectors, making it less convenient to work with in R, especially when I want to `fwrite` or `fst::write_fst`. 

`RSQLServer` handles such type by returning its hex-string representation, which I think is a better choice in this case.

```
$ FILEGUID       :List of 933838
  ..$ : raw  35 46 d8 b4 ...
  ..$ : raw  50 f2 38 10 ...
  ..$ : raw  89 8f 2f 65 ...
  ..$ : raw  e2 dc 78 ec ...
  ..$ : raw  40 c0 36 54 ...
  ..$ : raw  65 ea 66 66 ...
  ..$ : raw  0c 1e 96 c4 ...
  ..$ : raw  fc 27 1c 5d ...
  ..$ : raw  ea 8c b7 5b ...
  ..$ : raw  ef 8f 84 e3 ...
  ..$ : raw  30 b8 17 75 ...
  ..$ : raw  8a 1e f0 87 ...
  ..$ : raw  8a a7 4b d8 ...
  ..$ : raw  c4 7b 9a a5 ...
  ..$ : raw  1e 4a ab 8a ...
  ..$ : raw  d7 9b f0 ef ...
  ..$ : raw  60 2e 05 f6 ...
  ..$ : raw  ac 88 a2 10 ...
  ..$ : raw  ad 21 d7 67 ...
  ..$ : raw  5d 1d af 2d ...
```

**Comment by renkun-ken** [comment]
I'm testing the same commit https://github.com/renkun-ken/odbc/commit/fec21a23cdfd0c88c502358df704732d766dbed2 with the same database, same config, and the same query.

On Ubuntu 16.04 server (with `tdsodbc 0.91-6.1build1`), `uniqueidentifier` field returns a `blob` list of raw vectors.

On Ubuntu 18.04 server (with `tdsodbc 1.00.82-2`), `uniqueidentifier` field returns a character vector of hex-string representation as preferred.

I'm not sure what causes such a difference in return type.

**Comment by renkun-ken** [comment]
In the following code

https://github.com/r-dbi/odbc/blob/0062a2b1283ab3d4b10a1ac712db1817f44fd6e8/src/odbc_result.cpp#L612-L620

On Ubuntu 16.04 (`tdsodbc 0.91-6.1build1`), `uniqueidentifier` has type `-3` and falls in `default` case while on Ubuntu 18.04 (`tdsodbc 1.00.82-2`), it has type `-11` and falls in one of `SQL_BINARY`, `SQL_VARBINARY`, `SQL_LONGVARBINARY` case. 

I did some `git grep SQL_BINARY` and cannot find any definition of these `SQL_` type consts. I'm wondering where they are defined?

**Comment by jimhester** [comment]
They should be defined in `sql.h` header on your system.

**Comment by renkun-ken** [comment]
After inspecting `sqlext.h`, `-3` is `SQL_VARBINARY` and `-11` is `SQL_GUID` (which is only available `#if (ODBCVER >= 0x0350)`).

**Comment by jimhester** [comment]
This seems driver / system dependent, I am not sure anything needs to be done in the package, so I will close this issue.
