### ISSUE TITLE
nanodbc can't open the driver file

### ISSUE THREAD

**Issue by blmayer** [r-dbi/odbc#198]
### Issue Description and Expected Result

The command `dbConnect(odbc::odbc(), dsn = "mySQLdb")` returns the following error: 
```
Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libmysqlclient.a' : file not found 
```

### Database
MySQL

### Reproducible Example
I configured the file .odbcinst.ini like this:

```
[MySQL Driver]
Driver = /usr/local/lib/libmysqlclient.a
```
And the .odbc.ini to use that driver. I tried using other libraries, such as `libmyodbc8a.so` and `libmyodbc8w.so` but got the same result. I am sure that the file is present, because:

```
brians-Mac-mini$ ls /usr/local/lib/libm*
libmpc.3.dylib           libmpfr.6.dylib          libmyodbc8a.so           libmysqlclient.a         
libmpc.a                 libmpfr.a                libmyodbc8w.so           libmysqlclient.dylib     
libmpc.dylib             libmpfr.dylib            libmysqlclient.21.dylib  libmysqlservices.a      
```

The code I ran:

```r
library(odbc)

conn <- dbConnect(odbc::odbc(), dsn = "mySQLdb")
> Error: nanodbc/nanodbc.cpp:950: 01000: [unixODBC][Driver Manager]Can't open lib '/usr/local/lib/libmysqlclient.a' : file not found 
```

My machine is a Mac Mini , `Darwin Brians-Mac-mini-8.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64` and I use Brew. Is it something with my mysql installation?

Thanks.

**Comment by jimhester** [comment]
The driver you want for the odbc package is the ODBC/connector, e.g. `/usr/local/lib/libmyodbc5w.so`, not the C client library `/usr/local/lib/libmysqlclient.a`, changing your configuration to the following should fix the issue.

```ini
[MySQL Driver]
Driver = /usr/local/lib/libmyodbc5w.so
```
