### ISSUE TITLE
Use modulo power of 2 for interrupt checking

### ISSUE THREAD

**Issue by dirkschumacher** [r-dbi/odbc#204]
Really just a minor thing I noticed, but using a power of 2 instead of 10000 can be significantly faster AFAIK [1]. However this is only relevant for very large datasets.

https://github.com/r-dbi/odbc/blob/8cf2858472e849ad73b3485611242ac7dd0c056d/src/odbc_result.cpp#L689-L691

So instead of 10k, one could use 2^13 = 8192 or 2^14 = 16384. I am not entirely sure if the compiler always translates it to a bitwise AND `rows_fetched_ & (8192 - 1)`, but at least there is a chance :) Alternative is to write `if (rows_fetched_ & (8192 - 1) == 0) ...` directly, but this is also less readable.

1: https://en.wikipedia.org/wiki/Modulo_operation#Performance_issues

**Comment by jimhester** [comment]
Thanks, the compiler pretty much always does this optimization if it is available, see https://github.com/tidyverse/readr/pull/627 for some compiler explorer examples in readr.

**Comment by dirkschumacher** [comment]
I can send a PR if useful
