### ISSUE TITLE
Silent error sending NaN values via dbBind()

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/odbc#211]
### Issue Description and Expected Result

`NaN` values behave strangely when sent with `dbBind()`. Expecting them to be passed through or to treated like `NA` values, or to raise an error.

### Database

SQL Server 2017 on Ubuntu 16.04, accessed via FreeTDS from Ubuntu 18.04.

### Reproducible Example
``` r
library(DBI)

con <- dbConnect(
  odbc::odbc(),
  .connection_string = "Driver=/usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so;Server=...;Port=...;",
  uid = "...", pwd = "...", database = "..."
)

dbExecute(con, "SET ANSI_DEFAULTS ON")
#> [1] 0

dbWithTransaction(
  con,
  {
    dbExecute(con, "DROP TABLE IF EXISTS dbo.[test]")
    dbExecute(con, "CREATE TABLE dbo.[test] (a FLOAT)")
    res <- dbSendStatement(con, "INSERT INTO test (a) VALUES (?)")
    dbBind(res, list(c(1, 2.5, NA, 3)))
    dbClearResult(res)
    dbGetQuery(con, "SELECT * FROM dbo.[test]")
  }
)
#>     a
#> 1 1.0
#> 2 2.5
#> 3  NA
#> 4 3.0

dbWithTransaction(
  con,
  {
    dbExecute(con, "DROP TABLE IF EXISTS dbo.[test]")
    dbExecute(con, "CREATE TABLE dbo.[test] (a FLOAT)")
    res <- dbSendStatement(con, "INSERT INTO test (a) VALUES (?)")
    dbBind(res, list(c(4, 5.5, NaN, 6)))
    dbClearResult(res)
    dbGetQuery(con, "SELECT * FROM dbo.[test]")
  }
)
#> Error: <SQL> 'SELECT * FROM dbo.[test]'
#>   nanodbc/nanodbc.cpp:1587: 42S02: [FreeTDS][SQL Server]Invalid object name 'dbo.test'.

dbDisconnect(con)
```

> Created on 2018-08-22 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
Did you try this with a different driver, FreeTDS is known to behave differently than other drivers in many cases. You might try the Microsoft drivers for linux (https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017)

**Comment by krlmlr** [comment]
Not yet, but I'll keep this in mind.
