### ISSUE TITLE
Error message shows like  �H

### ISSUE THREAD

**Issue by shizidushu** [r-dbi/odbc#213]
### Issue Description and Expected Result
Issue Description: Error message shows like  �H

Expected Result: Show the error message. When connect to the database SSMS, it display the error message clearly in Chinese. I want to see the error message so I can fix the sql syntax error.

### Database
SQL Server 2016

### Reproducible Example

```r
library(DBI)
library(odbc)
dw <- config::get("datawarehouse")

con <- DBI::dbConnect(odbc::odbc(),
                      Driver = dw$driver,
                      Server = dw$server,
                      UID    = dw$uid,
                      PWD    = dw$pwd,
                      Port   = dw$port,
                      Database = dw$database
)
dbGetQuery(con, 
           '
           SELECT *
           FROM notexistedtable
           ')
devtools::session_info()
```

    > dbGetQuery(con, 
                 +            '
                 +            SELECT *
                 +            FROM notexistedtable
                 +            ')
    Error: <SQL> '
    SELECT *
    FROM notexistedtable
    '
    'notexistedtable' �H 587: 42S02: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]�a
    > devtools::session_info()
    Session info -----------------------------------------------------------------------------------------
      setting  value                       
    version  R version 3.5.1 (2018-07-02)
    system   x86_64, linux-gnu           
    ui       RStudio (1.1.456)           
    language (EN)                        
    collate  en_US.UTF-8                 
    tz       Etc/UTC                     
    date     2018-08-24                  
    
    Packages ---------------------------------------------------------------------------------------------
      package     * version    date       source                            
    assertthat    0.2.0      2017-04-11 CRAN (R 3.5.1)                    
    backports     1.1.2      2017-12-13 CRAN (R 3.5.1)                    
    base        * 3.5.1      2018-08-22 local                             
    bindr         0.1.1      2018-03-13 CRAN (R 3.5.1)                    
    bindrcpp    * 0.2.2      2018-03-29 CRAN (R 3.5.1)                    
    bit           1.1-14     2018-05-29 CRAN (R 3.5.1)                    
    bit64         0.9-7      2017-05-08 CRAN (R 3.5.1)                    
    blob          1.1.1      2018-03-25 CRAN (R 3.5.1)                    
    broom         0.5.0      2018-07-17 CRAN (R 3.5.1)                    
    cellranger    1.1.0      2016-07-27 CRAN (R 3.5.1)                    
    cli           1.0.0      2017-11-05 CRAN (R 3.5.1)                    
    colorspace    1.3-2      2016-12-14 CRAN (R 3.5.1)                    
    compiler      3.5.1      2018-08-22 local                             
    config        0.3        2018-03-27 CRAN (R 3.5.1)                    
    countrycode * 1.00.0     2018-02-11 cran (@1.00.0)                    
    crayon        1.3.4      2017-09-16 CRAN (R 3.5.1)                    
    datasets    * 3.5.1      2018-08-22 local                             
    DBI         * 1.0.0      2018-05-02 CRAN (R 3.5.1)                    
    dbplyr      * 1.2.2      2018-07-25 CRAN (R 3.5.1)                    
    devtools      1.13.6     2018-06-27 CRAN (R 3.5.1)                    
    digest        0.6.15     2018-01-28 CRAN (R 3.5.1)                    
    dplyr       * 0.7.6      2018-06-29 CRAN (R 3.5.1)                    
    forcats     * 0.3.0      2018-02-19 CRAN (R 3.5.1)                    
    ggplot2     * 3.0.0.9000 2018-08-22 Github (tidyverse/ggplot2@5a37ae7)
    glue          1.3.0      2018-07-17 CRAN (R 3.5.1)                    
    graphics    * 3.5.1      2018-08-22 local                             
    grDevices   * 3.5.1      2018-08-22 local                             
    grid          3.5.1      2018-08-22 local                             
    gtable        0.2.0      2016-02-26 CRAN (R 3.5.1)                    
    haven         1.1.2      2018-06-27 CRAN (R 3.5.1)                    
    hfun        * 0.0.0.9000 2018-08-22 Github (shizidushu/hfun@1174907)  
    hms           0.4.2      2018-03-10 CRAN (R 3.5.1)                    
    httr          1.3.1      2017-08-20 CRAN (R 3.5.1)                    
    jsonlite      1.5        2017-06-01 CRAN (R 3.5.1)                    
    knitr         1.20.15    2018-08-22 local                             
    lattice       0.20-35    2017-03-25 CRAN (R 3.5.1)                    
    lazyeval      0.2.1.9000 2018-08-22 Github (hadley/lazyeval@93c455c)  
    lubridate     1.7.4      2018-04-11 CRAN (R 3.5.1)                    
    magrittr      1.5        2014-11-22 CRAN (R 3.5.1)                    
    memoise       1.1.0      2017-04-21 CRAN (R 3.5.1)                    
    methods     * 3.5.1      2018-08-22 local                             
    modelr        0.1.2      2018-05-11 CRAN (R 3.5.1)                    
    munsell       0.5.0      2018-06-12 CRAN (R 3.5.1)                    
    nlme          3.1-137    2018-04-07 CRAN (R 3.5.1)                    
    odbc        * 1.1.6      2018-06-09 CRAN (R 3.5.1)                    
    pillar        1.3.0      2018-07-14 CRAN (R 3.5.1)                    
    pkgconfig     2.0.2      2018-08-16 CRAN (R 3.5.1)                    
    plyr          1.8.4      2016-06-08 CRAN (R 3.5.1)                    
    purrr       * 0.2.5      2018-05-29 CRAN (R 3.5.1)                    
    R6            2.2.2      2017-06-17 CRAN (R 3.5.1)                    
    Rcpp          0.12.18    2018-07-23 CRAN (R 3.5.1)                    
    readr       * 1.1.1      2017-05-16 CRAN (R 3.5.1)                    
    readxl        1.1.0      2018-04-20 CRAN (R 3.5.1)                    
    redux         1.1.0      2018-08-22 Github (richfitz/redux@f84a22f)   
    rlang         0.2.2.9000 2018-08-22 Github (r-lib/rlang@2cf70c8)      
    rsconnect     0.8.8      2018-03-09 CRAN (R 3.5.1)                    
    rstudioapi    0.7        2017-09-07 CRAN (R 3.5.1)                    
    rvest         0.3.2      2016-06-17 CRAN (R 3.5.1)                    
    scales        1.0.0      2018-08-09 CRAN (R 3.5.1)                    
    stats       * 3.5.1      2018-08-22 local                             
    stringi       1.2.4      2018-07-20 CRAN (R 3.5.1)                    
    stringr     * 1.3.1      2018-05-10 CRAN (R 3.5.1)                    
    tibble      * 1.4.2      2018-01-22 CRAN (R 3.5.1)                    
    tidyr       * 0.8.1      2018-05-18 CRAN (R 3.5.1)                    
    tidyselect    0.2.4      2018-02-26 CRAN (R 3.5.1)                    
    tidyverse   * 1.2.1      2017-11-14 CRAN (R 3.5.1)                    
    tools         3.5.1      2018-08-22 local                             
    utils       * 3.5.1      2018-08-22 local                             
    withr         2.1.2      2018-03-15 CRAN (R 3.5.1)                    
    writexl       1.0        2018-05-10 CRAN (R 3.5.1)                    
    xfun          0.3        2018-07-06 CRAN (R 3.5.1)                    
    xml2          1.2.0      2018-01-24 CRAN (R 3.5.1)                    
    yaml          2.2.0      2018-07-25 CRAN (R 3.5.1)

Edit:
After add the `Language=English` connection string, it shows error message in English
```
library(DBI)
library(odbc)
dw <- config::get("datawarehouse")

con <- DBI::dbConnect(odbc::odbc(),
                      Driver = dw$driver,
                      Server = dw$server,
                      UID    = dw$uid,
                      PWD    = dw$pwd,
                      Port   = dw$port,
                      Database = dw$database,
                      .connection_string = "Language=English;AutoTranslate=Yes;"
)
dbGetQuery(con, 
           '
           SELECT *
           FROM notexistedtable
           ')
```

    Error: <SQL> '
               SELECT *
               FROM notexistedtable
               '
      nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'notexistedtable'. 

It seems the problem is related to the error message language. When the error message language is 简体中文, ie., Chinese, it doesn't display well.

**Comment by jimhester** [comment]
I think this is a driver configuration issue rather than something that would require changes in the odbc package, so I will close this issue.

**Comment by shrektan** [comment]
Just add my 2 cents: Looks like the MSSQLServer is on a Windows machine which may throw an error message encoded in GB2312. 

However, your computer is on Linux which can only display UTF-8 encoded message well. So one possible solution is to let your driver translate the error message to UTF-8 so that odbc can display it correctly. I suggest you to google to see if there exists a configuration of your driver (FreeTDS?), which relates to the setting of the message encoding from the Server.
