### ISSUE TITLE
RStudio Connections Pane ODBC Error

### ISSUE THREAD

**Issue by lee170** [r-dbi/odbc#218]
### Issue Description and Expected Result
After successfully connecting to MariaDB 10.3.9 a list of table names is displayed in the RStudio connections pane.  Clicking on a list expansion button next to one of the tables throws an error, but subsequently closing and reopening displays a list of column names and their types.  Although the error is thrown in nanodbc.cpp, it may be due to the interaction between RStudio and odbc.  I am posting it here in case anyone can help identify the cause.

### Database
MariaDB 10.3.9

### Reproducible Example
Note, the call to dbConnect succeeds.  The error occurs after a list of tables is displayed in the RStudio connections pane.
```r
library(DBI)
con <- dbConnect(odbc::odbc(), "MySQL", timeout = 10)
Error in connection_sql_columns(connection@ptr, table_name = validateObjectName(table,  : 
  nanodbc/nanodbc.cpp:2525: 22003: [ma-3.0.2][10.3.9-MariaDB]Numeric value out of range 
```

<details>
<summary>R version 3.5.1 (2018-07-02)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_1.0.0</summary>
</details>

**Comment by jimhester** [comment]
It is hard to say for sure what is happening without being able to diagnose what particular query was failing, it is possible that 71852b8e may help address this.

If you still have this or similar problems please open a new issue with a reproducible example if possible.
