### ISSUE TITLE
dbWriteTable seems to mix up the order of inserted rows when appending

### ISSUE THREAD

**Issue by satvenkat** [r-dbi/odbc#242]
## Issue: dbWriteTable mixes up the order of inserted rows when appending

The issue that I am having when trying to get data out of a data frame into the database is that it is inserting rows out of order.   However, when i export the data frame to an excel file, or if I were to over write instead of appending into the database, I have no issues in that the rows are in the same order as it is in the dataframe.  Has anyone come across this before, and is this some issue on my end within my DbWriteTable query.

### Database

SQL Server 2012

```
### Code Snippet 
con <- dbConnect(odbc::odbc(), dsn) #where dsn is my odbc dsn name
data <- dbWriteTable(con, "FASOperationsFinancials", final, overwrite=FALSE, append=TRUE)
```

Am i missing anything in the dbWriteTable command??  Thank you.
Satish.

**Comment by jimhester** [comment]
I agree with @krlmlr, you need to use `ORDER BY` to specify the order you want the records to be returned. If you want to order them by the insertion order you will need to modify your table schema to include an [AUTO INCREMENT](https://www.w3schools.com/sql/sql_autoincrement.asp) field that you can order by.
