### ISSUE TITLE
MySQL attempts to connect to localhost rather than remote server

### ISSUE THREAD

**Issue by versipellis** [r-dbi/odbc#244]
What I tried:
```
con <- DBI::dbConnect(odbc::odbc(),
                 driver="MySQL",
                 host="somehostname.com",
                 database="somedatabasename",
                 uid="uid",
                 pwd="pwd")
```

Result:
```
Error: nanodbc/nanodbc.cpp:950: 08S01: [unixODBC][MySQL][ODBC 8.0(a) Driver]Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

The traceback shows `.local(drv,...)`, so it looks like its trying to connect to localhost rather than the connection args I'm passing to it.

**Comment by jimhester** [comment]
`.local()` in the traceback is just due to the internals of S4 methods, the problem is actually that you are using 'host', when MySQL is expecting 'Server'.

See https://www.connectionstrings.com/mysql/
