### ISSUE TITLE
Large precision numbers not truncated

### ISSUE THREAD

**Issue by nwstephens** [r-dbi/odbc#245]
When I load large precision numbers into the database, the number gets stored improperly. I would expect the large precision numbers to get truncated instead of distorted. For example, `1.1111111111111` might get stored as `1.1111111111123`. See below for a reproducible example on PostgreSQL.

```
library(DBI)
library(odbc)
dd <- data.frame(pi = pi)

con <- dbConnect(odbc::odbc(), "PostgreSQL (DSN)")
dbWriteTable(con, "precision", dd, overwrite = TRUE)
x <- dbReadTable(con, "precision")
sprintf("%.55f", x$pi)
sprintf("%.55f", pi)

#odbc: 3.1415926535897900073734945181058719754219055175781250000
#pi:   3.1415926535897931159979634685441851615905761718750000000
```

Note, this same issue occurs in the `RPostgres` package.

**Comment by jimhester** [comment]
This is just [R-FAQ 7.31](https://cran.r-project.org/doc/FAQ/R-FAQ.html#Why-doesn_0027t-R-think-these-numbers-are-equal_003f) I think, the difference between those numbers is very close to the machine epsilon for doubles, and IEEE 754 numbers cannot store anywhere close to 55 base 10 digits.

**Comment by ronblum** [comment]
Using the example from R FAQ, with a slight modification, to show that this is expected behavior:

```
> a <- sqrt(2) 
> b <- a * a 
> print(2, digits = 18) 
[1] 2 
> print(b, digits = 18) 
[1] 2.00000000000000044 
> b == 2 
[1] FALSE 
> identical(a * a, 2) 
[1] FALSE 
> all_equal(a * a, 2) 
[1] "Rows in x but not y: 1. Rows in y but not x: 1. " 
> all.equal(a * a, 2) 
[1] TRUE
```

**Comment by nwstephens** [comment]
Thanks for the education, @jimhester. I was not aware that `0.3+0.6 != 0.9` in R. According the websites:
```
The only numbers that can be represented exactly in R’s numeric type are integers and fractions whose denominator is a power of 2. All other numbers are internally rounded to (typically) 53 binary digits accuracy. As a result, two floating point numbers will not reliably be equal unless they have been computed by the same algorithm, and not always even then. For example
```
So numbers like `pi` can have varying degrees in and out of R memory.

**Comment by jimhester** [comment]
Should also note this is not something specific to R, this is just due to limitations of how floating point numbers are represented in memory in computers, so it will occur in basically any language using IEEE 754 floating point representation.
