### ISSUE TITLE
Logon failed. The logon is from an untrusted domain

### ISSUE THREAD

**Issue by ralsouza** [r-dbi/odbc#251]
### Issue Description and Expected Result
I am trying to connect on a SQL Server base from my macbook `macOS Mojave Version 10.14.2`, but it seems that there is some   authentication problem with the server.

### Database
   

> Microsoft SQL Server 2014 (SP2) (KB3171021) - 12.0.5000.0 (X64) 
	Jun 17 2016 19:14:09 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)

### Reproducible Example
```r
install.packages("odbc")
library(odbc)
con <- dbConnect(odbc::odbc(),
                 driver = "libtdsodbc.so",
                 database = "FOO",
                 uid = "MYSERVER\\administrator",
                 pwd = "******",
                 Server = "192.168.5.5",
                 port = 1433)
```
### Then it returns the error message

> Error: nanodbc/nanodbc.cpp:950: 42000: [FreeTDS][SQL Server]
Logon failed. The logon is from an untrusted domain and can not be used with Windows Authentication.

**Comment by jimhester** [comment]
I think this depends on your TDS driver configuration settings, so there is not something we need to change in odbc. [freeTDS#206](https://github.com/FreeTDS/freetds/issues/206) seems to be a user with a similar situation. Hopefully from that and the freeTDS documentation you can get this working.
