### ISSUE TITLE
MySQL not returning tables under information schema

### ISSUE THREAD

**Issue by nwstephens** [r-dbi/odbc#253]
I am using RStudio Desktop Pro to query MySQL, and the temporary tables do not show up under the information schema in the connections pane as I would expect. However, tables are listed under the information schema if I use `dbSendQuery`. I would expect `odbcListObjects` to give me similar results that I get from `dbSendQuery`.

```
library(DBI)
con <- dbConnect(
  odbc::odbc(), 
  Driver="mysql", 
  Server = "*****", 
  Port = "3306", 
  UID = "****",
  PWD = "*****",
  Database = "finance")
odbc::odbcListObjects(con, "INFORMATION_SCHEMA") # no results (incorrect)
dbGetQuery(con, "SHOW TABLES FROM INFORMATION_SCHEMA;") # lists tables (correct)
```

**Comment by nwstephens** [comment]
Note that `odbc::odbcListObjects` will work for certain schema and not others. For example, it will work for my user generated schema but not the system schema as seen here:

![image](https://user-images.githubusercontent.com/7519295/55752189-65307b80-5a15-11e9-9034-09a2b426f6b6.png)

**Comment by jimhester** [comment]
I can reproduce this, I think the most likely cause is related to this (from https://dev.mysql.com/doc/refman/8.0/en/information-schema-introduction.html)

> The INFORMATION_SCHEMA database contains several read-only tables. They are actually views, not base tables, so there are no files associated with them, and you cannot set triggers on them. Also, there is no database directory with that name.

Trying to set `type = "VIEW"` did not help unfortunately, I am not sure what else we could do, I don't know how to access the information, or if it is even possible through the SQLTable interface.

**Comment by nwstephens** [comment]
```The INFORMATION_SCHEMA database contains several read-only tables. They are actually views, not base tables, so there are no files associated with them, and you cannot set triggers on them. Also, there is no database directory with that name.```

The information schema is not a high priority since it mainly contains blob storage not typically used in data science workflows. For now, if users want to investigate the information schema, they can use a db admin tool or `dbGetQuery`.
