### ISSUE TITLE
Login timeout expired on Mac accessing SQL Express; Windows config works OK

### ISSUE THREAD

**Issue by md0u80c9** [r-dbi/odbc#254]
### Issue Description and Expected Result

I've been trying to access a remote SQL Express configuration. I've set up the server myself on an old PC for testing, connected within a local wired LAN, and have followed MS's troubleshoot guide. The goal will be to use a remote SQL Server configuration with a full dataset (1,000,000 records) at a later stage.

My primary development machine is an iMac which has Boot Camp installed.

I have confirmed the SQL Server works correctly on, and from Windows I have confirmed it works OK remotely.

I have then successfully accessed the database from RStudio on Windows.

On the mac I installed the ODBC driver from the following location following the guidance from this MS document:

https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017

(The pertinent text copied below):
```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew update
brew install --no-sandbox msodbcsql17 mssql-tools
```

I've also confirmed that unixodbc is definitely installed (v2.3.7):
```
andrewhill$ brew install unixodbc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
kubeprod                                 sn0int
==> Updated Formulae
apibuilder-cli      dosbox-x            swiftformat         wine
composer            libgda              weechat

Warning: unixodbc 2.3.7 is already installed and up-to-date
To reinstall 2.3.7, run `brew reinstall unixodbc`
```

From looking at odbcListDrivers() I think the drivers are installed correctly. You can see I have also tried the ODBC Driver 13 with the same results.

On the Mac I can successfully Ping the test pc. I've disabled the firewall on the Mac until I'm confident it's all working as expected to exclude any firewall issues. However, regardless of what I do I'm seeing:

Error: nanodbc/nanodbc.cpp:950: HYT00: [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired

I've tried with ODBC Driver 13 installed - same result. I've tried adding or omitting the port number - no dice.

### Database

SQL Express 2017 installed on a Windows 10 PC. Firewall disabled.

### Reproducible Example

```r
library(odbc)
library(DBI)

> odbcListDrivers()
                           name   attribute                                   value
1 ODBC Driver 13 for SQL Server Description Microsoft ODBC Driver 13 for SQL Server
2 ODBC Driver 13 for SQL Server      Driver    /usr/local/lib/libmsodbcsql.13.dylib
3 ODBC Driver 13 for SQL Server  UsageCount                                       1
4 ODBC Driver 17 for SQL Server Description Microsoft ODBC Driver 17 for SQL Server
5 ODBC Driver 17 for SQL Server      Driver    /usr/local/lib/libmsodbcsql.17.dylib
6 ODBC Driver 17 for SQL Server  UsageCount                                       1

con <- dbConnect(odbc::odbc(), Driver = "ODBC Driver 17 for SQL Server", timeout = 10, Server = "Test-PC//SQLEXPRESS", Database = "odbc_test", UID="ssnap_user", PWD = "ssnap")
```
-->

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
> devtools::session_info()
─ Session info ────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.2 (2018-12-20)
 os       macOS Mojave 10.14.4        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_GB.UTF-8                 
 ctype    en_GB.UTF-8                 
 tz       Europe/London               
 date     2019-01-30                  

─ Packages ────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source                        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.0)                
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.1)                
 bit           1.1-14  2018-05-29 [1] CRAN (R 3.5.0)                
 bit64         0.9-7   2017-05-08 [1] CRAN (R 3.5.0)                
 blob          1.1.1   2018-03-25 [1] CRAN (R 3.5.0)                
 callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.0)                
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)                
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.0)                
 DBI         * 1.0.0   2018-05-02 [1] CRAN (R 3.5.0)                
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.0)                
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)                
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.0)                
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)                
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.0)                
 hms           0.4.2   2018-04-30 [1] Github (tidyverse/hms@c0cfc01)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.0)                
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.0)                
 odbc        * 1.1.6   2018-06-09 [1] CRAN (R 3.5.0)                
 openxlsx    * 4.1.0   2018-05-26 [1] CRAN (R 3.5.0)                
 packrat       0.5.0   2018-11-14 [1] CRAN (R 3.5.1)                
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.0)                
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.1)                
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.0)                
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.0)                
 processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.1)                
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.0)                
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.5.0)                
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.1)                
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.0)                
 rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)                
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.0)                
 rsconnect     0.8.13  2019-01-10 [1] CRAN (R 3.5.2)                
 rstudioapi    0.9.0   2019-01-09 [1] CRAN (R 3.5.2)                
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)                
 testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.0)                
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)                
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.0)                
 zip           1.0.0   2017-04-25 [1] CRAN (R 3.5.0)                

[1] /Library/Frameworks/R.framework/Versions/3.5/Resources/library
> 
```
</details>

Any thoughts or advice appreciated:

- Are there ways to more directly debug what is going wrong?

- The timeout error isn't really helping diagnose any underlying connection problem. Could the failure error be perhaps more descriptive or give pointers to what the underlying problem may be?

**Comment by r2evans** [comment]
Thoughts (I'm not the maintainers): instead of `Server = "Test-PC//SQLEXPRESS"`, have you tried `Server = "Test-PC"` or just `Server = "ipaddress"`? Additionally, I've always used lower-case argument names, so my calls look like:

```r
con <- DBI::dbConnect(odbc::odbc(), driver = "ODBC Driver 17 for SQL Server",
    database = "mydb", timeout = 1, server = "myserver", uid = "myuser", pwd = "mypass")
```

**Comment by nadas-team1** [comment]
I was having the EXACT same issue and just got it to work. Add a comma and the port number after your server name:
`"myserver,port"`

**Comment by md0u80c9** [comment]
Thanks for this - I hadn’t tried that. I will test this evening if it works.

**Comment by md0u80c9** [comment]
Wow! OK - that has worked. If any of the maintainers are listening, is there a reason why this is needed on the Mac but not on the PC?

**Comment by r2evans** [comment]
You're connecting from a Microsoft competitor to a Microsoft product ... perhaps just school-yard bullying or resentment? ;-)

**Comment by jimhester** [comment]
Looks like this was sorted, glad you figured it out! The odbc package isn't doing anything different here, so maybe it is just a difference in the default ports for the driver manager or the driver on the two operating systems.

**Comment by Clee681** [comment]
Wow. Just hit this issue on macOS Catalina. Adding the port number fixed it! Thanks @nadas-team1 for the tip and @md0u80c9 for reporting this!
