### ISSUE TITLE
I can dbSendQuery/dbGetQuery only once per R Session 

### ISSUE THREAD

**Issue by ChristianAlvaradoAP** [r-dbi/odbc#267]
### Issue Description and Expected Result

I have to read 5 different tables from my server so I created a script that send querys one after another and then proccess this tables. 

My problem is when I run the script, the first query works fine but the next ones always return error "Error in new_result(connection@ptr, statement) : std::bad_alloc". It doesn't matter which query is the first, also if I try running the first query a second time it shows the same error.

When I restart R Session I can run any another query again and then I get the same error
Edit: My computer is an i7 of 7th generation with 16GB of RAM

### Output Example

 con <- dbConnect(odbc(),
                  Driver = "SQL Server",
                  Server = "xxxx,
                  Database = "xxx",
                 UID = "xxx",
                  PWD = "xxx",
                  Port = xxxx)
> crmlectura<-dbSendQuery(con,"SELECT * FROM vwCrmLeads WHERE UniversidadId = '5'")
> crmlectura <- dbFetch(crmlectura)
> crmlectura2<-dbSendQuery(con,"SELECT * FROM vwCrmLeads WHERE UniversidadId = '5'")
Error in new_result(connection@ptr, statement) : std::bad_alloc
In addition: Warning message:
In new_result(connection@ptr, statement) : Cancelling previous query
> crmlectura2 <- dbFetch(crmlectura)
Error in result_fetch(res@ptr, n, ...) : 
nanodbc/nanodbc.cpp:2525: HY010: [Microsoft][ODBC Driver Manager] Function sequence error 

Please note that is the same query in different variables. The first one just worked fine, but the second one failed

### My Script

```r
library(odbc)
library(DBI)
library(tidyverse)
con <- dbConnect(odbc(),
                 Driver = "SQL Server",
                 Server = "xxxx",
                 Database = "xxxx",
                 UID = "xxxx",
                 PWD = "xxx",
                 Port = xxxx)


crmlectura<-dbSendQuery(con,"SELECT * FROM vwCrmLeads WHERE UniversidadId = '5'")
salectura<-dbSendQuery(con,"SELECT * FROM vwInscriptos WHERE UniversidadId = '5'")
pagoslectura<- dbGetQuery(con,"SELECT * FROM vwReportePagosPorCiclo WHERE UniversidadId = '5'")
pagoslectura<-dbSendQuery(con,"SELECT * FROM vwReportePagosPorCiclo WHERE UniversidadId = '5'")
enrolllectura<-dbGetQuery(con,"SELECT * FROM vwEnrollments WHERE UniversidadId = '5'")
enrolllectura<-dbSendQuery(con,"SELECT * FROM vwEnrollments WHERE UniversidadId = '5'")

```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> Session info -----------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Mexico_City         
 date     2019-03-20                  

- Packages ---------------------------------------------------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.4.3)
 backports     1.1.3   2018-12-14 [1] CRAN (R 3.4.4)
 bit           1.1-14  2018-05-29 [1] CRAN (R 3.4.4)
 bit64         0.9-7   2017-05-08 [1] CRAN (R 3.4.4)
 blob          1.1.1   2018-03-25 [1] CRAN (R 3.4.4)
 callr         3.1.1   2018-12-21 [1] CRAN (R 3.4.4)
 cli           1.0.1   2018-09-25 [1] CRAN (R 3.4.4)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.4.3)
 DBI           1.0.0   2018-05-02 [1] CRAN (R 3.4.4)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.4.4)
 devtools      2.0.1   2018-10-26 [1] CRAN (R 3.4.4)
 digest        0.6.18  2018-10-10 [1] CRAN (R 3.4.4)
 fs            1.2.6   2018-08-23 [1] CRAN (R 3.4.4)
 glue          1.3.0   2018-07-17 [1] CRAN (R 3.4.4)
 hms           0.4.2   2018-03-10 [1] CRAN (R 3.4.4)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.4.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.4.4)
 odbc        * 1.1.6   2018-06-09 [1] CRAN (R 3.4.4)
 pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.4.4)
 pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.4.4)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.4.4)
 prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.4.4)
 processx      3.2.1   2018-12-05 [1] CRAN (R 3.4.4)
 ps            1.3.0   2018-12-21 [1] CRAN (R 3.4.4)
 R6            2.3.0   2018-10-04 [1] CRAN (R 3.4.4)
 Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.4.4)
 remotes       2.0.2   2018-10-30 [1] CRAN (R 3.4.4)
 rlang         0.3.1   2019-01-08 [1] CRAN (R 3.4.4)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.4.3)
 rstudioapi    0.9.0   2019-01-09 [1] CRAN (R 3.4.4)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.4.4)
 testthat      2.0.1   2018-10-13 [1] CRAN (R 3.4.4)
 usethis       1.4.0   2018-08-14 [1] CRAN (R 3.4.4)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.4.4)
 yaml          2.2.0   2018-07-25 [1] CRAN (R 3.4.4)

[1] C:/Users/Usuario/Documents/R/win-library/3.4
[2] C:/Program Files/R/R-3.4.3/library
```
</details>

**Comment by shrektan** [comment]
I think you should always use `dbGetQuery()` here. If you use `dbSendQuery()`, you need to use `dbClearResult()` to free the result later.

**Comment by jimhester** [comment]
Yeah I think the most relevant part of the error is `Function sequence error`, which indicates you are sending commands to the driver in an order it does not expect, you vary rarely ever need to use `dbSendQuery()` manually.

**Comment by kkwoo** [comment]
Hi @jimhester and @shrektan ,

    I came across this issue using dbSendQuery(). When I switched to dbGetQuery() all was better. Just want to let you know beginners like me are using dbSendQuery() because that's what's in the example on the intro page at https://db.rstudio.com/dbi/ even though dbGetQuery() is described in https://db.rstudio.com/odbc/

    Who'd be the right people to ask about updating https://db.rstudio.com/dbi/?

Kind Regards,

Kevin

**Comment by jedteres** [comment]
One thing I wanted to mention-- this happens with dbSendStatement as well as dbSendQuery. If you use dbSendStatement to create a table, for example, you might want to assign an object so you can later use dbClearResult. 

like this
```
dbSendStatement(con, "create table dbo.test_table (col1 varchar(20), col2 numeric)") -> tt
dbClearResult(tt)

```
