### ISSUE TITLE
[FR] be able to control the returned timezone

### ISSUE THREAD

**Issue by shrektan** [r-dbi/odbc#275]
Hi, first of all, my timezone and my database server's timezone are all Asia/Shanghai (UTC+8).

It's great that we can set the server's timezone info in the odbc connection, a.k.a., `odbc::dbConnect(...,, timezone = 'Asia/Shanghai')`. 

It's also a necessary step to ensure the value uploaded to the server is the same as local. Otherwise, the time will be converted to UTC first before getting uploaded to the server, ending up with a different time value in the server. Moreover, the timezone info get from `DBI::dbGetQuery()` would be UTC which is incorrect either.

Howerver, it causes inconvenient. **The results returned from `DBI::dbGetQuery()` are all converted to UTC timezone and it confuses the users a lot.**

For example, let's say there's a time value `2019-01-01 01:00:00` in the server. The server's timezone is `Asia/Shanghai`. What we get from `DBI::dbGetQuery()` is `2018-12-31 17:00:00 UTC`.

Yes, I know the value it's correct but it's much better if we can simply have the default `Asia/Shanghai` timezone value, a.k.a., `2019-01-01 01:00:00`, by setting somewhere before in the `odbc::dbConnect()`.

**So my proposal is, can we add a new param `timezone_out` in `odbc::dbConnect()` so that we can control the timezone returned from `DBI::dbGetQuery()`?**

Many thanks!

**Comment by dernst** [comment]
`TIMESTAMP`s and `POSIXt` are UTC internally anyway. The confusion stems from the fact that `odbc` sets the `tzone` attribute to UTC. Therefore the time is displayed as UTC. If it were left empty it would display in the local timezone by default.

**Comment by shrektan** [comment]
@dernst This assumes your local timezone is the same as the server but it's not true in some cases. So I think the current param timezone is necessary but having the ability to set the timezone attributes of the returned data other than UTC is often convinient and causes less confusing in the usual cases (server and local uses the same timezone).
