### ISSUE TITLE
dbExecute causes R to become unresponsive on DB2 connections if autocommit=0

### ISSUE THREAD

**Issue by s-fleck** [r-dbi/odbc#277]
### Issue Description and Expected Result

Using `dbExecute()` (and possibly other functions) on a DB2 connection that was configured with `autocommit = 0` do not work. If you call `dbExecute()`, close the connection and reconnect to the database, the next SQL Statement will cause R to become nonresponsive. 

Everything works just fine with `dbBegin() .... dbCommit()`. I am not sure what the expected behaviour is, but I assume `dbExecute()` is supposed to take care of such things? There also seems no way to manually commit when you use `dbExecute()`. It's hard for me to give more details, since I am not the person responsible for configuring our DB2 servers.

### Example
Reproducible, but requires a DB2 server configured in the way described above

```r
library(odbc)
library(DBI)

# everything below works
con <- # establish db2 connection
DBI::dbExecute(con, "create table TMP.TEST (tcol char(3))")
print(DBI::dbGetQuery(con, "select * from TMP.TEST"))
DBI::dbDisconnect(con)


# This causes R to become nonresponsive 
con <-  # establish db2 connection again
DBI::dbGetQuery(con, "select * from TMP.TEST")
```

**Comment by jimhester** [comment]
`dbExecute()` does not do any committing itself, you still need to do explicit `dbCommit()` calls when you use it.
