### ISSUE TITLE
Feature request: Return data.table from dbGetQuery()

### ISSUE THREAD

**Issue by crossxwill** [r-dbi/odbc#290]
This is a new feature request.

`dbGetQuery()` returns a data frame. The request is to add an option to return a data.table.

I could convert the data frame into a data.table, but this conversion is expensive for large data frames. I want to avoid conversion by having `dbGetQuery()` return a data.table.

```r
library(data.table)
library(dplyr)
library(microbenchmark)

mtcars_small <- mtcars
mtcars_large <- sample_n(mtcars, size=1e6, replace=TRUE)

microbenchmark(as.data.table(mtcars_small),
               as.data.table(mtcars_large),
               times=100)
```

**Comment by shrektan** [comment]
Why not use `data.table::setDT()`?

**Comment by jimhester** [comment]
Yes, as @shrektan mentions using `setDT()` would prevent the explicit copy that happens in `as.data.table()`, so should have no major performance implications. I think that is sufficient for this purpose.
