### ISSUE TITLE
Show first and last 4000 characters of error message if too long

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/odbc#292]
Error messages can't be arbitrarily long in R:

``` r
tryCatch(
  stop(paste(sample(letters, 100000, replace = TRUE))),
  error = function(e) nchar(conditionMessage(e))
)
#> [1] 8190
```

<sup>Created on 2019-08-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

dbplyr can generate very long SQL queries (especially when accessing very wide tables). Some drivers (e.g. SQL Server) include the SQL in the error message, and the cause of the error is stripped and never shown for the user.

Suggesting to split such very long messages halfway and include the first and last 4000 or so characters.

**Comment by krlmlr** [comment]
For now, `options(error = rlang::entrace)` makes the entire message available for inspection after the fact.

**Comment by jimhester** [comment]
I think capturing the error message as you suggest is a better method of handling this problem then emitting a mangled error message.

**Comment by krlmlr** [comment]
Do we have rlang as a dependency?
