### ISSUE TITLE
dbWriteTable() and dbListTables() - missing characters?

### ISSUE THREAD

**Issue by cfisher5** [r-dbi/odbc#296]
### Issue Description and Expected Result
I am experiencing a weird problem where I try appending to an existing table and I get the response `There is already an object named 'test_table' in the database`.
After doing some digging, I think the problem is in `dbListTables()` and `dbExistsTable()`.

### The code
```
## i built a connection wrapper that works; since querying definitely works...
con <- connect_db()

## everything working fine...
data <- data.frame(a = c(1,2,3), b = c("a", "b", "c"), stringsAsFactors = F)
dbWriteTable(con, "test_table", data, row.names = F)

## this append doesn't work - 
dbWriteTable(con, "test_table", data, append=T, row.names = F)

## Error Message:
Error: <SQL> 'CREATE TABLE "test_table" (
  "a" FLOAT,
  "b" varchar(255)
)
'
  nanodbc/nanodbc.cpp:1587: 42S01: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]There is already an object named 'test_table' in the database.

```
Despite the append=T, dbWriteTable is trying to re-create the table. Why? I think because:
`dbExistsTable(con, "test_table")` returns `FALSE`

When I call `dbListTables(con)` I get a really strange response: All the tables are listed with every other character missing. **So `test_table` looks like `ts_al`.**

If we check `dbExistsTable(con, "ts_al")` the return is `TRUE`

I am truly at a loss here, hoping someone has some ideas...
I am using ODBC Driver 17 for SQL Server as my driver, and like I said, the connection works. 
Perhaps it is some sort of character encoding issue? I really have no idea...

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] odbc_1.1.6        DBI_1.0.0.9001    stringr_1.4.0     wolvesutils_0.1.0 dplyr_0.8.3      

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.2       rstudioapi_0.10  magrittr_1.5     hms_0.5.1        tidyselect_0.2.5 bit_1.1-14       R6_2.4.0         rlang_0.4.0     
 [9] blob_1.2.0       tools_3.6.1      yaml_2.2.0       bit64_0.9-7      assertthat_0.2.1 tibble_2.1.3     crayon_1.3.4     purrr_0.3.2     
[17] vctrs_0.2.0      zeallot_0.1.0    glue_1.3.1       stringi_1.4.3    compiler_3.6.1   pillar_1.4.2     backports_1.1.4  pkgconfig_2.0.2 
```
</details>

**Comment by shrektan** [comment]
May relate to #285

**Comment by shrektan** [comment]
It’s not case sensitive issue but my patch uses a direct approach to check if the table exists or not, instead of using an indirect approach (using dblisttable). 

Thought it should help...

**Comment by duncanrellis** [comment]
Maybe related to my issue?   I'm also have issues with every other character being dropped.

https://github.com/r-dbi/odbc/issues/303

**Comment by shrektan** [comment]
Just to note that the issue of dropping letters on R 3.6 + macOS is related to #283 . Building the odbc package from the source should solve this (a.k.a, `install.packages('odbc', type = 'source')`).

**Comment by jimhester** [comment]
I think this should all be fixed with the current codebase. As mentioned recompiling the CRAN binary also may help until the next CRAN release.
