### ISSUE TITLE
Setting pre-connect connection attributes for Azure SQL Server connection

### ISSUE THREAD

**Issue by kjaanson** [r-dbi/odbc#299]
### Connecting to Azure SQL database using access token via pre-connect connection attributes

Is it possible to set pre-connect attributes on a connection using r odbc? I want to use Active Directory access token to connect to Azure SQL Data Warehouse. Azure docs specifiy that the token needs to be given to the driver as a pre-connect attribute SQL_COPT_SS_ACCESS_TOKEN (https://docs.microsoft.com/en-us/sql/connect/odbc/using-azure-active-directory?view=sql-server-2017).

I know that it is doable in pyodbc but I have not seen any implementation or mention of pre-connect connection attributes in r-odbc docs.

**Comment by jimhester** [comment]
No, there is currently no support for specifying pre-connection attributes. Adding support for it would likely require a decent amount of work, it is unlikely to be done without an external PR.

**Comment by samssann** [comment]
This would be a very welcome feature.

**Comment by hongooi73** [comment]
@jimhester I've received a number of requests for something like this. What is required to make this happen? Is there anything I can contribute?

**Comment by jimhester** [comment]
As mentioned in https://github.com/nanodbc/nanodbc/issues/215 we would have to modify nanodbc to support this, similar to what was done in pyodbc, and then expose an R interface for it in this odbc package.

**Comment by olesendan** [comment]
Hi everybody.

I'm one of persons, trying to implement this in my workflow. I would like to contribute aswell. I consider myself a newbie in software development, and only know R. But I am willing to learn an have some time to work on a solution.

**Comment by julieinsan** [comment]
Upvote and offer to contribute.  We are dealing with this issue presently as the only means of connecting to Azure SQL DB to satisfy our security team.

**Comment by JoshRosenstein** [comment]
Bump. This would be extremely helpful.

**Comment by innir** [comment]
Now that nanodbc seems to have support for it (see https://github.com/nanodbc/nanodbc/commit/b0fa192eb7289bba5450f90ad57075dec3a6581c), things might get going :-)

**Comment by detule** [comment]
Yes / should have a solution that works for us here soon.

**Comment by BaukjeStienstra** [comment]
That would be very nice! But I do have a question about this enhancement of nanodbc: Is there also a need to modify the odbc/DBI R-packages to make it available in an R-environment? And if so, when will this be available?

**Comment by kummerer94** [comment]
@BaukjeStienstra: Due to the incredible work of @detule there is now actually a PR that implements this. https://github.com/r-dbi/odbc/pull/521

I can only say that I am very, very grateful for the work and effort that has gone into this.

**Comment by harrismcgehee** [comment]
This is not working as expected for me. 

I have been able to implement a connection on the same server using `pyodbc.connect(connection_string, attrs_before=attrs_before)`; but I can't get `odbc` in R to work. 

I followed this guide for python: https://debruyn.dev/2023/connect-to-fabric-lakehouses-warehouses-from-python-code/

```
con <- DBI::dbConnect(odbc::odbc(),
                      driver = "ODBC Driver 17 for SQL Server",
                      server = "zzz.datawarehouse.fabric.microsoft.com,1433",
                      database = "yyy",
                      Encrypt="yes",
                      TrustServerCertificate="No",
                      attributes = list("azure_token" = token))
```
``` 
Error in `DBI::dbConnect()`:
! ODBC failed with error 00000 from [Microsoft][ODBC Driver 17 for SQL Server][SQL
  Server].
✖ Login failed due to invalid authentication methods.
ℹ From nanodbc/nanodbc.cpp:1150.
Run `rlang::last_trace()` to see where the error occurred.
Connected to your session in progress, last started 2024-Jun-26 15:32:42 UTC (4 hours ago)
> packageVersion("odbc")
[1] ‘1.5.0’
> packageVersion("DBI")
[1] ‘1.2.2’
```

**Comment by harrismcgehee** [comment]
Resolved. 

I used jwt.ms to compare the tokens. The `aud` of the non-functioning token was `https://database.windows.net` instead of `https://database.windows.net/`.

**Comment by detule** [comment]
Hi @harrismcgehee 

Thanks for the report.  Glad to see this feature getting used.  If you have any suggestions in terms of usability let us know.

Cheers

**Comment by kummerer94** [comment]
@detule This is one of the best features for us ... it has made our development so much better. We get our tokens from Azure CLI which means no more login screens. So, thank you a lot.
