### ISSUE TITLE
Temporary tables not maintaned across subsequent queries

### ISSUE THREAD

**Issue by TTudino** [r-dbi/odbc#310]
Hi Guys, I am trying to use odbc to create temporary tables in a SQL Server and then read from it but I am hitting an error. For instance, I would like to do something like:

check <- dbGetQuery(database_connection, "SELECT whatever INTO #TempTab FROM ExtTab")
update <- dbGetQuery(database_connection, "UPDATE #TempTab SET x = 0")

However, the second query returns:

[Microsoft] [ODBC Driver 17 for SQL Server][SQL Server] Invalid object name '#TempTab'

Any help???????????????

Thanks

**Comment by codref** [comment]
I'm also interested in this. We use a lot of temp tables and currently the library does seem to ignore them.  
Unfortunately global temp (i.e. ##something) are a no-go.

**Comment by krlmlr** [comment]
Thanks for raising this. Is this a duplicate of #127?

**Comment by jimhester** [comment]
I believe this is a duplicate of #127, so I will close this issue.
