### ISSUE TITLE
Column type nvarchar(MAX) getting truncated

### ISSUE THREAD

**Issue by pythiantech** [r-dbi/odbc#315]
This refers to an old issue ([156](https://github.com/r-dbi/odbc/issues/156)).

I am on macOS Catalina Version 10.15.1, running R version 3.6.1. Facing exactly the same issue as described [here](https://github.com/r-dbi/odbc/issues/156). `odbc` version is 1.1.6 which I installed from source and am using the Simba driver to connect to a SQL server running locally on Docker. I do have the freeTDS driver installed, but `odbcListDrivers()` does not list it.

While reading columns of type `nvarchar(MAX)` the results are getting truncated to only the first letter.

**Comment by jimhester** [comment]
If you recompile the package from source it should fix the issue, there is something wrong with the current CRAN binary on macOS.

```r
install.packages("odbc", type = "source")
```
