### ISSUE TITLE
Can't use SQL function NEWID() in odbc

### ISSUE THREAD

**Issue by stlouiso** [r-dbi/odbc#316]
So I'm switching a script from RODBC to odbc that uses the NEWID() function. In RODBC the script runs without error but when I run it with odbc, I get this error:
```
nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]'NEWID' is not a recognized built-in function name.
```
This error is happening for my team and isn't isolated to one computer. Is this a known issue? 

Here's some sample code that produces the error for only odbc:
```
library(odbc)
con <- dbConnect(odbc(), 
                 Driver = "ODBC Driver 17 for SQL Server", 
                 Server = "Server",
                 Database = "DB",
                 Authentication = "ActiveDirectoryIntegrated")
dbGetQuery(con,
           "SELECT TOP 5 *
            FROM TABLE
            ORDER BY NEWID()"
)

library(RODBC)
con2 <- odbcDriverConnect("Driver={ODBC Driver 17 for SQL Server};
                           Server=Server;
                           Database=DB;
                           Authentication=ActiveDirectoryIntegrated;")

sqlQuery(channel = con2, stringsAsFactors = FALSE, query =
           "SELECT TOP 5 *
            FROM TABLE
            ORDER BY NEWID()"
)
```

**Comment by jimhester** [comment]
There is nothing specific to the odbc package that I think would cause this. Seems similar behavior to what you are seeing https://stackoverflow.com/questions/9575622/table-valued-function-is-not-a-recognized-built-in-function-name/9575633, perhaps try the answers suggested there.

As to why this works with RODBC, I do not know.
