### ISSUE TITLE
Rolling back incomplete transaction

### ISSUE THREAD

**Issue by detule** [r-dbi/odbc#327]
Hi @jimhester 

Was hoping to get your thought on rolling back incomplete transactions, before submitting a PR.

The background is that we recently encountered an issue where a call to `dbWriteTable` **silently** failed to write the entirety of the argument data to the destination table.  The underlying cause was a likely a [bug](https://github.com/FreeTDS/freetds/pull/318) in FreeTDS, however the silent failure is a bit disconcerting.

In this particular case, despite the incomplete write the driver/SQLExecute returned `SQL_SUCCESS_WITH_INFO`, which at least according to [this](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/using-arrays-of-parameters?redirectedfrom=MSDN&view=sql-server-ver15) piece of documentation is a reasonable state.  At this point [nanodbc](https://github.com/r-dbi/odbc/blob/master/src/nanodbc/nanodbc.cpp#L227) declares success and `package:odbc` loses track of the issue.

In https://github.com/detule/odbc/commit/e15f70ca7c81c1efb36c331b2034f615548e241d in `bind_list` after each batched execution I check whether the number of affected rows is as expected, and if not:

* Bail on the remaining batches
* Attempt to rollback the transaction
* Throw an error

This does require a new round-trip to the server, per batch.

Original issue (again, the root cause we believe to be elsewhere) was with a combination of SQL Server + FreeTDS
```
df <-
  data.frame(id = 1:5, val = c(0.1, 0.01, 0.001, 0.0001, 0.00001))
DBI::dbExecute(conn, "CREATE TABLE ##test_delete_me2(id INT, val DECIMAL(12,6))")
dbWriteTable(conn, "tempdb.dbo.##test_delete_me2", df, overwrite = FALSE, append = TRUE)
[1] TRUE
> dbGetQuery(conn, "SELECT * FROM tempdb.dbo.##test_delete_me2")
  id   val
1  1 1e-01
2  2 1e-02
3  3 1e-03
4  4 1e-04
```

Appreciate your feedback.

**Comment by detule** [comment]
Gentle ping @jimhester :

We came across this issue in a new context - when writing to a table where we have insufficient privileges.

In particular, `nanodbc` silently processes the `SQL_SUCCESS_WITH_INFO`.  As a result, `dbWriteTable` is oblivious to the fact that the write has failed.

The example below is with a SQL Server back-end and using both FreeTDS, as well as the Microsoft SQL Server Driver.  I inserted a `printf` in nanodbc.cpp just after the call to `SQLExecute` to log the return value.

```
# Single row write throws, `SQLExecute` returns `SQL_NO_DATA` in this case. 
> dbWriteTable(conn, tbl2write, x2[1, ], overwrite = FALSE, append = TRUE)
SQL Execute, rc:-1
Error in result_insert_dataframe(rs@ptr, values) :
  nanodbc/nanodbc.cpp:1600: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The INSERT permission was denied o

# Failure to write/throw on a multi-row prepared insert statement to same table, SQLExecute returns SQL_SUCCESS_WITH_INFO
> dbWriteTable(conn, tbl2write, x2, overwrite = FALSE, append = TRUE)
SQL Execute, rc:1
[1] TRUE
```
Patching `package:odbc` with the patch from the first post, I get better results:
```
> dbWriteTable(conn, tbl2write, x2, overwrite = FALSE, append = TRUE)
SQL Execute, rc:1
Error in result_insert_dataframe(rs@ptr, values) :
  Failed writing row num 0; Attempted to rollback cleanly.
```

**Comment by jimhester** [comment]
If the driver is returning `SQL_SUCCESS_WITH_INFO` I think we have to assume it was successful. I am not very confident in all drivers always returning the proper number of affected rows.

**Comment by detule** [comment]
Jim - thanks!

Given the `nanodbc` handling of the `SQLExecute` call, can you think of another way around this - perhaps without checking the number of affected rows?

According to the documentation for [SQLExecute](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlexecute-function?view=sql-server-ver15) it is valid for the call to return `SQL_SUCCESS_WITH_INFO`, and yet for a message such as "42000: Syntax error or access violation" to be buried in the diagnostics of the call.

We are a little bit concerned about migrating production writes to `odbc`, if write failures can happen silently.

Thanks again for giving this some thought.

**Comment by jimhester** [comment]
It also states

> The return code associated with each SQLSTATE value is SQL_ERROR, unless noted otherwise.

So the only states that can be returned if the overall return value is `SQL_SUCCESS_WITH_INFO` should be those which explicitly mention it in the description, e.g. 01001, 01003, 01004, 01006, 01S02, 01S07, 07006, 22007.

**Comment by detule** [comment]
Thanks again Jim - I don't mean to be bugging you, and I appreciate your time invested in this.

It could be the difference between using parametrized queries and not - the `SQLExecute` page points to a [different page on using this call](https://docs.microsoft.com/en-us/sql/odbc/reference/develop-app/using-arrays-of-parameters?view=sql-server-ver15) with parametrized queries, where it states

```
If the SQL_ATTR_PARAM_STATUS_PTR statement attribute has been set, SQLExecute or
SQLExecDirect returns the parameter status array, which provides the status of each set of
parameters. The parameter status array is allocated by the application and filled in by the driver.
Its elements indicate whether the SQL statement was executed successfully for the row of
parameters or whether an error occurred while processing the set of parameters. If an error
occurred, the driver sets the corresponding value in the parameter status array to
SQL_PARAM_ERROR and returns SQL_SUCCESS_WITH_INFO. The application can check the
status array to determine which rows were processed. Using the row number, the application can
often correct the error and resume processing.
```

Whatever the case with documentation it remains the case that Microsoft's ODBC driver (as well as freeTDS) do pair `SQL_SUCCESS_WITH_INFO` with SQLSTATE 42000.

Out of luck with using both of these drivers?

**Comment by detule** [comment]
Upon further testing: in line with your suspicion the Microsoft driver does return SQL_ERROR rather than SQL_SUCCESS_WITH_INFO, even in the case of a parametrized query.

FreeTDS is the offender here.

Thanks for all your help - appreciate you helping me chase this down.
