### ISSUE TITLE
DB errors are truncated to 1000 characters

### ISSUE THREAD

**Issue by vspinu** [r-dbi/odbc#329]
### Issue Description and Expected Result

With longer than 1000 chars queries the errors are truncated.

### Database

PostgresSQL  11.4 (Ubuntu 11.4-1.pgdg16.04+1)

 odbc        * 1.2.1.9000 2019-12-11 [1] local                           

### Example

Any query longer than 1000 chars with syntax error or missing column wtih `odbc::dbGetQuery`.

**Comment by jimhester** [comment]
Truncated by R or by the driver? If the former set `options(warning.length)` to a larger value or capture the error object, the truncation is just when printing.

**Comment by vspinu** [comment]
Yeh. That was it. So many years with R and I have never heard of that option :/ Thanks!
