### ISSUE TITLE
Can `dbGetQuery()` and `dbReadTable()` behave like `dbListFields()` [regarding default schema]

### ISSUE THREAD

**Issue by jhuntergit** [r-dbi/odbc#330]
Once I establish a connection with `DBI::dbConnect()` I can start running commands on it like this:

```
DBI::dbListFields(con, "ibin_acq")
#>  [1] "MANDT"           "IN_RECNO"        "VALFR"           "VALTO"          
#>  [5] "AENNR"           "DELFLAG"         "IN_STANCE"       "MLANG"          
#>  [9] "SORTF"           "OBJNR"           "IBASE"           "AMOUNT"         
#> [13] "UNIT"            "DATUV"           "TECHS"           "IN_OBJNR"       
#> [17] "IN_GUID"         "OBJECTTYP"       "VOID"            "CSTATUS"        
#> [21] "CUCOCNT"         "EXPERT"          "MAT_VARIANT"     "ATAUT"          
#> [25] "KLART"           "CRNAM"           "CRTIM"           "UPNAM"          
#> [29] "UPTIM"           "SOURCE_ID"       "EXTRACTION_DATE"
```

It turns out that `dbListFields()` does not apply the default schema, though `dbGetQuery()` and `dbReadTable()` both do, and to demonstrate I'll issue the following command:

```
DBI::dbReadTable(con, "ibin_acq")
#> Error in new_result(connection@ptr, statement) : 
#>   nanodbc/nanodbc.cpp:1344: 42S02: [Teradata][ODBC Teradata Driver]
#> [Teradata Database](-3807)Object 'ibin_acq' does not exist. 
```

I can issue the command shown below to determine the DataBaseName to use, to replace the Database, when establishing my `con` connection. Then `DBI::dbReadTable(con, "ibin_acq")` will work. But is it possible to make `dbGetQuery()` and `dbReadTable()` behave like `dbListFields()`, to avoid the issue altogether?

```
DBI::dbGetQuery(con, "SELECT CURRENT_USER, DATABASE, DatabaseName, TableName FROM DBC.TablesV WHERE TableName='ibin_acq'")
```

**Comment by jimhester** [comment]
No, it is not possible. Note you can also use `DBI::Id()` to specify the schema you want to use directly, which would be the most robust way for you to handle this.

**Comment by jhuntergit** [comment]
Is this an appropriate feature request for the DBI package? Or for one (or more) other reasons is it a bad idea? Thanks for the `DBI::Id()` tip.

**Comment by jimhester** [comment]
It is just not really possible with the ODBC API
