### ISSUE TITLE
Invalid Descriptor Index 

### ISSUE THREAD

**Issue by mckenziem** [r-dbi/odbc#331]
I keep getting an error when trying to load a SQL table. 

SELECT * FROM is not working. When I replace * with a variable it works. I have over 200 variables I need * to work. 

Error in result_fetch(res@ptr, n) : 
  nanodbc/nanodbc.cpp:2966: 07009: [Microsoft][ODBC SQL Server Driver]Invalid Descriptor Index

**Comment by jimhester** [comment]
This is a duplicate of https://github.com/r-dbi/odbc/issues/10, https://github.com/r-dbi/odbc/issues/309. Long data columns have to be placed at the end of SELECT queries according to the ODBC spec for `SQLGetData()`, unless the driver you are using supports `SQL_GD_ANY_ORDER`.
