### ISSUE TITLE
odbc should detect db server timezone

### ISSUE THREAD

**Issue by mkirzon** [r-dbi/odbc#332]
As we've started replacing RODBC with odbc in our organization, I'm finding that the odbc timezone behavior is rather unintuitive and easily leads to incorrect timestamps being propogated into our analyses. 

The source of this confusion is that the `odbc::dbConnect` defaults the server (eg SQL Server) timezone to "UTC" rather than what the database is actually configured to. Contrast this with R's default behavior which sets local POSIX values to the local system's timezone (in our case, Pacific time).

So here's an example (problematic) workflow: 
1. Parse some flat file logs on a local computer (Pacific timezone). Without explicit timezone handling, R will treat imported timestamps to use Pacific timezones. 
2. Query a database (in the same timezone and configured to Pacific timezone) for meta data related to those logs. Without explicit timezone specifications, the returned timestamps will have the `tzone` attribute set to UTC. 
3. Combining the datasets (through vector appending, or dataframe joins) will silently match the timezones but do so by actually offsetting the times for one of the sources. 

In step 3, the issue is that the raw timestamps were correct but had the wrong timezone attribute. As a result, the timestamps will be **incorrectly shifted** leading to incorrect analyses. 

I know that odbc 1.2.0 launched with a really useful and explicit `timezone_out` feature. However, after watching a number of folks fall prey to this issue, I would argue that the *default behavior of odbc timezone handling is unintuitive*. 

For this reason, in our case, I would have liked something like `timezone = NULL` (and have that as default) which would use the internal database timezone *before* offseting to `timezone_out`. 

What are your thoughts?

**Comment by krlmlr** [comment]
It might be difficult to detect the server timezone portably for all database servers out there.

**Comment by shrektan** [comment]
Yes, the default should be timezone_out = timezone (not NULL). Despite that it may break the existing code, I vote for the change.

**Comment by mkirzon** [comment]
@krlmlr I can imagine. Would a `dbplyr`-analogous approach work? They have DB-specific translations that are completely modularized, and has a default behavior when certain translations haven't yet been implemented?

**Comment by mkirzon** [comment]
@shrektan I hadn't thought of that but agree that that's an additional change that would be more intuitive behavior. 
On a related note, what if there's at least a way to return `POSIXct` columns *without any `tzone`* attribute? This would mimic `RODBC` behavior and could indirectly solve the problem (in my original post) by then having R apply its default timezone handling.

**Comment by shrektan** [comment]
If your DB server has the same timezone as your local computer, set it to timezone should be identical as if set to NULL. In addition, I take the bet that many users (if not all) have the same timezone both locally and remotely (the DB server). So I think timezone_out = timezone is the correct choice.

 Moreover, not as RODBC, where you can't set the timezone, we have already explicitly set the timezone to something. Returning a DateTime column with the same timezone looks a natural choice for me.

**Comment by mkirzon** [comment]
I agree that many users would likely be running queries in the same timezones as their data sources. Perhaps we're an exception since we are a team of 20 data analysts at an international manufacturing org and regularly run queries against at least 2 timezones and use R to merge the results. 

So the best case solution would still be to autodetect and apply the remote source's timezone. However, if I understood your recommendation correctly, `timezone_out = timezone` and `timezone= Sys.timezone()` would be a decent solution as well

**Comment by jimhester** [comment]
> In step 3, the issue is that the raw timestamps were correct but had the wrong timezone attribute. As a result, the timestamps will be incorrectly shifted leading to incorrect analyses.

> Combining the datasets (through vector appending, or dataframe joins) will silently match the timezones but do so by actually offsetting the times for one of the sources.

There is no _wrong_ timezone attribute, the timezone is used for the display.

The actual time point value is the same regardless of the timezone attribute and is the only thing that is used by a join. e.g. all the following methods of combining or joining two time points ignore the timezone attribute.

The defaults were chosen to ensure that the same code produces the same output regardless of the local timezone, it was chosen this way deliberately.

``` r
x <- as.POSIXct("2019-01-01 12:01:01", tz = "UTC")
y <- x
attr(y, "tzone") <- "EST"

x
#> [1] "2019-01-01 12:01:01 UTC"
y
#> [1] "2019-01-01 07:01:01 EST"

c(x, y)
#> [1] "2019-01-01 07:01:01 EST" "2019-01-01 07:01:01 EST"

vctrs::vec_c(x, y)
#> [1] "2019-01-01 12:01:01 UTC" "2019-01-01 12:01:01 UTC"

suppressMessages(library(dplyr))
x_df <- tibble(time = x, foo = 1)
y_df <- tibble(time = y, bar = 2)

left_join(x_df, y_df)
#> Joining, by = "time"
#> # A tibble: 1 x 3
#>   time                  foo   bar
#>   <dttm>              <dbl> <dbl>
#> 1 2019-01-01 12:01:01     1     2

merge(x_df, y_df)
#>                  time foo bar
#> 1 2019-01-01 12:01:01   1   2
```

<sup>Created on 2019-12-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mkirzon** [comment]
I've tried illustrating how the confusion naturally occurs in our workflow with this example -

```
# This is a locally generated timestamp (eg in US/Pacific)
t_local = as.POSIXct("2019-01-01 12:01:01")
t_local
#> [1] "2019-01-01 12:01:01 PST"

# This is a timestamp coming from the database that's also in US/Pacific. The raw time is indeed 12:01:01 *in Pacific time*  
t_db = as.POSIXct("2019-01-01 12:01:01", tz = "UTC")
t_db
#> [1] "2019-01-01 12:01:01 UTC"

# The expectation for merging the two results should be two *identical* times. However, one of them gets *offset* since they have different tzone attributes
vctrs::vec_c(t_local, t_db)
#> [1] "2019-01-01 20:01:01 UTC" "2019-01-01 12:01:01 UTC"
```

**Comment by jimhester** [comment]
That is because those aren't the same timestamp, if your database is in `US/Pacific` you need to use `timezone = "US/Pacific"` in your initial connection, the default is to assume the database is returning times in `UTC`. 

One of them is offset because it _is_ a different time, see how the numeric representation is different between the to values below?

``` r
t_local = as.POSIXct("2019-01-01 12:01:01")
t_db = as.POSIXct("2019-01-01 12:01:01", tz = "UTC")

unclass(t_local)
#> [1] 1546362061
#> attr(,"tzone")
#> [1] ""
unclass(t_db)
#> [1] 1546344061
#> attr(,"tzone")
#> [1] "UTC"
```

<sup>Created on 2019-12-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mkirzon** [comment]
So that was the original point of this issue :) That default assumption is wrong and is prone to errors for workflows like ours in which we query 30+ different servers, each properly configured for timezones. Having to specify the timezone would require our analysts to have prior knowledge to where these dbs live which we typically don't.

**Comment by jimhester** [comment]
Not knowing what timezone a particular DB is in is an even worse situation, the db could be giving you locale datetimes in a completely different timezone than what you analist is using and then all of the actual time points would be wrong.

Ideally all your datetimes are stored in your database tables as UTC datetimes, but if not you _need_ to know what local timezone they are in before you can correctly interpret them.

**Comment by jimhester** [comment]
I understand the frustration with this.

I unfortunately don't think there is a way to detect the server's timezone that would work across database types, so I am closing this issue.

**Comment by shrektan** [comment]
Yes, I agree. As far as I know, usually the DB won’t storage the timezone info. No way to detect the timezone of the DB server uses. What’s worse, the server’s timezone is not necessarily the timezone of the data.
