### ISSUE TITLE
'insufficient privileges' error from dbWriteTable() despite having priviledges on DB

### ISSUE THREAD

**Issue by pinkumbrella14** [r-dbi/odbc#333]
I am trying to append my data frame to a blank table that exists in an Oracle DB. I am successfully able to establish a connection to the DB with the following code:

```r
xx_re_connect <- dbConnect(odbc::odbc(), "DBNAME", uid = "xxxxx", 
                          pwd = 'xxxxxx')
```
I am able to successfully import data from tables on this DB; however, when I try using dbWriteTable() to add new rows to a table (to which I have write priviledges), I get the following error:
'nanodbc/nanodbc.cpp:1587: HY000: [Oracle][ODBC][Ora]ORA-01031: insufficient privileges'

This is the code I'm using inside the dbWriteTable() function:
```r
dbWriteTable(conn = xx_re_connect,
             name = "table_name",
             value = data_table_rbindlist_,
             row.names = FALSE,
             field.types = c(FORECAST_GUID = "varchar(36)",
                             FORECAST_TYPE = "varchar(255)",
                             REPORT_DATE = "date",
                             LOC_ID = "varchar(36)",
                             WELL = "varchar(255)",
                             TAG_NAME = "varchar(255)",
                             TAG_TYPE = "varchar(255)",
                             FORECAST_BREACH_DATE = "timestamp",
                             FORECAST_BREACH_VALUE = "number",
                             UPPER_BOUND = "number",
                             LOWER_BOUND = "number",
                             DATA_POINTS_USED = "number",
                             LAST_READING_DATE = "date",
                             LAST_READING_VALUE = "number",
                             IA_NOL = "number",
                             OA_NOL = "number",
                             OOA_NOL = "number",
                             USER_STAMP = "varchar(255)"
                             ),
             append = TRUE
             )

It seems like the issue is the fact that this dbWriteTable() script gets translated into a 'Create Table' sql statement, for which I do not have priviledges. So is there a way to change the dbWriteTable() function so that the sql statement is translated to either 'INSERT' or 'APPEND'

**Comment by jimhester** [comment]
If you use `append = TRUE` it will not try to create the table (assuming it exists).

I would guess that odbc does not think the table exists. Does `dbExistsTable(con, "table_name")` return `TRUE`? Because the odbc package always quotes identifiers they are case sensitive in Oracle, so be sure the case matches.

**Comment by pinkumbrella14** [comment]
@jimhester I went ahead and followed your advice - now I'm a little bit confused. So I want to give you some more detail. Here is how I am connecting to the DB:
```r
asss_re_connect <- dbConnect(odbc::odbc(), "ASSS", uid = "xxx", 
                          pwd = 'xxx', believeNRows=FALSE)
```
A connectio is established and I can see the tables. I can query the empty table that I am trying to write to using this code:
```r
testing_query <- dbSendQuery(asss_re_connect,
                            "SELECT *
                            FROM ASSS.ANN_NOL_FORECAST_TAB")
#fetch merged table
testing_tbl <- dbFetch(testing_query)
```
And from this I get back a list of the table columns and the fact that this table has 0 rows.

Now, the confusing part. When I try 
```r
dbExistsTable(asss_re_connect, "ASSS.ANN_NOL_FORECAST_TAB")
```
I get back FALSE. However, when I try leaving the database name off of the table:
```r
dbExistsTable(asss_re_connect, "ANN_NOL_FORECAST_TAB")
```
I get back TRUE.

However when I try appending the table that does exist (so without using the DB name in the table name), like so:
```r
dbAppendTable(asss_re_connect,
              "ANN_NOL_FORECAST_TAB",
              data_table_rbindlist_)
```
I get an error 'table of view does not exist'.

Do you have any thoughts on what may be going on? I genuinly can not understand, nor find any info, on why the table that I am able to query and read from, shows up as 'FALSE' when I try to see if it exists.

Thanks for your help!

**Comment by jimhester** [comment]
Likely because of various quoting rules for Oracle databases, I unfortunately can't give you much more advice than that.
