### ISSUE TITLE
dbAppendTable cuts off (truncates) nvarchar fields to 255

### ISSUE THREAD

**Issue by liudvikasakelis** [r-dbi/odbc#335]
Tables inserted into a MSSQL database using dbWriteTable(append or from scratch) insert their full text fields, however, using dbAppendTable cuts them off at 255 characters. All libraries are reasonably new, everything repeatable across 3 machines with slightly different library versions, I'll include configuration of one.

```r
sessionInfo()
# R version 3.6.1 (2019-07-05)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Arch Linux

# Matrix products: default
# BLAS:   /usr/lib/libptf77blas.so
# LAPACK: /usr/lib/libptlapack.so.3.6.1

# locale:
#  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
#  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

# attached base packages:
# [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

# other attached packages:
# [1] feather_0.3.5     stringi_1.4.3     xml2_1.2.2        DBI_1.1.0         odbc_1.2.1        RJSONIO_1.3-1.3   data.table_1.12.6

# loaded via a namespace (and not attached):
#  [1] Rcpp_1.0.3      zeallot_0.1.0   crayon_1.3.4    backports_1.1.5 pillar_1.4.2    rlang_0.4.1     blob_1.2.0      vctrs_0.2.0     tools_3.6.1    
# [10] bit64_0.9-7     bit_1.1-14      hms_0.5.2       compiler_3.6.1  pkgconfig_2.0.3 tibble_2.1.3   

connection <- DBI::dbConnect(
  odbc::odbc(),
  Driver="ODBC Driver",
  Server=cfg$server_name,
  Database=cfg$database,
  UID=cfg$uid,
  PWD=cfg$pass,
  Port=1433
)

connection
# <OdbcConnection> classified
#   Database: dbname
#   Microsoft SQL Server Version: 13.00.5026

t1 <- data.table(x1="one", x2=paste0(rep("zed", 100), collapse="."))
dbWriteTable(connection, name="t1", t1)
dbWriteTable(connection, name="t1", t1, append=T)
dbAppend(connection, name="t1", t1)
```
The following SQL statement then shows the problem:

    SELECT LEN(x2) FROM dbname.dbo.t1

> 399
> 399
> 255

The last one from the last insert (the dbAppendTable) has been truncated. I believe this is a bug. A few relevant libraries:

unixodbc 2.3.7-2
freetds 1.00.100-1 

I'd love for someone to shed some light on this, especially because the pdf manual encourages the use of dbAppendTable, and just for following that I've spent a day debugging.

**Comment by krlmlr** [comment]
Thanks for raising this. It's likely that `dbAppendTable()` uses a different code path in the {odbc} package, perhaps we need a custom implementation.

**Comment by jimhester** [comment]
In the meantime I would suggest using `dbWriteTable()` with odbc connections.

**Comment by jimhester** [comment]
Should now be remove ``` r
library(DBI)
con <- dbConnect(odbc::odbc(), "MicrosoftSQLServer", UID="SA", PWD="Password12")
t1 <- data.frame(x1="one", x2=paste0(rep("zed", 100), collapse="."))
dbWriteTable(con, name="t1", t1)
dbWriteTable(con, name="t1", t1, append=T)
dbAppendTable(con, name = "t1", t1)
dbGetQuery(con, "SELECT LEN(x2) FROM t1")
#>      
#> 1 399
#> 2 399
#> 3 399
```

<sup>Created on 2020-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
