### ISSUE TITLE
odbc package in R throwing caught segfault error while connecting to ORACLE Database

### ISSUE THREAD

**Issue by sachalla1** [r-dbi/odbc#336]
I am trying to connect to oracle database using odbc package in R and while connecting it is throwing caught segfault and we are unable to connect to database. Please find the details mentioned below and we have configured unixodbc configuration in the server but with RODBC package, we are able to establish the connection.
```r
library(odbc) Target2Conn<-dbConnect(odbc::odbc(), dsn = "PEGA_DEV", uid = "username", pwd = "username_123")

* caught segfault * address 0x38, cause 'memory not mapped'

Traceback:

1:

odbc_connect(connection_string, timezone = timezone, timezone_out = timezone_out,     encoding = encoding, bigint = bigint, timeout = timeout)
2:

OdbcConnection(dsn = dsn, ..., timezone = timezone, timezone_out = timezone_out,     encoding = encoding, bigint = bigint, timeout = timeout,     driver = driver, server = server, database = database, uid = uid,     pwd = pwd, dbms.name = dbms.name, .connection_string = .connection_string)
3: .local(drv, ...)

4:

dbConnect(odbc::odbc(), dsn = "PEGA_DEV", uid = "username", pwd = "username_123")
5:

dbConnect(odbc::odbc(), dsn = "PEGA_DEV", uid = "username", pwd = "username_123")
Possible actions: 1: abort (with core dump, if enabled) 2: normal R exit 3: exit R without saving workspace 4: exit R saving workspace Selection
```

**Comment by jimhester** [comment]
It is unfortunately hard to say from this error, however you may want to try installing the latest dev version and see if that resolves the issue.

```r
remotes::install_dev("odbc")
```

**Comment by sachalla1** [comment]
Hi Jim,
When we are trying to install the odbc package using the above mentioned, we facing issue mentioned below.

**Error: Failed to install 'unkown package' from GitHub:
Could not resolve host:  api.github.com**


We assume github url is blocked for our intranet and could not install. Is there any way we could download the package in local and then install the package.

**Comment by jimhester** [comment]
You can also use `download.packages("odbc")` then install the package from there.
