### ISSUE TITLE
Interrupt SQL Server queries

### ISSUE THREAD

**Issue by mkirzon** [r-dbi/odbc#344]
I use `odbc` usually via `dbplyr` in RMarkdowns and it would be nice to have the chunk or console 'stop' buttons fully interrupt the query server-side and make the command line usable again. 

Currently, we are unable to interrupt or gracefully terminate long running queries. As a result, RStudio has to be killed via task manager.

**Comment by jimhester** [comment]
We check for interrupts when writing and reading results, however if the query is taking a long time in the initial query step we don't have much we can do I think, unless we move towards a async query interface

**Comment by krlmlr** [comment]
Would be solved by #312, can we close this as a duplicate?

**Comment by jimhester** [comment]
Sure, we will track it in #312
