### ISSUE TITLE
`dbFetch()` doesn't fetch all result sets

### ISSUE THREAD

**Issue by vkapartzianis** [r-dbi/odbc#346]
### Issue Description and Expected Result
Stored procedures and parameterized queries can return multiple result sets but `dbFetch()` only fetches the first one.

### Database
The issue certainly affects SQL Server connections (see also #259) but will affect any driver that returns multiple result sets.

### Reproducible Example
The following is reproducible with SQL Server connections, which return a result set for each parameter set. I couldn't reproduce it with MySQL connections, as those apparently return a single result set for all parameters.

Example:
``` R
``` R
library(DBI)

dev_db <- dbConnect(odbc::odbc(), "dev_db")

df <- data.frame(id = 1:10)

if (dbExistsTable(dev_db, "df")) dbRemoveTable(dev_db, "df")
dbCreateTable(dev_db, "df", df)

sql <- "INSERT INTO df (id) VALUES (?)"
rs <- dbSendStatement(dev_db, sql)
dbBind(rs, df)
dbClearResult(rs)

print(dbReadTable(dev_db, "df"))

sql <- "SELECT id FROM df WHERE id=?"
rs <- dbSendQuery(dev_db, sql)
dbBind(rs, df)
results <- dbFetch(rs)
dbClearResult(rs)

print(results)

dbDisconnect(dev_db)
```

Output:
```
   id
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
10 10
  id
1  1
```

Expected output:
```
   id
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
10 10
   id
1   1
2   2
3   3
4   4
5   5
6   6
7   7
8   8
9   9
10 10
```

### Notes
I have submitted a pull request to resolve the issue: https://github.com/r-dbi/odbc/pull/345

**Comment by shrektan** [comment]
Should be closed as the related PR is merged.
