### ISSUE TITLE
`dbBind()` doesn't properly support more than 1024 parameter sets

### ISSUE THREAD

**Issue by vkapartzianis** [r-dbi/odbc#347]
### Issue Description and Expected Result
`dbBind()` splits parameter sets in batches of `batch_rows = getOption("odbc.batch_rows", 1024)` for some reason. Each batch overwrites the results of the previous one, as a) no driver supports "multiple active result sets" by default and b) nanodbc will clear previous result sets with `SQLFreeStmt()` in any case.

### Reproducible Example
Example:
``` R
library(DBI)

dev_db <- dbConnect(odbc::odbc(), "dev_db")

df <- data.frame(id = 1:1026)

if (dbExistsTable(dev_db, "df")) dbRemoveTable(dev_db, "df")
dbCreateTable(dev_db, "df", df)

sql <- "INSERT INTO df (id) VALUES (?)"
rs <- dbSendStatement(dev_db, sql)
dbBind(rs, df)
dbClearResult(rs)

print(tail(dbReadTable(dev_db, "df")))

sql <- "SELECT id FROM df WHERE id=?"
rs <- dbSendQuery(dev_db, sql)
dbBind(rs, df)
results <- dbFetch(rs)
dbClearResult(rs)

print(tail(results))

dbDisconnect(dev_db)
```

Output:
```
       id
1021 1021
1022 1022
1023 1023
1024 1024
1025 1025
1026 1026
    id
1 1025
2 1026
```

Expected output:
```
       id
1021 1021
1022 1022
1023 1023
1024 1024
1025 1025
1026 1026
       id
1021 1021
1022 1022
1023 1023
1024 1024
1025 1025
1026 1026
```

### Notes
A workaround would be to set `batch_rows` to the size of the parameter set, as below. This feature should just be removed as it's not properly supported, though. Anyone that would like to split parameter sets by some batch size, can easily do so in an R loop.

``` R
dbBind(rs, df, batch_rows = nrow(df))
```

**Comment by jimhester** [comment]
Should now be resolved by https://github.com/r-dbi/odbc/commit/65870d3d61c993213ee7264a9ce1bbfebd23006d
