### ISSUE TITLE
R connection to MS SQL

### ISSUE THREAD

**Issue by ifuchs** [r-dbi/odbc#348]
I have (finally) gotten R to talk to a MS SQL Server. At least this works:
con <- dbConnect(odbc(), "dsn",UID="sa",PWD="pswd",Database="dbname")

However, when I do: dbListTables(con), I get a list of 1000+ tables that are not part of my database!

This line: sort(unique(odbcListDrivers()[[1]])) gives:
[1] "ODBC Connection Pooling"       "ODBC Driver 17 for SQL Server" "ODBC Drivers"
If I try to do a a dbSendQuery, my tablenames seem to be recongized (no error) but all results are 0 row retrieved. Moreover, if I try to query one of the tables that she ListTables returned, it says object not found.
Can someone explain this and more importantly, tell me how I cn query my database?

**Comment by jimhester** [comment]
I think your questions would be better answered on the RStudio community site [community.rstudio.com](https://community.rstudio.com/tag/database). Would you mind asking it over there?
