### ISSUE TITLE
"SQL Server" driver does not respect 'port' parameter

### ISSUE THREAD

**Issue by DavidPatShuiFong** [r-dbi/odbc#353]
### Issue Description and Expected Result

When accessing a Microsoft SQL server which has a non-standard port (perhaps because the SQL Server is open to the Internet, yes, I know that shouldn't be done....) then the 'Port' parameter makes no difference, it appears that the standard port 1433 is being used.

As a result, I can't set up the Microsoft SQL Server using a non-standard port to be accessed by R. I can access the same database set up with a non-standard port using dBeaver.

### Database

Microsoft SQL Server 12

### Reproducible Example
```r
> packageVersion("odbc")
 [1] ‘1.1.6’ 
> con <- dbConnect(odbc(), Driver = "SQL Server", Server = "blah.blah.org", Database = "bpssamples", UID = "myuid", PWD = "mypassword") 
>  
> head(dbListTables(con))
 [1] "ACCIDENT"          "ACCIDENTDIAGNOSIS" "ACCIDENTLINK"      "ACCOMODATION"      "ACCOUNTTEXT"       "ACCOUNTTYPE"       
> dbDisconnect(con) 
> con <- dbConnect(odbc(), Driver = "SQL Server", Server = "blah.blah.org", Database = "bpssamples", UID = "myuid", PWD = "mypassword", port = 8888) 
>  
> head(dbListTables(con)) 
[1] "ACCIDENT"          "ACCIDENTDIAGNOSIS" "ACCIDENTLINK"      "ACCOMODATION"      "ACCOUNTTEXT"       "ACCOUNTTYPE"
```
Also tested with `ODBC Driver 13 for SQL Server`.

**Comment by jimhester** [comment]
That is because SQL Server connections strings do not use `port=` to specify an alternative port, you specify it with a `,port` after the server name. <https://www.connectionstrings.com/microsoft-odbc-driver-17-for-sql-server/using-a-non-standard-port/>

e.g. `Server = blah.blah.org,8888`

**Comment by DavidPatShuiFong** [comment]
Thank you @jimhester ! I saw that syntax elsewhere, but didn't realize it applied to odbc.
