### ISSUE TITLE
Better behavior for "Invalid Descriptor Index" problem

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/odbc#358]
I'm now convinced that the problem must be solved by using an appropriate driver, or putting long columns at the end of the query.

Still: Can we do better than throwing `"Invalid Descriptor Index"` at the user?

``` r
library(DBI)
library(tidyverse)

con <- dbConnect(odbc::odbc(), "mssql-test-ms", uid = "kirill", pwd = keyring::key_get("mssql", "kirill"))

data <- tibble(a = 1:3, b = "a", c = 1)

copy_to(con, data, name = "##data1", types = c("integer", "varchar(max)", "real")) %>% collect()
#> Error in result_fetch(res@ptr, n): nanodbc/nanodbc.cpp:2908: 00000: [Microsoft][ODBC Driver 17 for SQL Server]Invalid Descriptor Index
#> Warning in dbClearResult(res): Result already cleared
```

<sup>Created on 2020-04-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Follow-up to #309.

**Comment by jimhester** [comment]
Should be fixed by https://github.com/r-dbi/odbc/pull/381
