### ISSUE TITLE
macOS: `freetds` formula has no option `--with-unixodbc`

### ISSUE THREAD

**Issue by pat-s** [r-dbi/odbc#362]
As stated in the [installation instructions in the README](https://github.com/r-dbi/odbc#common-db-drivers).

**Comment by jimhester** [comment]
This option was [removed in homebrew](https://github.com/Homebrew/homebrew-core/commit/f3664604cbde0ab135e7af48c8e6db0b72b7f5d3), it now seems to use unixodbc unconditionally. Se we can remove this from the readme.
