### ISSUE TITLE
Batch insertion for dbWriteTable()

### ISSUE THREAD

**Issue by Microkiller** [r-dbi/odbc#366]
### Issue Description and Expected Result

I am now using dbWriteTable() to insert R dataframes into SQL tables. It is working.
But I notice at the backend, it is actually inserting the dataframe row by row. Is there a parameter controls this behavior or any other functions available to insert the dataframe all at one time?
### Database

SQL server 2012
### Reproducible Example

For example, I have a dataframe with 2 rows. When I am calling dbWriteTable(), what it is actually doing is:
Insert into table1
Select row 1
Insert into table1
Select row 2

What I am expecting:
Insert into table1
(select row 1
union
select row2)

It seems not a big difference. In my case, I have triggers on table1, the difference will be the trigger is triggered just once or multiple times. If the dataframe is large, the difference is noticeable.
<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> output
```
</details>

**Comment by jimhester** [comment]
odbc does the equivalent of

```
INSERT INTO table 1 (field1, field2, field3)
VALUES (?, ?, ?)
```

Then binds the data associated with field1, field2, and field3. If thee driver converts that into rowwise insertion there isn't a lot the odbc package can do.

I would suggest you disable the trigger when inserting.
