### ISSUE TITLE
Database does not appear in connections pane when `dbConnect` called within function

### ISSUE THREAD

**Issue by doctortickle** [r-dbi/odbc#370]
### Issue Description and Expected Result
When `DBI::dbConnect` is called within a function, the database connection should appear in the connections pane of Rstudio.

RStudio Version 1.3.959

### Database
PostgreSQL Version: 12.0.1

### Reproducible Example
This will connect to the database **and** show up in the connections pane of Rstudio.
```
con <- DBI::dbConnect(odbc::odbc(),
                 Driver = driver,
                 Server = ip,
                 Databse = db,
                 Port = port,
                 UID = user,
                 PWD = pw
```
This does **not** show up in the connections pane of Rstudio, even though the connection works.
```
conn_db <- function(driver, ip, db, port, user, pw) {
  DBI::dbConnect(odbc::odbc(),
                 Driver = driver,
                 Server = ip,
                 Databse = db,
                 Port = port,
                 UID = user,
                 PWD = pw
                 )
}
```

**Comment by jimhester** [comment]
Yes, this is a limitation in the way the RStudio connections pane works, only top level connections are supported in it.

This is unlikely to change, so I think it best to close this issue.
