### ISSUE TITLE
Connection for Shiny

### ISSUE THREAD

**Issue by atakzltn** [r-dbi/odbc#378]
I can connect to DB with FreeTDS but I got the error that you can find in below when publish in Shiny. Thank you.

`DBI::dbConnect(odbc::odbc(), Driver = "FreeTDS", 
    Database = "***", Server = "***", UID = "***", 
    PWD = "****", Port = 1433)`

![image](https://user-images.githubusercontent.com/63283600/86395370-d1497000-bca8-11ea-8f79-6dea23543718.png)

**Comment by jimhester** [comment]
You would need to have the same database information setup and available in however you are deploying to shiny.

**Comment by jimhester** [comment]
In particular you would have to have the FreeTDS driver installed in wherever you are deploying shiny.

I don't believe this is something we can change in the odbc package, rather it seems a configuration issue. This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
