### ISSUE TITLE
Use RcppCCTZ?

### ISSUE THREAD

**Issue by QuLogic** [r-dbi/odbc#384]
This is not really a bug, but more of a query, whether you may want to use [RcppCCTZ](https://cran.r-project.org/web/packages/RcppCCTZ/) which provides `cctz`, so you don't have to bundle it yourself, and it can be found from a common location.

**Comment by QuLogic** [comment]
Also, slightly related, it looks like the entire `cctz` repo was added to this one. Though the latest version of `odbc` is 1.something, this confusingly means there are v2.something tags. Unfortunately, I don't know that there's any way to fix that other than deleting the `cctz` tags.

**Comment by jimhester** [comment]
I did try using RcppCCTZ initially, but the API it exposed was not quite what we needed for odbc so in the end it was easier to bundle it directly.

I used a git subtree to include the cctz repo, which is why you get the extra tags. I could remove them, but I haven't.
