### ISSUE TITLE
Error in query sent via `dbGetQuery()` causes R session to crash

### ISSUE THREAD

**Issue by tcuongd** [r-dbi/odbc#386]
### Issue Description and Expected Result

I have a feeling this is not an issue with the `odbc` package, but I thought I would raise it anyway in case anyone else is experiencing the same issue. I'm currently using the Snowflake ODBC connector (https://docs.snowflake.com/en/user-guide/odbc-download.html), with odbc 1.2.2, R 4.0.0, and my OS is x86_64-apple-darwin19.4.0 (64-bit). 

When I send a query and fetch the results using `dbGetQuery()`, all works as expected if the query runs on Snowflake with no error. However, if the query has an error on Snowflake, the R session crashes. Here is an example using R from the CLI:

```
> library(DBI)
> dbGetQuery(engine, "select 1;")
  1
1 1
> dbGetQuery(engine, "select 1 2;")

 *** caught segfault ***
address 0x40, cause 'memory not mapped'

Traceback:
 1: new_result(connection@ptr, statement, immediate)
 2: OdbcResult(connection = conn, statement = statement, params = params,     immediate = immediate)
 3: .local(conn, statement, ...)
 4: dbSendQuery(conn, statement, params = params, ...)
 5: dbSendQuery(conn, statement, params = params, ...)
 6: .local(conn, statement, ...)
 7: dbGetQuery(engine, "select 1 2;")
 8: dbGetQuery(engine, "select 1 2;")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:
```

On RStudio, it causes the "R session has crashed" dialog to come up.

We'd expect a query with an error to return the error from the Database, right? If anyone has any ideas about what's going on here that would be greatly appreciated :) 

### Database

Snowflake

### Reproducible Example

I'm not sure how to provide a fully reproducible example, except for what I pasted above ^

**Comment by tonyk7440** [comment]
Hi @tcuongd,

I tried your commands above, hit the error as expected but it did not crash my session, can you try checking your libraries against what I have installed?

```
my_driver <- "{SnowflakeDSIIDriver}"
my_servername <- "XXXX.snowflakecomputing.com"
my_username <- "XXXX"
my_password <- "XXXX"
con_snow <- DBI::dbConnect(odbc::odbc(), 
                           driver = my_driver, 
                           server = my_servername, 
                           UID = my_username, 
                           PWD = my_password)

DBI::dbGetQuery(con_snow, "select 1;")
```
```
  1
1 1
```

```
DBI::dbGetQuery(con_snow, "select 1 2;")
```
```
Error in new_result(connection@ptr, statement, immediate) : 
  nanodbc/nanodbc.cpp:1374: 42000: SQL compilation error:
syntax error line 1 at position 9 unexpected '2'. 
```

My session
```
> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Ireland.1252  LC_CTYPE=English_Ireland.1252    LC_MONETARY=English_Ireland.1252 LC_NUMERIC=C                    
[5] LC_TIME=English_Ireland.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6    packrat_0.5.0   digest_0.6.25   DBI_1.1.0       odbc_1.2.3      evaluate_0.14   rlang_0.4.6     blob_1.2.1      vctrs_0.3.0    
[10] rmarkdown_2.1   tools_4.0.0     bit64_0.9-7     bit_1.1-15.2    hms_0.5.3       xfun_0.13       yaml_2.2.1      compiler_4.0.0  pkgconfig_2.0.3
[19] htmltools_0.4.0 knitr_1.28
```

**Comment by tcuongd** [comment]
@tonyk7440 It looks like the difference is `odbc_1.2.2` vs. `odbc_1.2.3`. I installed 1.2.3 and the second query returned the Database Error instead of crashing R as expected.

**Comment by tonyk7440** [comment]
@tcuongd Great! If all is good you should close this issue
