### ISSUE TITLE
"Restricted data type attribute violation" when using dbWriteTable to write a Date column whose internal representation is "integer"

### ISSUE THREAD

**Issue by snowdensmom** [r-dbi/odbc#388]
### Issue Description and Expected Result
dbWriteTable() throws "Restricted data type attribute violation" when writing a data.frame with a Date column whose internal representation is "integer" instead of "numeric"

### Database
SQL Server 2016

### Reproducible Example
```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "...") # MS SQL server 2016 
a <- data.frame(a_date=structure(0L, class = "Date"))
b <- data.frame(a_date=as.Date("1970-01-01"))
dbWriteTable(con, "TEST_A", a) # error (attribute violation). 
dbWriteTable(con, "TEST_B", b) # works fine.
```
--> Table "TEST_A" is created, but will be empty, and an error will be thrown. Table "TEST_B" is created and filled with data just fine.

This issue is not purely artifical, but occurs when reading .csv files via the latest version of data.table::fread().
Until version 1.12, fread() used to read dates as character. Starting in version 1.13, fread() supports native parsing of %Y-%m-%d. The internal representation of the resulting Date columns will be integer, not numeric, leading to exactly the situation as with the variable "a" in the example above. See: https://github.com/Rdatatable/data.table/blob/master/NEWS.md#potentially-breaking-changes

So, the issue occurs in a non-artificial way when using data.table version 13, using fread() to read the following .csv file:

> "a_date"
> "1970-01-01"

and then trying to use odbc::dbWriteTable() to write the resulting data to our database.

Note: According to the documentation of R's Date class, internal representation of a Date as "integer" is good practice. See: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/Dates, "It is intended that the date should be an integer, but this is not enforced in the internal representation."

<details>

<summary>Session Info</summary>

```r
devtools::session_info()
R version 4.0.2 (2020-06-22)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows Server x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] keyring_1.1.0     data.table_1.13.0 stringr_1.4.0     odbc_1.2.2        logging_0.10-108 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5       assertthat_0.2.1 crayon_1.3.4     R6_2.4.1         DBI_1.1.0        magrittr_1.5     stringi_1.4.6    rlang_0.4.7      rstudioapi_0.11 
[10] blob_1.2.1       generics_0.0.2   vctrs_0.3.2      tools_4.0.2      bit64_4.0.5      tinytex_0.24     bit_4.0.4        hms_0.5.3        xfun_0.15       
[19] compiler_4.0.2   pkgconfig_2.0.3 
```
</details>

**Comment by jimhester** [comment]
I agree with the documentation that dates should contain whole number values, but in practice Date objects internally in base R are always stored and manipulated as double vectors (`REALSXP`).

data.table should not be using `INTSXP` for these objects.

**Comment by jimhester** [comment]
It was fairly straightforward to support these `IDate` objects from data.table, so odbc now does so.
