### ISSUE TITLE
Provide some basic check of driver config?

### ISSUE THREAD

**Issue by hadley** [r-dbi/odbc#393]
Is there some method you can run against a driver that would error if the path is incorrect? This would be useful for debugging driver install.

**Comment by jimhester** [comment]
I don't know of anything really, but I agree it would be useful.

**Comment by simonpcouch** [comment]
Related to #680, but not closed by that PR, I think.

**Comment by hadley** [comment]
IMO I think we can close this now — in my experience you do get a pretty clear error if the path isn't set correctly.
