### ISSUE TITLE
Invalid SQL data type error when viewing table columns in RStudio Connections pane

### ISSUE THREAD

**Issue by crazybilly** [r-dbi/odbc#405]
### Issue Description and Expected Result
I'm using odbc on a Windows 10 machine to connect R to our Oracle datawarehouse.

I can connect and use dplyr in the console just fine. However, if I use the RStudio Connections pane, I'm able to see all the schemas and tables, but when I try to expand a table to see the columns in that table, I get an error.

First, RStudio pops up a dialog box saying "R code execution error"

![image](https://user-images.githubusercontent.com/61009/98688506-88798600-2330-11eb-821a-608e6d21e34b.png)

Then, in the console, I see more details about the error, namely:

```
Error in connection_sql_columns(connection@ptr, table_name = validateObjectName(table,  : 
nanodbc/nanodbc.cpp:2593: HY004: [Oracle][ODBC]Invalid SQL data type <-25>. 
```

My connection string looks like this:
```
library(DBI)
con <- DBI::dbConnect(odbc::odbc(), "MY_ODBC_CONNECTION_NAME", uid = Sys.getenv("DB_USER"), pwd = Sys.getenv("DB_PWD"), timeout = 10)
```
As far as I can tell, this happens on every table (mostly materialized views, but some real tables as well) that I try. 

### Database
Oracle Database 12c Enterprise Edition Release 12.2.0.1.0

**Comment by detule** [comment]
Fixed in https://github.com/r-dbi/odbc/pull/577
