### ISSUE TITLE
RStudio on macOS Catalina fails to connect to mysql and postgres db

### ISSUE THREAD

**Issue by alexdiazortiz** [r-dbi/odbc#411]
### Issue Description and Expected Result
I have followed the installation procedure described in the 

https://github.com/r-dbi/odbc/#macos

 (using brew, unixODBC, mysql, postgres) on macOS catalina 10.15.7 . No installation errors reported. 

```
odbcinst -j
unixODBC 2.3.9
DRIVERS............: /usr/local/etc/odbcinst.ini
SYSTEM DATA SOURCES: /usr/local/etc/odbc.ini
FILE DATA SOURCES..: /usr/local/etc/ODBCDataSources
USER DATA SOURCES..: /Users/myuser/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

The `odbcinst.in` file contents

```
cat /usr/local/etc/odbcinst.ini

[ODBC Driver for MySQL]
Driver=/usr/local/lib/libmysqlclient.dylib

[ODBC Driver for PostgreSQL]
Driver=/usr/local/lib/psqlodbcw.so
```
and the corresponding  `odbc.in` file  

```
cat ~/.odbc.ini
[MyDSN]
Driver= ODBC Driver for MySQL
Database= database_name
Servername= mysql-host-site.com
UserName= myusername
Password= mypasswd
Port= 3306
```

Check-list 
* Access to the mysql db was confirmed for the credentials using mysql workbench v 8.0.2
* Idem for a postgres db and dbeaver
* mysql ver 8.0.22 for osx10.15 on x86_64 (Homebrew)
* R version 4.0.3 (2020-10-10)
* RStudio version 1.3.1093

Attempting to connect to mysql database using RStudio 

```{r}
library(odbc)
library(DBI)
sort(unique(odbcListDrivers()[[1]]))
```
[1] "ODBC Driver for MySQL"      "ODBC Driver for PostgreSQL"

```{r}
con <- DBI::dbConnect(odbc::odbc(),
                      Driver   = "ODBC Driver for MySQL",
                      UID      = "myusername",
                      PWD    = "mypasswd",
                      Server   = "mysql-host-site.com",
                      Port     = 3306)
```
throws the following error

```
Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Driver's SQLAllocHandle on SQL_HANDLE_HENV failed
```

For good measure, I tried to connect to a postgres db

```{r}
con <- DBI::dbConnect(odbc::odbc(),
  driver   = "ODBC Driver for PostgreSQL",
  database = "postgres",
  uid      = "myusername",
  pwd      = "mypasswd",
  host     = "mypostgres-host-site.com",
  port     = 5432)
```

that gives this error message

```
Error: nanodbc/nanodbc.cpp:1021: 00000: could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

as noted above, I was able to connect to this postgres db using dbeaver.

**Comment by alexdiazortiz** [comment]
It seems that installing `mysql` with homebrew as indicated in

https://github.com/r-dbi/odbc/#macos

does not install any MySQL OBDC drivers.

I wrongly assumed that `libmysqlclient.dylib` contained the drivers, since its the only library that looked as a good candidate.

This issue is not related to the packages `DBI/odbc` but to the installation of the MySQL libraries.

**Comment by danielset** [comment]
@alexdiazortiz How did you solve your issue? Just ran into the same problem ...
