### ISSUE TITLE
odbc may return garbaged letters for varchar type when driver changes encoding

### ISSUE THREAD

**Issue by shrektan** [r-dbi/odbc#437]
## Issue Description and Expected Result

odbc returns garbaged letters for the following SQL:  `"select '你好' as '中文'"` while RODBC works expectedly

### Database

- DB: SQL Server 2017
- Driver: ODBC Driver 17 for SQL Server

### Set up the DB

```bash
docker pull mcr.microsoft.com/mssql/server:2017-latest

docker network create mynetwork

docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=AaEeF-A123" \
   --network mynetwork \
   -e "MSSQL_COLLATION=Chinese_PRC_Stroke_CI_AI_KS_WS" \
   -p 1433:1433 --name sql1 -h sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2017-latest
```

### Set up the Client

```bash
docker pull shrektan/r-production
docker run -it --rm  --network mynetwork shrektan/r-production R

```

#### odbc returns string with garbage letters

```r
conn1 <- DBI::dbConnect( 
      odbc::odbc(), 
      server = 'sql1',
      uid = 'SA', pwd = 'AaEeF-A123', 
      driver = 'ODBC Driver 17 for SQL Server', port = 1433)    
DBI::dbGetQuery(conn1, "select '你好' as '中文'")
#    中文
# 1 你\xe5
```

#### RODBC works correctly

```r
if (!require("RODBC")) install.packages("RODBC")
conn2 <- RODBC::odbcDriverConnect(connection="uid=SA;pwd=AaEeF-A123;server=sql1;driver=ODBC Driver 17 for SQL Server;")
RODBC::sqlQuery(conn2, "select '你好' as '中文'")
#  中文
# 1 你好
```

**Comment by shrektan** [comment]
Note, explicitly casting the string literal works, so it may be related to the data-type conversion.

```r
> DBI::dbGetQuery(conn1, "select cast('你好' as nvarchar(50)) as '中文'")
  中文
1 你好
```

**Comment by shrektan** [comment]
After three hours investigation, my conclusions are:

1. The **cause** of this issue: the driver changes the encoding of the Database, leading to the case that the SQL Column Size of the varchar type returned from DB doesn't equal to the string's byte length, after re-encoded.
2. The **solution** of this issue: (I would check RODBC's implementation later when I have more time) 
    - If you can set the encoding of the driver (e.g., FreeTDS allows you to set via Client Charset, Oracle via an Env Variable), that would be perfect, please do that
    - For those drivers can't (Microsoft ODBC driver), odbc may should add a new parameter (e.g., `varchar_len_mult`?) to intentionally multiply increase the size of the varchar type. In my case, since the database use double bytes and UTF-8 uses three bytes, a 1.5 factor will be enough, without significantly impact the performance.

**Comment by djhurio** [comment]
Thank you @shrektan for digging this. Casting to longer varchar is a good temporal solution for me now.

BTW, it looks this is Linux only related problem. I can not reproduce it on Windows. I am reading varchars encoded in "ISO-8859-13" from a MS SQL server. As you know `odbc` always returns "UTF-8". On Linux I get UTF-8 encoded text which is truncated if there are more bytes then varchar lengths (as you have described). On Windows I get UTF-8 encoded text without any loss of bytes.

I am using the `ODBC Driver 17 for SQL Server driver` both on Linux and Windows.

**Comment by shrektan** [comment]
It's probably that the MS odbc driver returns the local encoding on Windows. I mean, you didn't set the encoding arg of `odbc` to UTF-8 on Windows and the encoding of your Windows Computer that runs R is "ISO-8859-13", correct?  

FreeTDS did a better job on Encoding issues but it's buggy when writing data  (See #436 )

**Comment by djhurio** [comment]
Yes, you are right. "ISO-8859-13" was the local encoding on this Windows machine.

**Comment by detule** [comment]
Should be resolved, I think, with https://github.com/r-dbi/odbc/pull/553

Let me know if not.
