### ISSUE TITLE
Help installing with clang on RHEL7

### ISSUE THREAD

**Issue by rnorberg** [r-dbi/odbc#445]
I'd really like to install (from source) the latest version of `odbc`, but at work we're on RedHat 7 so our version of `gcc` is rather old (4.8.5) and predates full C++11 support. This has been well documented, for eaxmple [here](https://support.rstudio.com/hc/en-us/articles/360052331933-ODBC-v1-2-3-on-CentOS-RHEL-6-7-). Unfortunately, our Linux admins are strongly discouraging us from using RedHat Software Collections, so the solution in that article doesn't work for us.

While they discourage the use of RedHat Software Collections, our Linux admins are fine with us `yum install`'ing packages from EPEL. I noticed that `clang v3.4.2` is available for RHEL7 from EPEL, and according to [clang.llvm.org/cxx_status](https://clang.llvm.org/cxx_status), "Clang 3.3 and later implement all of the ISO C++ 2011 standard." So I `yum install`'ed `clang` and added `CXX11 = clang++` to my `~/.R/Makevars` file. 
  
After doing this, I got an error about `'codecvt' file not found`. Some Googling led me to understand that this is a C++11 header missing from `gcc`'s standard library, so I `yum install`'ed `libcxx-devel` (also available in EPEL) and added `CXX11FLAGS += -stdlib=libc++` to my `~/.R/Makevars` file. Now everything seems to compile just fine, but `install.packages` throws the following error upon trying to load the package:

```
Error: unable to load shared object '/mnt/r/site-library/4.0/00LOCK-odbc/00new/odbc/libs/odbc.so':
  /mnt/r/site-library/4.0/00LOCK-odbc/00new/odbc/libs/odbc.so: undefined symbol: _ZTINSt3_113basic_ostreamIcNS_11char_traitsIcEEEE
```

I don't really know my way around C++ compilation, so could someone please point me in the right direction to getting this to compile with `clang`?

**Recap:**
* Using R 4.0.2 on RHEL7
* `yum install clang clang-devel libcxx libcxx-devel` to get a C++11 compliant compiler
* `~/.R/Makevars` contains:
```
CXX11 = clang++
CXX11FLAGS += -stdlib=libc++
```
* Error message:
```
Error: unable to load shared object '/mnt/r/site-library/4.0/00LOCK-odbc/00new/odbc/libs/odbc.so':
  /mnt/r/site-library/4.0/00LOCK-odbc/00new/odbc/libs/odbc.so: undefined symbol: _ZTINSt3_113basic_ostreamIcNS_11char_traitsIcEEEE
```

**Comment by hadley** [comment]
I'm closing this in sad acknowledgement that we don't have the resources to help with this 😞
