### ISSUE TITLE
Connection to Redshift behavior change from 1.3.0 to 1.3.1

### ISSUE THREAD

**Issue by sdadsetan-concert** [r-dbi/odbc#459]
### Issue Description and Expected Result
Upgraded from odbc 1.3.0 to 1.3.1 and output after connection to Redshift has changed.
With `1.3.0`, running the following in RStudio (1.4.1106) yields a list of all schemas.
```
library(DBI)
con <- dbConnect(odbc::odbc(), "AWS Redshift (C3 Dev)", timeout = 10)
```
With `1.3.1`, the same command just lists the name of the database in the odbc.ini config.

### Database
Redshift 8.0.2

### Reproducible Example
Same as above

<details>
<summary>Session Info</summary>

─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 4.0.4 (2021-02-15)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2021-06-15                  

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 bit           4.0.4   2020-08-04 [1] CRAN (R 4.0.2)
 bit64         4.0.5   2020-08-30 [1] CRAN (R 4.0.2)
 blob          1.2.1   2020-01-20 [1] CRAN (R 4.0.2)
 cachem        1.0.4   2021-02-13 [1] CRAN (R 4.0.2)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.2)
 cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.2)
 crayon        1.4.1   2021-02-08 [1] CRAN (R 4.0.2)
 DBI         * 1.1.1   2021-01-15 [1] CRAN (R 4.0.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 devtools    * 2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.0.2)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 hms           1.0.0   2021-01-13 [1] CRAN (R 4.0.2)
 lifecycle     1.0.0   2021-02-15 [1] CRAN (R 4.0.2)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.2)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.0.2)
 odbc          1.3.0   2020-10-27 [1] CRAN (R 4.0.4)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.2)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.2)
 pkgload       1.2.0   2021-02-23 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.2)
 ps            1.6.0   2021-02-28 [1] CRAN (R 4.0.4)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.2)
 Rcpp          1.0.6   2021-01-15 [1] CRAN (R 4.0.2)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.2)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.2)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 testthat      3.0.2   2021-02-14 [1] CRAN (R 4.0.2)
 tinytex       0.30    2021-03-04 [1] CRAN (R 4.0.4)
 usethis     * 2.0.1   2021-02-10 [1] CRAN (R 4.0.2)
 vctrs         0.3.6   2020-12-17 [1] CRAN (R 4.0.2)
 withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.2)
 xfun          0.22    2021-03-11 [1] CRAN (R 4.0.2)

[1] /Library/Frameworks/R.framework/Versions/4.0/Resources/library</details>

**Comment by hadley** [comment]
What do you mean by "yields a list of all schemas"? It looks like that code just creates a connection.

**Comment by sdadsetan-concert** [comment]
Hi Hadley,

I've posted two screen recordings for you to hopefully clarify a bit more. 

One recording shows how `odbc 1.3.0` behaves in Workbench when connecting. It connects to the database ("concerto_dev") and immediately lists all the available schemas. The second recording shows `obdc 1.3.3` where when it connects, it displays at the "database" level (ie, "concerto_dev") and doesn't list the schemas inside. 

https://user-images.githubusercontent.com/79531025/234082443-cb9e518b-c0ca-49a1-94e5-2b78ddced71b.mov
https://user-images.githubusercontent.com/79531025/234082450-eafa2d62-5ae7-46fb-a183-116dc6952fe0.mov

**Comment by hadley** [comment]
Those don't seem to play for me. But are you talking about the connections pane in RStudio?

**Comment by sdadsetan-concert** [comment]
Yes. I've taken some screenshots to show what it looks like "post-connection" that hopefully show what I'm referring to.

<img width="601" alt="Screenshot 2023-04-24 at 12 52 43 PM" src="https://user-images.githubusercontent.com/79531025/234101690-4966ff34-a626-4808-9d0a-0947c8d83585.png">
<img width="602" alt="Screenshot 2023-04-24 at 12 53 18 PM" src="https://user-images.githubusercontent.com/79531025/234101703-196c4c51-96dc-4195-9ddf-4ef467c4afb4.png">

**Comment by sdadsetan-concert** [comment]
I was playing around with this a bit more and found that the db connection `> 1.3.0` has a `catalog` property that causes this difference. We've been able to change our code to accommodate and got this working. Appreciate everyone's time.
