### ISSUE TITLE
Issue writing data frame with more than 60K rows to Sybase IQ database 

### ISSUE THREAD

**Issue by jgarrigan** [r-dbi/odbc#463]
Database type: Sybase IQ 16

Issue: I have a data frame of  2397264 rows and 4 columns and I am trying to write to a table in my Sybase IQ database. 

I am able to write ~ 60K rows before I receive the following error: 

Error in result_insert_dataframe(rs@ptr, values, batch_rows) : 
  nanodbc/nanodbc.cpp:2241: HY024: [Sybase][ODBC Driver]Invalid attribute value

I'm using a DSN to connect to my database and my connection properties looks as follows:

```
# CREATE A CONNECTION TO THE DATABASE
db_conn <- dbConnect(odbc(), 
                         dsn = "dbName")
```
# WRITE DATA OUT TO DB
dbWriteTable(conn = db_conn, 
             name = "AWP_WAC_DATA", 
             value = AWP_WAC_DATA,
             overwrite = TRUE,
             row.names = FALSE)

My data frame has the following structure
```
str(AWP_WAC_DATA)
tibble [2,397,264 x 4] (S3: tbl_df/tbl/data.frame)
 $ NDC               : Factor w/ 126129 levels "00002120001",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DATE_QUARTER      : 'yearqtr' num [1:2397264] 2017 Q1 2017 Q2 2017 Q3 2017 Q4 ...
 $ AVG_WAC_UNIT_PRICE: num [1:2397264] 2600 2600 2600 2600 2857 ...
 $ AVG_AWP_UNIT_PRICE: num [1:2397264] 3120 3120 3120 3120 3429 ...

I have the same issue with another smaller dateframe which I was able to chunk into ~60 rows + ~20K rows to write to the database but this AWP_WAC_DATE df is too big and time consuming to chunk. 

Please let me know if there's some logs I can provide to help troubleshoot.

Please note I am not an advanced R user but I think my code is right for writing to the DB.
```

**Comment by detule** [comment]
Hi there.

Curious if you have tried to use the `batch_rows` parameter to `dbWriteTable`, and if that might help with the issue.

I would try values like 100, 1000, 10000, 100000

Cheers

**Comment by jgarrigan** [comment]
@detule Nailed it, thank you!

batch_rows is what I needed, you've saved me a whole world of pain.
