### ISSUE TITLE
R 'ODBC Driver 17 for SQL Server' file not found - from M1 Mac

### ISSUE THREAD

**Issue by realMBP** [r-dbi/odbc#474]
After many hours of troubleshooting I was able to finally connect to SQL Server using Terminal from my M1 Mac. However, I am still getting errors when trying to connect through R Studio. 

I installed homebrew, unixodbc and ODBC Driver 17 for SQL Server (per MS the driver is compatible with M1s ARM64 starting from version 17.8). I also installed openssl@1.1 since openssl@3 doesn't seem to work. I was then able to connect to the SQL Server via terminal:

`isql -v -k "Driver=ODBC Driver 17 for SQL Server;Server=<myserverip>;UID=<username>;PWD=<password>;database=<dbname>"`

CONNECTED!

However, when attempting the same connection through R Studio, it's not recognizing the driver. 

```
dbConnect(odbc(),
                    Driver= "ODBC Driver 17 for SQL Server",
                    Server="<myserverip>",
                    Port= 1433,
                    Database="<dbname>",
                    UID= <username>,
                    PWD= keyring::key_get("DBcredentials", keyring::key_list("DBcredentials")[1,2]))

Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib 'ODBC Driver 17 for SQL Server' : file not found 
```

Alternatively, attempting to connect using the DSN through Terminal is also successful but not through RStudio:

`isql -v SQLServer <myusername> <mypassword>`

CONNECTED!

But not from R Studio:

```
dbConnect(odbc(),
                    DSN = "SQLServer",
                    UID= <myusername>,
                    PWD= <mypassword>)
Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Data source name not found and no default driver specified 
```

Pulling the file paths I get this:

```
itisme@realMBP ~ % odbcinst -j
unixODBC 2.3.9
DRIVERS............: /opt/homebrew/etc//odbcinst.ini
SYSTEM DATA SOURCES: /opt/homebrew/etc//odbc.ini
FILE DATA SOURCES..: /opt/homebrew/etc//ODBCDataSources
USER DATA SOURCES..: /opt/homebrew/etc/odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

I added these symlinks in case RStudio needs them:

/etc/odbcinst.ini
/etc/odbc.ini

and

/User/itisme/odbcinst.ini
/User/itisme/odbc.ini

all pointing to their /opt/homebrew/opt/ corresponding files.

The content of my odbcinst.ini file at /opt/homebrew/etc/odbcinst.ini is:

```
[ODBC Driver 17 for SQL Server]
Description=Microsoft ODBC Driver 17 for SQL Server
Driver=/opt/homebrew/lib/libmsodbcsql.17.dylib
UsageCount=2
```

The content of my odbc.ini file /opt/homebrew/etc/odbc.ini is:

```
# [DSN name]
[SQLServer]  
Driver = ODBC Driver 17 for SQL Server
# Server = [protocol:]server[,port]
Server = tcp:<myserverip>,1433
#
# Note:
# Port is not a valid keyword in the odbc.ini file
# for the Microsoft ODBC driver on Linux or macOS
#
```

Is there anything else I need to do to connect to the driver from RStudio? Has anyone been able to connect to SQL Server from R Studio running native ARM64 M1s?

**Comment by realMBP** [comment]
I was able to resolve this by creating 2 additional symlinks:

`ln -s /opt/homebrew/etc/odbc.ini /usr/local/etc/odbc.ini`
`ln -s /opt/homebrew/etc/odbcinst.ini /usr/local/etc/odbcinst.ini`

Now RStudio recognizes the drivers though it is still unable to connect. Now it throws this error:

`[Driver Manager]Can't open lib '/opt/homebrew/lib/libmsodbcsql.17.dylib' : file not found` 

But the error is now similar to another case I found [here](https://github.com/microsoft/homebrew-mssql-release/issues/53) but the only solution offered is running an x86 emulator.

**Comment by realMBP** [comment]
Resolved the last part by uninstalling R and RStudio and reinstalling them using homebrew. I had originally downloaded R/RStudio from the web and then installed homebrew to add unixodbc and the odbc driver so R and unixodbc were in different directories. R, unixodbc and the driver all need to be in the same homebrew directory.

**Comment by jwhendy** [comment]
Sorry, I know this is a necro post, but thought I'd add breadcrumbs, as this is still in the top hits for the odbc driver not being found. Instead of symlinking, I found in [the Rstudio docs](https://solutions.posit.co/connections/db/best-practices/drivers/) that one can just add the path to .Renviron.

Adding this resolved the issue for me.
```
# in .Renviron
ODBCSYSINI=/opt/homebrew/etc
```
