### ISSUE TITLE
MS SQL Server: Wrong encoding running inside RStudio, correct while knitting

### ISSUE THREAD

**Issue by panporter** [r-dbi/odbc#489]
### Issue Description and Expected Result
dbConnect() establishes a connection to SQL Server with a wrong encoding. But only running code inside RStudio. When knitting the RMarkdown document everything works as expected.

I'd expect no difference whether code is run via IDE or by knitr.

### Database
Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64) 

### Reproducible Example
```
library(DBI)
library(odbc)
 
sessioninfo::os_name()
#> [1] "Windows 10 x64 (build 19044)"
 
#RStudio.Version()$long_version
# [1] "2021.09.2+382"
 
version
#>                _                          
#> platform       x86_64-w64-mingw32         
#> arch           x86_64                      
#> os             mingw32                    
#> system         x86_64, mingw32            
#> status                                    
#> major          4                          
#> minor          1.2                        
#> year           2021                       
#> month          11                         
#> day            01                         
#> svn rev        81115                      
#> language       R                           
#> version.string R version 4.1.2 (2021-11-01)
#> nickname       Bird Hippie
getOption("encoding")
#> [1] "native.enc"
localeToCharset()
#> [1] "ISO8859-1"
Sys.getlocale()
#> [1] "LC_COLLATE=German_Germany.1252;LC_CTYPE=German_Germany.1252;LC_MONETARY=German_Germany.1252;LC_NUMERIC=C;LC_TIME=German_Germany.1252"

# This should be correct according to all the gathered information, but works
# only while knitting, not executing chunk in RStudio
con <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding="latin1")

# This is a nasty workaround
#con <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding=ifelse(isTRUE(getOption('knitr.in.progress')), "latin1", "UTF-8"))

sql_server_collation <- dbGetQuery(con, "SELECT os_language_version,
       SERVERPROPERTY('LCID') AS 'Instance-LCID',
       SERVERPROPERTY('Collation') AS 'Instance-Collation'
FROM   sys.dm_os_windows_info")

sql_server_collation
#>   os_language_version Instance-LCID   Instance-Collation
#> 1                1033          1033 Latin1_General_CI_AS

test <- dbGetQuery(con, "SELECT 'Tö' as Tü")

test
#>   Tü
#> 1 Tö
```

test shows the result as it ought to be. It's the result after knitting.

The source file itself is UTF-8 encoded.
odbc-Version 1.3.3
DBI 1.1.2

When running this very code as a chunk in RStudio, I get the following error:

```
Error: nanodbc/nanodbc.cpp:1655: 42000: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near 'ï¿½  [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Statement(s) could not be prepared.

<SQL> 'SELECT 'Tö' as Tü'

Failed to execute SQL chunk
```

When I switch to *encoding="UTF-8"* running the chunk in RStudio the query works, but the result is distorted (wrong encoding):

```
    TÃ¼
1 T<c3>
```

When I switch to *encoding="UTF-8"* and *knitting* the document the query *doesn't work*, I again receive the "Error: nanodbc/nanodbc.cpp:1655: 42000" because the query is sent out UTF-8-encoded instead of Latin1.

I'm very puzzled and can't track it down where the difference comes from and if it might be a bug in RStudio. But how can encodings be mixed up when all the environment variables appear to be the same?

Thank you very much. I'd be glad to help doing further tests.

**Comment by krlmlr** [comment]
Thanks. Does this work better with R 4.2.1?

**Comment by panporter** [comment]
Sorry for the late reply. I had to skip R 4.2.1 and I am now on **R 4.2.2 (2022-10-31 ucrt)**.

At least I get the same results now both knitting and executing via RStudio.

Unfortunately now I get

> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
> 
> <SQL> 'SELECT 'T�' as T�'
> 

for Latin1 (`con <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding="latin1")`).

For UTF-8 (`con <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding="UTF-8")`) it eats up characters. I get

```r
dbGetQuery(con, "SELECT 'Tö' as Tü")
#>   Tü
#> 1 T
```

The last ö is indeed missing from the reply.

Is there some string length issue?
Each Umlaut (or other non-ASCII character) eats up one Byte (_not_ character) at the end of the reply:

```r
dbGetQuery(con, "SELECT 'Täöüäöü123456' as Tü")
#>   Tü
#> 1 Täöüäöü

dbGetQuery(con, "SELECT 'Täöüäöü' as Tü")
#>   Tü
#> 1 Täöü

```

**Comment by krlmlr** [comment]
Weird, I saw a very similar problem with an Oracle database, CC @moodymudskipper.

@detule: Any idea?

**Comment by detule** [comment]
Hi - 

I've been meaning to respond to this/similar issues - short version is that  UTF support can be better in the ODBC spec; for best results UTF data should be stored in columns that have a wide storage type ( for example, `NVARCHAR`, or `TEXT` ).

When you write
```
dbGetQuery(con, "SELECT 'Tö' as COL")
```
the field is, by default, VARCHAR.  For this to be parsed properly, you would need to write something like
```
dbGetQuery(con, "SELECT CAST('Tö' AS NVARCHAR) as COL")
```
Some other auxiliary notes:
* We are more exposed to this issue than other odbc interfaces, because of some of the aggressive buffer binding / optimization that we inherit from `nanodbc`.  As part of this optimization we need to know, ahead of time the storage size of each column.  If there are wide characters stored in a column with declared type VARCHAR, the back-end and the driver won't correctly communicate that storage size to each other, and as a result, we will most allocate a buffer that is of insufficient length to store at least some of the data in the column.
* Starting with the 2019 vintage, [Microsoft has expanded UTF support in SQL Server ](https://techcommunity.microsoft.com/t5/sql-server-blog/introducing-utf-8-support-for-sql-server/ba-p/734928)- trying to tackle, I think, this very issue ( storing wide characters in VAR/CHAR columns ).  To benefit from this, the collation of the database has to be one of the ones that end in a "_UTF8" suffix, for example: `Latin1_General_100_CS_AI_SC_UTF8`.  With that collation specified, I think your original query should return the expected answer.

**Comment by krlmlr** [comment]
Thanks. Can we patch nanodbc to use a buffer of size x4 of the expected size?

https://stackoverflow.com/a/10229225/946850

**Comment by panporter** [comment]
Thanks for the reply and all your work.

Meanwhile I did some additional tests.

Needless to say that all queries work inside SQL Management Studio.

I created a test table with

```sql
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[test](
       [TüChar] [char](10) NULL,
       [TüNChar] [nchar](10) NULL
) ON [PRIMARY]
GO
```

Resulting in

| TüChar | TüNChar |
| ----------|------------|
| Täöü123456 | Täöü123456 |

Document is UTF-8. Database is Latin1.

For the use of the N literal prefix:

> Prefix a Unicode character string constants with the letter N to signal UCS-2 or UTF-16 input, depending on whether an SC collation is used or not. Without the N prefix, the string is converted to the default code page of the database that may not recognize certain characters.
https://learn.microsoft.com/en-us/sql/t-sql/data-types/nchar-and-nvarchar-transact-sql?view=sql-server-ver16

``` r
conUTF8 <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding="UTF-8")
 
# truncated
dbGetQuery(conUTF8, "SELECT 'Täöü123456'")
#>         
#> 1 Täöü123
 
# correct
dbGetQuery(conUTF8, "SELECT N'Täöü123456'")
#>            
#> 1 Täöü123456
 
# CHAR column is truncated, NCHAR column is correct
dbGetQuery(conUTF8, "SELECT * FROM test")
#>    TüChar    TüNChar
#> 1 Täöü123 Täöü123456
 
# queries are sent correctly, CHAR column is always truncated
dbGetQuery(conUTF8, "SELECT * FROM test WHERE TüChar = 'Täöü123456'")
#>    TüChar    TüNChar
#> 1 Täöü123 Täöü123456
dbGetQuery(conUTF8, "SELECT * FROM test WHERE TüChar = N'Täöü123456'")
#>    TüChar    TüNChar
#> 1 Täöü123 Täöü123456
dbGetQuery(conUTF8, "SELECT * FROM test WHERE TüNChar = 'Täöü123456'")
#>    TüChar    TüNChar
#> 1 Täöü123 Täöü123456
dbGetQuery(conUTF8, "SELECT * FROM test WHERE TüNChar = N'Täöü123456'")
#>    TüChar    TüNChar
#> 1 Täöü123 Täöü123456
 
 
# truncated
dbGetQuery(conUTF8, "SELECT IIF(TüChar IS NULL, '', 'äöü789') FROM test")
#>     
#> 1 äöü
 
# correct
dbGetQuery(conUTF8, "SELECT IIF(TüChar IS NULL, '', N'äöü789') FROM test")
#>        
#> 1 äöü789
 
# interestingly error messages are truncated as well
dbGetQuery(conUTF8, "SELECT * FROM test WHERE 'Täöüäöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'Täöüäöü12  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE 'Täöüäöü123456''
 
 
conLatin1 <- dbConnect(odbc::odbc(), "SQLServerODBC", encoding="latin1")
 
# wrong encoding
dbGetQuery(conLatin1, "SELECT 'Täöü123456'")
#>            
#> 1 T???123456
 
# wrong encoding
dbGetQuery(conLatin1, "SELECT N'Täöü123456'")
#>            
#> 1 T���123456
 
# CHAR column has wrong encoding and is truncated, NCHAR column is correct
dbGetQuery(conLatin1, "SELECT * FROM test")
#>       TüChar    TüNChar
#> 1 TÃ¤Ã¶Ã¼123 Täöü123456
 
# all queries encounter errors (wrongly encoded error messages)
dbGetQuery(conLatin1, "SELECT * FROM test WHERE TüChar = 'Täöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE T<fc>Char = 'T<e4><f6><fc>123456''
dbGetQuery(conLatin1, "SELECT * FROM test WHERE TüChar = N'Täöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE T<fc>Char = N'T<e4><f6><fc>123456''
dbGetQuery(conLatin1, "SELECT * FROM test WHERE TüNChar = 'Täöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE T<fc>NChar = 'T<e4><f6><fc>123456''
dbGetQuery(conLatin1, "SELECT * FROM test WHERE TüNChar = N'Täöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE T<fc>NChar = N'T<e4><f6><fc>123456''
 
 
# error
dbGetQuery(conLatin1, "SELECT IIF(TüChar IS NULL, '', 'äöü789') FROM test")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT IIF(T<fc>Char IS NULL, '', '<e4><f6><fc>789') FROM test'
 
# error
dbGetQuery(conLatin1, "SELECT IIF(TüChar IS NULL, '', N'äöü789') FROM test")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '�  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT IIF(T<fc>Char IS NULL, '', N'<e4><f6><fc>789') FROM test'
 
# wrongly encoded error message
dbGetQuery(conLatin1, "SELECT * FROM test WHERE 'Täöüäöü123456'")
#> Error: nanodbc/nanodbc.cpp:1752: 42000: [Microsoft][ODBC SQL Server Driver][SQL Server]An expression of non-boolean type specified in a context where a condition is expected, near 'T����<ef><bf>  [Microsoft][ODBC SQL Server Driver][SQL Server]Statement(s) could not be prepared.
#> <SQL> 'SELECT * FROM test WHERE 'T<e4><f6><fc><e4><f6><fc>123456''
```
 
So I think I'd go for the N-prefix and CAST()s for now. (Remembering that when copying from SQL Management Studio.)


Additionally, in contrast to my example above (document: UTF-8, database: Latin1, the connection works only with encoding = "UTF-8"), the documentation states the opposite:

> encoding
> 
>     The text encoding used on the Database. If the database is not using UTF-8 you will need to set the encoding to get accurate re-encoding. See [iconvlist()](https://rdrr.io/r/base/iconv.html) for a complete list of available encodings on your system. Note strings are always returned UTF-8 encoded.
https://r-dbi.github.io/odbc/reference/dbConnect-OdbcDriver-method.html

**Comment by detule** [comment]
Hi guys:

@krlmlr I asked the same question ( over-allocating the buffers ) [upstream in the nanodbc repo](https://github.com/nanodbc/nanodbc/issues/219#issuecomment-1399285674) about a month ago - didn't see much enthusiasm, other than recognition that it's not a straightforward issue.  It could be that the best course of action is to patch here and diverge a bit from upstream, not sure.

@panporter Nice work with the investigation.  Good call on prefix `N` working as well as casting.  Also as you discovered, if you are reading from a table and the column in the table is declared wide, then everything should work as well.  I think we went on a little tangent with the encoding argument to `dbConnect` - i don't think it has much to do with what you are experiencing - the core of the issue is UTF encoded data in VAR/CHAR columns.  While the collation of the database is set to Latin1, you are trying to retrieve UTF encoded characters.

**Comment by detule** [comment]
Should be resolved, I think, with https://github.com/r-dbi/odbc/pull/553

Let me know if not.
