### ISSUE TITLE
AS400/DB2 ODBC Connection Not Working in 4.2.0.

### ISSUE THREAD

**Issue by risk3hr0b** [r-dbi/odbc#492]
### Issue Description and Expected Result
I am unable to create a successful ODBC connection to an IBM iSeries AS400/DB2 data source using R 4.2.0, (same goes for RStudio).  The example below demonstrates that this works in R v4.1.3 but not v4.2.0.

I reported this same [issue](https://community.rstudio.com/t/odbc-is-showing-no-tables-when-i-connect-in-r-studio-continued/135456) in the RStudio community.  One of the users directed me here.

### Database
IBM iSeries AS400/DB2.  Using "iSeries Access ODBC Driver".

### Reproducible Example

Using 4.1.3:
> library(DBI)
> library(odbc)
> con <- DBI::dbConnect(odbc::odbc(),dsn="dsn",UID="uid",PWD="pwd")
> dbListTables(con)
   [1] "ACAASMNP04"            "ACAASM02"              "ACAASM04"             
   [4] "ACAASM05"              "ACAASM06"              "ACAASM07"             
   [7] "ACAASM08"              "ACAASM10"              "ACAASM11"             
  [10] "ACAASM12"              "ACAGENQC01"            "ACAGQC01" 

Using 4.2.0:

> library(DBI)
> library(odbc)
> con <- DBI::dbConnect(odbc::odbc(),dsn="dsn",UID="uid",PWD="pwd")
> dbListTables(con)
character(0)

I used reprex() on the con statement and it didn't give me an error message:

con <- DBI::dbConnect(odbc::odbc(),dsn="dsn",UID="uid",PWD="pwd")
Created on 2022-04-27 by the [reprex package](https://reprex.tidyverse.org/) (v2.0.1)
![Screenshot 2022-04-27 155209](https://user-images.githubusercontent.com/104508778/165619850-7636e397-cfa0-4235-921b-543882ade35a.jpg)

In the "connections" tab within R Studio, it says that the status is "connected".  Drilling into the connection brings me to another tab that shows "DB2/400 SQL" in the header on the right-side.  Within the pane it says "(No Tables)".  

<summary>Session Info</summary>

> sessionInfo()
R version 4.2.0 (2022-04-22 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

> Matrix products: default

> locale:
> [1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.utf8    

> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
> [1] odbc_1.3.3   DBI_1.1.2    reprex_2.0.1

> loaded via a namespace (and not attached):
 [1] Rcpp_1.0.8.3    rstudioapi_0.13 magrittr_2.0.3  knitr_1.39      hms_1.1.1       bit_4.0.4       R6_2.5.1        rlang_1.0.2     fastmap_1.1.0   fansi_1.0.3    
[11] blob_1.2.3      highr_0.9       tools_4.2.0     xfun_0.30       utf8_1.2.2      cli_3.3.0       clipr_0.8.0     withr_2.5.0     htmltools_0.5.2 ellipsis_0.3.2 
[21] yaml_2.3.5      bit64_4.0.5     digest_0.6.29   tibble_3.1.6    lifecycle_1.0.1 crayon_1.5.1    processx_3.5.3  callr_3.7.0     ps_1.7.0        vctrs_0.4.1    
[31] fs_1.5.2        glue_1.6.2      evaluate_0.15   rmarkdown_2.14  pillar_1.7.0    compiler_4.2.0  pkgconfig_2.0.3

**Comment by detule** [comment]
Hi - 

Can you send the output of ```odbc::dbGetInfo( con )```, both with 4.1.x ( working ), and 4.2.0 ( not working ).

Do you get similar output when you query the ```SYSIBMADM``` catalog for table information?   Something like ```SELECT * FROM SYSIBMADM.ADMINTABINFO``` perhaps.

What is the text encoding used on the database?

**Comment by detule** [comment]
Thanks for reverting.

I don't have a Windows box at hand and can't reproduce the issue; for what is worth, [R] 4.2 + DB2 + ```package:odbc``` seems to be working fine on my Debian box.

Having said that, couple more ideas:
- I *think* you can query the tables catalog from the ```sysibm``` catalog as well; hopefully less permission issues there.   Maybe something like ```dbGetQuery(conn, "SELECT * FROM sysibm.systables")```; if that works interested in if output is same with the two versions of [R].
- Other than that, if possible I would suggest trying to uninstall ```package:odbc``` and after changing to [R] 4.2,  re-installing it.  I think the 4.2 release was a major revision for [R] / Windows including possibly toolchain changes.  Wonder if you are seeing issues related to [R] and the package being built with potentially different toolchains.

Thanks

**Comment by risk3hr0b** [comment]
Installing the newest version of the iSeries Access ODBC Driver solved this issue.
