### ISSUE TITLE
R 4.2: error "the logical functions, && and ||, now give a warning when one of the comparisons has a length greater than one. In future versions, this will become an error."

### ISSUE THREAD

**Issue by datakid** [r-dbi/odbc#496]
Hi Team,

From customer ticket #75793 they note that they are seeing this error when connecting to a database using `DBI::dbConnect(odbc::odbc())`:

> the logical functions, && and ||, now give a warning when one of the comparisons has a length greater than one. In future versions, this will become an error.

https://github.com/r-dbi/odbc/blob/09ef0a23a191b6f1496e9243b91157f83a32d9ae/R/Driver.R#L122-L124

They also note that this warning doesn't appear when `connectionObserver` is NULL.

https://www.r-bloggers.com/2022/04/new-features-in-r-4-2-0/#changes-to-logical-functions

Thanks!

**Comment by detule** [comment]
Should be fixed in https://github.com/r-dbi/odbc/commit/da7b27b6b2768683fb83abf488a4599cd926a1b0

**Comment by datakid** [comment]
Thanks @detule. Is there any chance of a new release in the near future?
