### ISSUE TITLE
Can't open lib '/opt/homebrew/lib/libmsodbcsql.18.dylib' : file not found

### ISSUE THREAD

**Issue by Worville** [r-dbi/odbc#501]
Hi,

I'm trying to connect to a SQL Server database through R using `{odbc}`. Like many others, I'm struggling.

I started by installing the latest version of the Microsoft ODBC driver [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/install-microsoft-odbc-driver-sql-server-macos?view=sql-server-ver15) and followed the troubleshooting to ensure that the appropriate files are symlinked.

I have an M1 MacBook Pro and have got to the point where I can run the appropriate `isql` command in the terminal and return a database connection, but trying the following:

`
con <-  DBI::dbConnect(odbc::odbc(),
                       Driver = "ODBC Driver 18 for SQL Server",
                       server = "server_name",
                       Database = "db",
                       UID = "",
                       PWD = "",
                       port = 1433)
`

Where `ODBC Driver 18 for SQL Server` is pointing to `odbcinst.ini` file which contains:

`[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/homebrew/lib/libmsodbcsql.18.dylib
UsageCount=2`

Results in:

`Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib '/opt/homebrew/lib/libmsodbcsql.18.dylib' : file not found`

The issue seems to be that my R instance can't locate the `libmsodbcsql.18.dylib` file.

Any help would be much appreciated. I've already considered the following links:

- https://github.com/microsoft/homebrew-mssql-release/issues/53
- https://stackoverflow.com/questions/61628762/cant-open-lib-odbc-driver-17-for-sql-server-in-python

**Comment by sharon-wang** [comment]
I've experienced a similar error to `Error: nanodbc/nanodbc.cpp:1021: 00000: [unixODBC][Driver Manager]Can't open lib '/opt/homebrew/lib/libmsodbcsql.18.dylib' : file not found` (same error, but for sqlite) when my R and RStudio was x86_64, but my ODBC was aarch64.

I was able to connect by installing the x86_64 ODBC (i.e. R, RStudio and ODBC are all x86_64) or if I installed the aarch64 versions of R/RStudio/ODBC.

**Comment by L-Groeninger** [comment]
I can confirm @sharon-wang s solution. I followed a procedure that Scott Brenstuhl has provided in [this](https://stackoverflow.com/questions/69275130/how-do-i-install-the-odbc-driver-for-snowflake-successfully-on-an-m1-apple-silic) stackoverflow answer. I also wrote a [short blog post](https://lukas-r.blog/posts/2023-03-05-finally-solving-the-mac-m1-odbc-issue/) about my quest to finding this solution:)
