### ISSUE TITLE
Limit on query for previewing large tables

### ISSUE THREAD

**Issue by MariaSemple** [r-dbi/odbc#502]
### Issue Description and Expected Result
When calling `previewObject` even with a small row limit such as 50, it still takes a long time for the query to return when the table in question is quite large. This can cause an RStudio Session to hang while the query is being performed.

Ideally, if we limit the number of rows in the preview, we could query only that many rows to avoid the hang in the IDE. A `LIMIT` or a `TOP` statement [here](https://github.com/r-dbi/odbc/blob/09ef0a23a191b6f1496e9243b91157f83a32d9ae/R/Viewer.R#L241) would fit that need, but that may not be possible due to database language support differences.

### Database
I'm unsure if this is specific to one database or another, but we have a reproducible example on the IDE team, so I will get the information about that table and its Database and update it here (it has something like 30000 rows).

### Reproducible Example

Specific details about loading the database to come.

1. In an RStudio Session, navigate through the Connections pane until you find a large table. 
2. Preview the table by clicking on it.
3. Even though the preview is limited to 1000 rows, it takes quite some time for the query to return. Restricting the limit to 50 has no impact on performance.

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> output
```
</details>

**Comment by detule** [comment]
Hi - thanks.

Please if you get an opportunity do revert with the back-end, the driver you are using, and size of table ( or maybe view? ).   Also if you can note if there are out-of-the-ordinary characteristics and fields ( VARBINARY / blobs for example ), that would be helpful.

30K rows is not a size where I would have expected an observable delay in fetching 1000 rows from `SELECT *`
