### ISSUE TITLE
Window 10 R 4.2.1 DBI::dbGetQuery Error message text unavailable

### ISSUE THREAD

**Issue by cszpara** [r-dbi/odbc#504]
I am using Window 10. I was using R 4.1.3. I have recently updated to R 4.2.1. I was able to query from our DB2 database by using the following script.

```r
con = DBI::dbConnect(odbc::odbc(),
                       Driver = "iSeries Access ODBC Driver",
                       System = "DBServer",
                       UID = "User",
                       PWD = "Password",
                       Port = 6016)
df = DBI::dbGetQuery(con, sql)
```

R 4.1.3 would correctly query the results. R 4.2.1 produces an Error.

Error: nanodbc/nanodbc.cpp:1655: HY000: [IBM][System i Access ODBC Driver][DB2 for i5/OS] - Error message text unavailable. Message can not be translated successfully. 'SELECT * FROM PRODDTA.F4211 FETCH FIRST 3 ROWS ONLY'

Does any one have a solution to resolve this error?

Additional, i can validate the connection using... 
```r
DBI::dbCanConnect(odbc::odbc(), Driver = "iSeries Access ODBC Driver",
                       System = "DBServer",
                       UID = "User",
                       PWD = "Password",
                       Port = 6016)
```

This produces a TRUE response.

**Comment by krlmlr** [comment]
Thanks. Could you please share the output of `sessioninfo::session_info()` after trying to query the data, for both systems? An easy way to do this is to run `reprex::reprex(si = TRUE)` after copying the code to the clipboard, see https://reprex.tidyverse.org/.

**Comment by cszpara** [comment]
> Thanks. Could you please share the output of `sessioninfo::session_info()` after trying to query the data, for both systems? An easy way to do this is to run `reprex::reprex(si = TRUE)` after copying the code to the clipboard, see https://reprex.tidyverse.org/.

 `sessioninfo::session_info()` 
OUTPUT:
─ Session info ───────────────────
 setting  value
 version  R version 4.2.1 (2022-06-23 ucrt)
 os       Windows 10 x64 (build 19043)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2022-08-09
 rstudio  2022.07.1+554 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages──────────
 package     * version date (UTC) lib source
 bit           4.0.4   2020-08-04 [1] CRAN (R 4.2.1)
 bit64         4.0.5   2020-08-30 [1] CRAN (R 4.2.1)
 blob          1.2.3   2022-04-10 [1] CRAN (R 4.2.1)
 cli           3.3.0   2022-04-25 [1] CRAN (R 4.2.1)
 DBI           1.1.3   2022-06-18 [1] CRAN (R 4.2.1)
 ellipsis      0.3.2   2021-04-29 [1] CRAN (R 4.2.1)
 hms           1.1.1   2021-09-26 [1] CRAN (R 4.2.1)
 lifecycle     1.0.1   2021-09-24 [1] CRAN (R 4.2.1)
 odbc          1.3.3   2021-11-30 [1] CRAN (R 4.2.1)
 pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.2.1)
 Rcpp          1.0.9   2022-07-08 [1] CRAN (R 4.2.1)
 rlang         1.0.4   2022-07-12 [1] CRAN (R 4.2.1)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.2.1)
 sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.2.1)
 vctrs         0.4.1   2022-04-13 [1] CRAN (R 4.2.1)

 [1] C:/Users/MYUSERNAME/AppData/Local/R/win-library/4.2
 [2] C:/Program Files/R/R-4.2.1/library

I'll have to look into the response for
`reprex::reprex(si = TRUE)`
I currently get:
reprex::reprex(si = TRUE)
#> ✖ Install the styler package in order to use `style = TRUE`.
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> CLIPR_ALLOW has not been set, so clipr will not run interactively
#> Error in switch(where, expr = stringify_expression(x_expr), clipboard = ingest_clipboard(), : EXPR must be a length 1 vector

**Comment by cszpara** [comment]
I was able to resolve this issue by re-install the iSeries Access ODBC Driver via the ACS Windows App Pkg English (64bit) download.
https://www.ibm.com/support/pages/odbc-driver-ibm-i-access-client-solutions
