### ISSUE TITLE
Feature request: dbWriteTable with different column names in data.frame and DB table

### ISSUE THREAD

**Issue by aryoda** [r-dbi/odbc#508]
A stackoverflow user asked how to do this and there is only a work-around so far, see:
https://stackoverflow.com/questions/64950837/cant-insert-dataframe-to-sqlite-table-when-column-names-different-dbwritetable

I suggest to support different column names as long as the number, type and order of columns are the same between the `data.frame` and the DB table. In other words: Use the column position instead of the name...

Renaming the names of the `data.frame` itself would be possible of course but has possible side-effects
(eg. if you do not want to change the column names just to upload the data into a DB table but reuse the original names in downstream R code).

**Comment by hadley** [comment]
I think this is out of scope for odbc; we'd need initial support in DBI, and I think that's unlikely to happen due to the complexity of this feature.
