### ISSUE TITLE
Error transitioning from {RODBCDBI} to {odbc}

### ISSUE THREAD

**Issue by dleutnant** [r-dbi/odbc#510]
Hi all, 

I’d like to substitute the {RODBCDBI} package with {odbc}.

While the following three lines of code work, 

``` r
con <- DBI::dbConnect(RODBCDBI::ODBC(), src) # works
s <- DBI::dbGetQuery(con, statement = q) # works
nrow(s) # returns 7546
```
the next ones don‘t and instead return an error.

``` r
con <- DBI::dbConnect(odbc::odbc(), src) #works, I can even see the tables in the RStudio Connection Pane
so <- DBI::dbGetQuery(con, statement = q) # fails

Error: nanodbc/nanodbc.cpp:1649: IM001: [DataForum][ACRON ODBC Driver]Not supported
<SQL> 'SELECT Timestamp, PVShortName, NumData FROM FastInterval4 WHERE (Timestamp>{ts '2022-01-01 00:00:00'})'
```
Does anyone have an idea, which difference between {RODBCDBI} and {odbc} causes this issue? Could someone eventually point me in the direction how to solve this issue? And finally, what does the error with regard to nanodbc mean?

Thanks in advance!

**Comment by r2evans** [comment]
`(Timestamp>{ts '2022-01-01 00:00:00'})` is not valid SQL, and `DBI`/`odbc` do not do any glue-like conversion. Please try

```r
so <- DBI::dbGetQuery(con,
  "SELECT Timestamp, PVShortName, NumData FROM FastInterval4 WHERE (Timestamp > ?)",
  params = list('2022-01-01 00:00:00'))
```

https://solutions.rstudio.com/db/best-practices/run-queries-safely/#parameterized-queries is a good link for bound-parameters.

**Comment by hadley** [comment]
Thanks @r2evans
