### ISSUE TITLE
ORACLE and non ascii characters

### ISSUE THREAD

**Issue by moodymudskipper** [r-dbi/odbc#524]
Using non ascii characters corrupts the strings. see how the "e" is missing in col `c` below. Maybe two incompatible methods are used to measure string length?

```
con <- connect_to_db() # Oracle through ODBC
copy_to(con, data.frame(a=1), "temp_tbl")
DBI::dbGetQuery(con, r"(SELECT "a", 'abcde' AS "b", 'übcde' AS "c" FROM ("temp_tbl"))")
#   a     b    c
# 1 1 abcde übcd
```

I could not test with the ROracle driver since I cannot install it on the client.

I don't have a good workaround.

**Comment by moodymudskipper** [comment]
Here's the definition:

```
connect_to_db <- function(value = "datawarehouse") {
  con_args <- config::get(value = value)
  DBI::dbConnect(
    odbc::odbc(),
    Driver = "Oracle",
    Host   = con_args$host,
    SVC    = con_args$svc,
    UID    = con_args$uid,
    PWD    = con_args$pwd,
    Port   = con_args$port
  )
}
```

**Comment by krlmlr** [comment]
Have you tried using the `encoding` argument?

**Comment by moodymudskipper** [comment]
I was not sure where to find it but finally found it in `?odbc::dbConnect()`. Unfortunately no luck, I get the same result after setting `encoding = "UTF-8"` in `DBI::dbConnect()`

**Comment by krlmlr** [comment]
Does `encoding = "latin1"` or `"latin-1"` work?

What ODBC driver are you using? Can you post the contents of the relevant `odbcinst.ini` or a screenshot of the ODBC configuration on Windows?

What happens if you select `'üäbcd'` or `'ü' || 'abcd'` or `'ü' || 'abcd' || '     '`?

What happens if you try to insert values with umlauts into a table, and try to select those values, perhaps with `... || '     '` ?

**Comment by moodymudskipper** [comment]
With "latin1" I get another wrong output : 

```
#>   a     b     c
#> 1 1 abcde Â¿bcd
```

If I select your suggested values :

```
DBI::dbGetQuery(con, r"(SELECT "a", 'abcde' AS "b", 'übcde' AS "c", 'üäbcd' as "d", 'ü' || 'abcd' as "e", 'ü' || 'abcd' || '     ' as "f" FROM ("temp_tbl2"))")
#>   a     b    c   d    e         f
#> 1 1 abcde übcd üäb üabc üabcd    
```

I'm doing this from RSW so I'm not sure where to find the odbc configuration used by the server

**Comment by detule** [comment]
Related to #437 #369

**Comment by shrektan** [comment]
You should set the environment variable NLS_LANG first. It controls the string encoding that oracle driver returns. The encoding argument should be set to the equivalent value of NLS_LANG.

**Comment by detule** [comment]
Should be resolved, I think, with https://github.com/r-dbi/odbc/pull/553

Let me know if not.

**Comment by krlmlr** [comment]
Thanks! Looking forward to odbc > 1.3.4 on CRAN.
