### ISSUE TITLE
Out-of-catalog preview incorrect

### ISSUE THREAD

**Issue by detule** [r-dbi/odbc#527]
Currently when using the `Connections` pane in the IDE, we incorrectly enumerate objects ( schemas / tables ) in catalogs different than the one we are currently `USE`-ing.  For example, for all catalogs, we show the same schemas ( listing as current catalog ).

<img width="551" alt="incorrect_catalog_enumeration" src="https://user-images.githubusercontent.com/1133993/210821688-9beeee8c-00fe-4beb-b703-e58c45961e74.png">

Saw this with SQL Server, both OEM as well as FreeTDS drivers.

**Comment by hadley** [comment]
Fixed by#692.
