### ISSUE TITLE
Set primary key in `dbWriteTable`

### ISSUE THREAD

**Issue by jpanfil** [r-dbi/odbc#530]
### Issue Description and Expected Result
I'm wondering it's possible to use `dbWriteTable` to create a SQL server table with a primary key. It looks like one possible solution is to use multiple steps where I first create the table with `dbCreateTable` (or perhaps `dbSendQuery`) and then append to that table. Is it possible however to do it in 1 step by specifying the primary key in `dbWriteTable`?

### Database
SQL Server 2019

Example:
```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), driver = 'SQL Server', server = 'server_name', database = 'db_name')
dbWriteTable(con, "iris", iris) # want to set primary key in this step
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package as it requires an extension past the current DBI specification. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by MolBioIX** [comment]
Hi, 
I've had success in using the `field.types` argument to specify the primary key.

```{r}
dbWriteTable(con, "my_table_name", my_df, overwrite = TRUE, 
             field.types = c("my_pk" = "INT NOT NULL PRIMARY KEY AUTO_INCREMENT")
)
```

Hope that helps.
