### ISSUE TITLE
`dbFetch()` fetches only the first result set with Oracle and a vector as params

### ISSUE THREAD

**Issue by ThomasSoeiro** [r-dbi/odbc#537]
### Issue Description and Expected Result
When using odbc to connect to an Oracle database and passing a list of vector(s) as `params`, `dbFetch()` fetches only the first result set.

[`?DBI::dbBind`](https://dbi.r-dbi.org/reference/dbbind) says:
> The elements of the params argument do not need to be scalars, vectors of arbitrary length (including length 0) are supported. For queries, calling `dbFetch()` binding such parameters returns concatenated results, equivalent to binding and fetching for each set of values and connecting via `rbind()`. 

This is also documented in the [Advanced DBI Usage vignette](https://cran.r-project.org/web/packages/DBI/vignettes/DBI-advanced.html).

This works as documented with other interfaces, e.g. RSQLite.

This seems related to the issue #346 which is fixed since odbc 1.3.0.

### Database
```r
dbGetInfo(conn)
# $dbname
# [1] ""
# 
# $dbms.name
# [1] "Oracle"
# 
# $db.version
# [1] "19.00.0000"
# 
# $username
# [1] ""
# 
# $host
# [1] ""
# 
# $port
# [1] ""
# 
# $sourcename
# [1] "xxx" # removed for privacy
# 
# $servername
# [1] "xxx" # removed for privacy
# 
# $drivername
# [1] "RStudio Oracle ODBC Driver"
# 
# $odbc.version
# [1] "03.52"
# 
# $driver.version
# [1] "2.0.2.1002"
# 
# $odbcdriver.version
# [1] "03.80"
# 
# $supports.transactions
# [1] TRUE
# 
# $getdata.extensions.any_column
# [1] TRUE
# 
# $getdata.extensions.any_order
# [1] TRUE
# 
# attr(,"class")
# [1] "Oracle"      "driver_info" "list" 
```

### Reproducible Example
```r
library(DBI)
con <- dbConnect(odbc::odbc(), ...)

# # works as documented with RSQLite
# con <- dbConnect(RSQLite::SQLite(), ":memory:")

dbWriteTable(con, "iris", iris)

query <- "SELECT * FROM \"iris\" WHERE \"Species\" = ?"
q_params <- list(c("setosa", "versicolor"))

res <- dbGetQuery(con, query, params = q_params)

nrow(res)
# [1] 50

# expected results
nrow(iris[iris$Species %in% c("setosa", "versicolor"), ])
# [1] 100
```

<details>
<summary>Session Info</summary>

```r
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.8 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
 [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] DBI_1.0.0

loaded via a namespace (and not attached):
 [1] bit_1.1-14      odbc_1.3.3      compiler_4.1.2  ellipsis_0.3.2  hms_1.1.1       tools_4.1.2     memoise_1.1.0  
 [8] Rcpp_1.0.7      bit64_0.9-7     vctrs_0.3.8     RSQLite_2.1.1   blob_1.2.2      digest_0.6.29   lifecycle_1.0.1
[15] pkgconfig_2.0.2 rlang_0.4.12 
```
</details>

**Comment by detule** [comment]
Hi - thanks for the report.

It seems you are using RStudio's Professional drivers - I don't have access to those but this is what I get when using Oracle's OEM driver.

```
res <- dbGetQuery(conn, query, params = q_params)
Error in result_bind(res@ptr, params, batch_rows) :
  nanodbc/nanodbc.cpp:1753: 00000: [Oracle][ODBC]SELECT with an array of parameters is not supported
```

```
> dbGetInfo(conn)
...
$db.version
[1] "21.00.0000"
$drivername
[1] "SQORA32.DLL"
$driver.version
[1] "21.08.0000"
...
```

I would venture to guess something similar ( the driver does not support parametrized SELECT's) is true for the SIMBA driver you are using as well.

At any rate, i am not an ORACLE user, but from googling I wouldn't take for granted that the back-end itself (oracle) supports multiple result sets in the same manner that SQL Server does.  For example:

https://stackoverflow.com/questions/51249342/multiple-result-sets-with-oracle
https://forums.oracle.com/ords/apexds/post/oralcle-multiple-result-set-1425

**Comment by ThomasSoeiro** [comment]
> It seems you are using RStudio's Professional drivers 
Yes I do.

**Comment by detule** [comment]
Hi Thomas:

Thanks for trying with `ROracle` as well.

This package only reports the feedback that it receives from the database drivers when attempting to execute the statement.  While the OEM driver from Oracle correctly reports the incorrect `SELECT` usage, the one from RStudio does not.

I think if you open a ticket with RStudio they can forward it to the third party vendor that supplies their database drivers.  Once fixed there, `package:odbc` will let that surface to the user.

Thanks again for the report.
