### ISSUE TITLE
NANODBC_THROW_DATABASE_ERROR thrown in ~connection_impl() NANODBC_NOEXCEPT

### ISSUE THREAD

**Issue by alexkowa** [r-dbi/odbc#539]
### 
The connection to our DB2 data base is not closed properly due to yet unknown reasons on the side from the data base, but this leads to a crash of R (Rstudio). Deallocate(); is called after the unsuccsessull call of disconnect(); in ~connection_impl() NANODBC_NOEXCEPT and throws an exception.

A quick fix is to move the deallocate() in a try block, see https://github.com/alexkowa/odbc 

### Database
IBM DB2 v11.1.4.4  FIXPACK 4

> dbDisconnect(conn)
nanodbc/nanodbc.cpp:1136 SQLDisconnect(dbc_)
<-- rc: SQL_ERROR | 
nanodbc/nanodbc.cpp:360 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, 0, 0, &total_bytes)
<-- rc: SQL_SUCCESS_WITH_INFO | 
nanodbc/nanodbc.cpp:378 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, sql_message.data(), (SQLSMALLINT)sql_message.size(), &total_bytes)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:360 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, 0, 0, &total_bytes)
<-- rc: SQL_NO_DATA | 
nanodbc/nanodbc.cpp:725 SQLFreeHandle(handle_type, handle)
<-- rc: SQL_ERROR | 
nanodbc/nanodbc.cpp:360 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, 0, 0, &total_bytes)
<-- rc: SQL_SUCCESS_WITH_INFO | 
nanodbc/nanodbc.cpp:378 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, sql_message.data(), (SQLSMALLINT)sql_message.size(), &total_bytes)
<-- rc: SQL_SUCCESS | 
nanodbc/nanodbc.cpp:360 SQLGetDiagRec(handle_type, handle, (SQLSMALLINT)i, sql_state, &native_error, 0, 0, &total_bytes)
<-- rc: SQL_NO_DATA | 
terminate called after throwing an instance of 'nanodbc::database_error'
  what():  nanodbc/nanodbc.cpp:727: 00000: [unixODBC][Driver Manager]Function sequence error 
Aborted (core dumped)
****

###  Example

```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "RTEST")
x <- dbGetQuery(con, "SELECT * from TAB")
dbDisconnect(conn)
```

**Comment by detule** [comment]
Thanks - your approach looks good.  Can you submit it as a PR?
