### ISSUE TITLE
Performance issue of `dbListTables()` and `dbWriteTable()` with `package:odbc` versus `package:ROracle`

### ISSUE THREAD

**Issue by ThomasSoeiro** [r-dbi/odbc#540]
### Issue Description and Expected Result
`dbListTables()` and `dbWriteTable()` (and maybe other functions) are excessively longer when connected to an Oracle database using `package:odbc` and RStudio's Professional drivers rather than when using `package:ROracle`.

I don't know if this is related to `package:odbc` or to RStudio's Professional drivers. I asked my IT department to [set up Oracle's OEM driver](https://solutions.posit.co/connections/db/databases/oracle/) to test it. I will report the results if they do. I have no idea how to investigate the issue further but would be happy to provide more information. 

### Database
```r
dbGetInfo(conn_odbc_rstudio)
# $dbname
# [1] ""
# 
# $dbms.name
# [1] "Oracle"
# 
# $db.version
# [1] "19.00.0000"
# 
# $username
# [1] ""
# 
# $host
# [1] ""
# 
# $port
# [1] ""
# 
# $sourcename
# [1] "xxx" # removed for privacy
# 
# $servername
# [1] "xxx" # removed for privacy
# 
# $drivername
# [1] "RStudio Oracle ODBC Driver"
# 
# $odbc.version
# [1] "03.52"
# 
# $driver.version
# [1] "2.0.2.1002"
# 
# $odbcdriver.version
# [1] "03.80"
# 
# $supports.transactions
# [1] TRUE
# 
# $getdata.extensions.any_column
# [1] TRUE
# 
# $getdata.extensions.any_order
# [1] TRUE
# 
# attr(,"class")
# [1] "Oracle"      "driver_info" "list"  
```

### Reproducible Example
```r
library(DBI)

con_roracle <- dbConnect(ROracle::Oracle(), dbname = "xxx")
system.time(dbListTables(con_roracle))
# utilisateur     système      écoulé 
#       0.003       0.000       0.116 
system.time(dbWriteTable(con_roracle, "iris", iris))
# utilisateur     système      écoulé 
#       0.001       0.000       0.138 

conn_odbc_rstudio <- dbConnect(odbc::odbc(), dsn = "yyy")
system.time(dbListTables(conn_odbc_rstudio))
# utilisateur     système      écoulé 
#       2.430       1.676     482.881 
system.time(dbWriteTable(conn_odbc_rstudio, "iris", iris))
# utilisateur     système      écoulé 
#       9.451       1.367    3240.433 
```

<details>
<summary>Session Info</summary>

```r
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Red Hat Enterprise Linux Server 7.8 (Maipo)
# 
# Matrix products: default
# BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
# 
# locale:
#  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8     LC_MONETARY=fr_FR.UTF-8   
#  [6] LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
# [11] LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices datasets  utils     methods   base     
# 
# other attached packages:
# [1] ROracle_1.3-1 odbc_1.3.3    DBI_1.0.0    
# 
# loaded via a namespace (and not attached):
#  [1] bit_1.1-14      compiler_4.1.2  ellipsis_0.3.2  hms_1.1.1       tools_4.1.2     Rcpp_1.0.7      bit64_0.9-7     vctrs_0.3.8    
#  [9] blob_1.2.2      lifecycle_1.0.1 pkgconfig_2.0.2 rlang_0.4.12 
```
</details>

**Comment by ThomasSoeiro** [comment]
According to my IT department:
- The `odbc` package uses `oracle-instantclient19.17-basic.x86_64` in version 19.17.0.0.0.
- The `ROracle` package uses the full client in version 12.1.0.2.
- The `DBI` package is currently in version 1.0.0 and will be updated as soon as possible.

**Comment by ThomasSoeiro** [comment]
The issue occurs both with RStudio's Professional drivers and with Oracle's OEM driver:

```r
library(DBI)

# RStudio's Professional drivers
conn_rstudio_odbc <- dbConnect(drv = odbc::odbc(), dsn = "yyy")
dbListTables(conn_rstudio_odbc) |> system.time()
# utilisateur     système      écoulé 
#       7.355       1.478    3427.682

# using Oracle's OEM driver
conn_oracle_odbc <- dbConnect(drv = odbc::odbc(), dsn = "zzz")
dbListTables(conn_oracle_odbc) |> system.time()
# still running...
```

**Comment by detule** [comment]
Hi - 

How do things compare when you ask for listing of tables in a specific schema ( your username? )
```
dbListTables( conn, schema_name = "<schema>" )
```

**Comment by ThomasSoeiro** [comment]
> How do things compare when you ask for listing of tables in a specific schema ( your username? )

It is slow as well:

```
dbListTables(conn, schema_name = "this_is_my_username") |> system.time()
# killed after 7+ mins without return
```

Happy to run more tests if needed.

Thanks!

**Comment by ThomasSoeiro** [comment]
I confirm this works (fast).
Do you have any suggestion for `dbWriteTable`?
Thanks!

**Comment by detule** [comment]
Right, ```dbWriteTable``` calls ```dbListTables``` to verify that the existence of the table.  Once we address here, I suspect you will see performance improvements there as well.

I'll try to get to this in the coming week or two.  Thanks for your patience in the meantime.

**Comment by detule** [comment]
@ThomasSoeiro

Sorry about the delay - when you get a chance, can you try one more invocation:

```
dbListTables(conn, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW")
```

Thanks.

**Comment by ThomasSoeiro** [comment]
It's much better, but it's not fast either:

```r
dbListTables(conn, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
utilisateur     système      écoulé 
      0.010       0.005       6.423 
```

By the way, could this issue be related to rstudio/rstudio#12699? (and eventually #527)

Happy to run more test if needed.

Thanks!

**Comment by detule** [comment]
Thanks for checking; unfortunate it still takes multiple seconds.  We still have the performant query route - will circle back to that approach.

Took a look at the issue reported for the IDE.  I could be wrong, but my take is that showing all the schema in the initial view is correct / desired behavior.  The excessive time to expand the objects in the connections pane ( as well as the IDE becoming unresponsive in the meantime ) are a different incarnation of the same issue we are looking into here.

#527 is unrelated / something specific to SQL Server.

**Comment by ThomasSoeiro** [comment]
> Thanks for checking; unfortunate it still takes multiple seconds. We still have the performant query route - will circle back to that approach.

For completeness, here are some more timings of the two solutions that work (I did not provide any for the query route):

```r
library(DBI)
conn_odbc <- dbConnect(odbc::odbc(), "yyy")

dbListTables(conn_odbc, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
# utilisateur     système      écoulé 
#       0.013       0.006      13.558 
dbListTables(conn_odbc, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
# utilisateur     système      écoulé 
#       0.010       0.006      13.629 
dbListTables(conn_odbc, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
# utilisateur     système      écoulé 
#       0.005       0.004       6.319 
dbListTables(conn_odbc, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
# utilisateur     système      écoulé 
#       0.005       0.001       3.689 
dbListTables(conn_odbc, catalog_name="", schema_name="<username>", table_type="TABLE,VIEW") |> system.time()
# utilisateur     système      écoulé 
#       0.005       0.004       4.434 


dbGetQuery(conn_odbc, "SELECT * FROM all_objects WHERE owner='<username>' AND (object_type = 'TABLE' OR object_type = 'VIEW')") |> system.time()
# utilisateur     système      écoulé 
#       0.024       0.028       3.667 
dbGetQuery(conn_odbc, "SELECT * FROM all_objects WHERE owner='<username>' AND (object_type = 'TABLE' OR object_type = 'VIEW')") |> system.time()
# utilisateur     système      écoulé 
#       0.017       0.001       0.130 
dbGetQuery(conn_odbc, "SELECT * FROM all_objects WHERE owner='<username>' AND (object_type = 'TABLE' OR object_type = 'VIEW')") |> system.time()
# utilisateur     système      écoulé 
#       0.017       0.001       0.106 
dbGetQuery(conn_odbc, "SELECT * FROM all_objects WHERE owner='<username>' AND (object_type = 'TABLE' OR object_type = 'VIEW')") |> system.time()
# utilisateur     système      écoulé 
#       0.019       0.001       0.106 
dbGetQuery(conn_odbc, "SELECT * FROM all_objects WHERE owner='<username>' AND (object_type = 'TABLE' OR object_type = 'VIEW')") |> system.time()
# utilisateur     système      écoulé 
#       0.013       0.003       0.154 
```

And for reference:
```r
con_roracle <- dbConnect(drv = ROracle::Oracle(), dbname = "xxx")

dbListTables(con_roracle) |> system.time()
# utilisateur     système      écoulé 
#       0.002       0.000       0.296 
dbListTables(con_roracle) |> system.time()
# utilisateur     système      écoulé 
#       0.001       0.000       0.123 
dbListTables(con_roracle) |> system.time()
# utilisateur     système      écoulé 
#       0.002       0.000       0.082 
dbListTables(con_roracle) |> system.time()
# utilisateur     système      écoulé 
#       0.001       0.000       0.066 
dbListTables(con_roracle) |> system.time()
# utilisateur     système      écoulé 
#       0.001       0.000       0.106 
```

**Comment by ThomasSoeiro** [comment]
> The excessive time to expand the objects in the connections pane ( as well as the IDE becoming unresponsive in the meantime ) are a different incarnation of the same issue we are looking into here.

Thank you for taking a look. Does this mean that fixing this issue (`dbListTables()`) will also fix the login pane?

**Comment by detule** [comment]
Thanks:

Do you have the ability to test a development branch?  If so I was hoping you can test `dbWriteTable` on https://github.com/r-dbi/odbc/pull/560 ?

I expect improved `dbWriteTable`, with status quo on `dbListTables` and connection pane issues.

Thank you for the continued reports - appreciate it.

**Comment by ThomasSoeiro** [comment]
> Do you have the ability to test a development branch? If so I was hoping you can test `dbWriteTable` on #560 ? I expect improved `dbWriteTable`, with status quo on `dbListTables` and connection pane issues.

My IT department has a strict policy on package installation. I have asked them if it is possible to make an exception. If so, I will report the results.

> And if you are up for it also testing performance of two more queries:

Here are the results:

```r
library(DBI)
conn <- dbConnect(odbc::odbc(), "xxx")


q1 <- "
SELECT * FROM
( SELECT null table_qualifier, 'TESTOWNER' table_owner, o1.object_name table_name, o1.object_type table_type, null remarks
 FROM user_objects o1 WHERE o1.object_type in ('TABLE', 'VIEW')
 UNION
 SELECT null table_qualifier, 'TESTOWNER' table_owner, s.synonym_name table_name, 'SYNONYM' table_type, null remarks
 FROM user_objects o3, user_synonyms s
 WHERE o3.object_type in ('TABLE','VIEW') AND s.table_name = o3.object_name
 UNION
 SELECT null table_qualifier, 'TESTOWNER' table_owner, s1.synonym_name table_name, 'SYNONYM' table_type, null remarks
 FROM user_synonyms s1 WHERE s1.db_link IS NOT NULL
 ) tables
"

dbGetQuery(conn, q1) |> system.time()
# utilisateur     système      écoulé 
#       0.020       0.013       1.683 
dbGetQuery(conn, q1) |> system.time()
# utilisateur     système      écoulé 
#       0.012       0.002       1.106 
dbGetQuery(conn, q1) |> system.time()
# utilisateur     système      écoulé 
#       0.007       0.004       1.039 
dbGetQuery(conn, q1) |> system.time()
# utilisateur     système      écoulé 
#       0.008       0.001       1.105 
dbGetQuery(conn, q1) |> system.time()
# utilisateur     système      écoulé 
#       0.006       0.003       0.969 
```

And:

```r
q2 <- "
SELECT * FROM
( SELECT null table_qualifier, o1.owner table_owner, o1.object_name table_name, decode(o1.owner,'SYS', decode(o1.object_type,'TABLE','SYSTEM TABLE','VIEW', 'SYSTEM VIEW', o1.object_type), 'SYSTEM', decode(o1.object_type,'TABLE','SYSTEM TABLE','VIEW', 'SYSTEM VIEW', o1.object_type), o1.object_type) table_type, null remarks
 FROM all_objects o1 WHERE o1.object_type in ('TABLE', 'VIEW') AND o1.owner='<my username>'
 UNION
 SELECT null table_qualifier, s.owner table_owner, s.synonym_name table_name, 'SYNONYM' table_type, null remarks
 FROM all_objects o3, all_synonyms s
 WHERE o3.object_type in ('TABLE','VIEW') AND s.table_owner= o3.owner AND s.table_name = o3.object_name AND o3.owner='<my username>'
 UNION
 SELECT null table_qualifier, s1.owner table_owner, s1.synonym_name table_name, 'SYNONYM' table_type, null remarks
 FROM all_synonyms s1 WHERE s1.db_link IS NOT NULL AND s1.owner='<my username>'
 ) tables
"

dbGetQuery(conn, q2) |> system.time()
# killed after 14+ minutes without return
```

Thanks!

**Comment by ThomasSoeiro** [comment]
> Do you have the ability to test a development branch? If so I was hoping you can test `dbWriteTable` on #560 ? I expect improved `dbWriteTable`, with status quo on `dbListTables` and connection pane issues.

@detule

My IT department (@zedapolo) agrees to test in the preprod environment but the system is not connected to the internet. Can you provide guidance on how to download the source for #560 and install it on another system? Thanks!

**Comment by ThomasSoeiro** [comment]
> By the way, could this issue be related to [rstudio/rstudio#12699](https://github.com/rstudio/rstudio/issues/12699)?

For the record, in rstudio/rstudio#12699, we also disccussed that a connection to an Oracle database is excessively long to establish when using Oracle's OEM driver (i.e. `dbConnect(drv = odbc::odbc(), dsn = "<DSN using Oracle's OEM driver>")`, see https://github.com/rstudio/rstudio/issues/12699#issuecomment-1435754705 for more information).

It would be nice to fix that too!

**Comment by detule** [comment]
Apologies for the delay; working through an exercise with @hadley on how to organize / prioritize some of the outstanding issues.  Will revert and address this once we are done.

**Comment by detule** [comment]
@ThomasSoeiro 

The main branch of the repo is updated with a collection of Oracle updates.  These should address listing tables / writing to tables, as well as hopefully snappiness in the connections pane.

Let me know if you find otherwise or have other feedback.  In the meantime, I'll close the issue.

Thanks for the patience!

**Comment by ThomasSoeiro** [comment]
@detule @hadley

We run tests today with `package:odbc` 1.3.5 on our preprod server with @zedapolo.

We confirm that `dbListTables()` and the connection pane are now as quick as expected.

There is however a new issue with `dbWritetable()` (see #586).

Thank you so much for all your hard work!
