### ISSUE TITLE
`odbcListDrivers()` shows nothing on 1.3.4 but was working in 1.3.3

### ISSUE THREAD

**Issue by xiaodaigh** [r-dbi/odbc#541]
### Issue Description and Expected Result
Not able to retrieve list of odbc drivers using `odbc::odbcListDrivers()`

### Database
NA

### Reproducible Example
```r
library(odbc)

odbc::odbcListDrivers() # this will show nothign
```

Unfortunatley the code is on my work computer and I can't access github.com using my work computer so easy way to give session info.

<details>
<summary>Session Info</summary>

─ Session info ───────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS 13.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Australia/Melbourne
 date     2023-02-07
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   NA

─ Packages ───────────────────────────────────────────────────────────────────
 ! package     * version date (UTC) lib source
 P bit           4.0.5   2022-11-15 [?] CRAN (R 4.1.1)
 P bit64         4.0.5   2020-08-30 [?] CRAN (R 4.1.0)
 P blob          1.2.3   2022-04-10 [?] CRAN (R 4.1.1)
 P cachem        1.0.6   2021-08-19 [?] CRAN (R 4.1.1)
 P callr         3.7.3   2022-11-02 [?] CRAN (R 4.1.1)
 P cli           3.6.0   2023-01-09 [?] CRAN (R 4.1.1)
 P crayon        1.5.2   2022-09-29 [?] CRAN (R 4.1.1)
 P DBI           1.1.3   2022-06-18 [?] CRAN (R 4.1.1)
 P devtools      2.4.5   2022-10-11 [?] CRAN (R 4.1.1)
 P digest        0.6.31  2022-12-11 [?] CRAN (R 4.1.1)
 P ellipsis      0.3.2   2021-04-29 [?] CRAN (R 4.1.0)
 P fastmap       1.1.0   2021-01-25 [?] CRAN (R 4.1.0)
 P fs            1.6.1   2023-02-06 [?] CRAN (R 4.1.2)
 P glue          1.6.2   2022-02-24 [?] CRAN (R 4.1.2)
 P hms           1.1.2   2022-08-19 [?] CRAN (R 4.1.1)
 P htmltools     0.5.4   2022-12-07 [?] CRAN (R 4.1.1)
 P htmlwidgets   1.6.1   2023-01-07 [?] CRAN (R 4.1.1)
 P httpuv        1.6.8   2023-01-12 [?] CRAN (R 4.1.1)
 P later         1.3.0   2021-08-18 [?] CRAN (R 4.1.1)
 P lifecycle     1.0.3   2022-10-07 [?] CRAN (R 4.1.1)
 P magrittr      2.0.3   2022-03-30 [?] CRAN (R 4.1.1)
 P memoise       2.0.1   2021-11-26 [?] CRAN (R 4.1.1)
 P mime          0.12    2021-09-28 [?] CRAN (R 4.1.1)
 P miniUI        0.1.1.1 2018-05-18 [?] CRAN (R 4.1.0)
 P odbc          1.3.4   2023-01-17 [?] CRAN (R 4.1.1)
 P pkgbuild      1.4.0   2022-11-27 [?] CRAN (R 4.1.1)
 P pkgconfig     2.0.3   2019-09-22 [?] CRAN (R 4.1.0)
 P pkgload       1.3.2   2022-11-16 [?] CRAN (R 4.1.1)
 P prettyunits   1.1.1   2020-01-24 [?] CRAN (R 4.1.0)
 P processx      3.8.0   2022-10-26 [?] CRAN (R 4.1.1)
 P profvis       0.3.7   2020-11-02 [?] CRAN (R 4.1.0)
 P promises      1.2.0.1 2021-02-11 [?] CRAN (R 4.1.0)
 P ps            1.7.2   2022-10-26 [?] CRAN (R 4.1.1)
 P purrr         1.0.1   2023-01-10 [?] CRAN (R 4.1.1)
 P R6            2.5.1   2021-08-19 [?] CRAN (R 4.1.1)
 P Rcpp          1.0.10  2023-01-22 [?] CRAN (R 4.1.1)
 P remotes       2.4.2   2021-11-30 [?] CRAN (R 4.1.1)
   renv          0.16.0  2022-09-29 [1] CRAN (R 4.1.1)
 P rlang         1.0.6   2022-09-24 [?] CRAN (R 4.1.1)
 P rstudioapi    0.14    2022-08-22 [?] CRAN (R 4.1.1)
 P sessioninfo   1.2.2   2021-12-06 [?] CRAN (R 4.1.1)
 P shiny         1.7.4   2022-12-15 [?] CRAN (R 4.1.1)
 P stringi       1.7.12  2023-01-11 [?] CRAN (R 4.1.1)
 P stringr       1.5.0   2022-12-02 [?] CRAN (R 4.1.1)
 P urlchecker    1.0.1   2021-11-30 [?] CRAN (R 4.1.1)
 P usethis       2.1.6   2022-05-25 [?] CRAN (R 4.1.1)
 P vctrs         0.5.2   2023-01-23 [?] CRAN (R 4.1.1)
 P xtable        1.8-4   2019-04-21 [?] CRAN (R 4.1.0)

 [1] /Users/daiz/Documents/git/cci-analysis/renv/library/R-4.1/aarch64-apple-darwin20
 [2] /Users/daiz/Documents/git/cci-analysis/renv/sandbox/R-4.1/aarch64-apple-darwin20/84ba8b13

 P ── Loaded and on-disk path mismatch.

</details>

**Comment by detule** [comment]
Hi there - 

Do you have the ability to rebuild 1.3.4 from source on your M1, rather than installing the pre-built binary?

Cheers

**Comment by xiaodaigh** [comment]
Possibly. It's a work laptop so pretty locked down. I will check

**Comment by detule** [comment]
I think it could help - did you get a chance to try?

**Comment by sharon-wang** [comment]
If you're using `brew`-installed `odbc` on an aarch64 mac, setting `ODBCSYSINI=/opt/homebrew/etc` in `.Renviron` resolved the issue for me and a few others. I've opened #549 to document this troubleshooting step.

**Comment by RoyalTS** [comment]
@sharon-wang That helped, thank you!
