### ISSUE TITLE
Issue with CASE block against an Oracle DB

### ISSUE THREAD

**Issue by fniessen** [r-dbi/odbc#545]
I don't get that.

In R, running such a query against Oracle, via a call to odbc::dbGetQuery(con, query):

    SELECT
        em_id,
        status,
        CASE
            WHEN bl_id IS NOT NULL AND fl_id IS NOT NULL
            THEN CONCAT(bl_id, fl_id)
            ELSE NULL
        END AS location
    FROM em;

will return:

    Error: nanodbc/nanodbc.cpp:1752: HY000:
    [Oracle][ODBC][Ora]ORA-00933: SQL command not properly ended

On the other hand, almost the same one:

    SELECT
        em_id,
        CASE
            WHEN bl_id IS NOT NULL AND fl_id IS NOT NULL
            THEN CONCAT(bl_id, fl_id)
            ELSE NULL
        END,
        status
    FROM em;

will succeed!?

What makes the first request fail?

- The CASE block just before the FROM, and
- The name given to it (AS location)

Only when both previous conditions are false does the query succeed...

NOTE that both queries are correctly run (via dbGetQuery) against an SQL Server DB... 

And both queries do work without any errors in
- SQL Server Management Studio (for SQL Server) and
- SQL Developer (for Oracle).

Both queries are semantically and syntactically correct. Though, one does not work from an Rscript to Oracle...

What can I do to make those queries run without errors on both DB from the R script?

**Comment by hadley** [comment]
Thanks for filing this bug report! Unfortunately because it's so hard to reproduce or we think it's unlikely to affect many people, we don't have the development resources to fix at this time. It's our policy to close such issues to help stay focussed on the biggest problems, but the issue is still indexed by google, so if other people hit it, they'll be able to find it, and we can consider reopen it if it turns out to be a common problem. Thanks for reporting and I'm sorry we couldn't help more 😞.

**Comment by ThomasSoeiro** [comment]
FWIW, I experienced a similar issue a few weeks ago with Oracle ODBC driver version 12.01.0020. I wanted to report but our IT department updated the server in the meantime. I cannot reproduce anymore with Oracle ODBC driver version 19.00.0000.

For previous config, see e.g. [here](https://github.com/r-dbi/odbc/issues/766#issuecomment-1969052719).

Current config:

```r
dbGetInfo(con)
# $dbname
# [1] ""
# 
# $dbms.name
# [1] "Oracle"
# 
# $db.version
# [1] "19.00.0000"
# 
# $username
# [1] ""
# 
# $host
# [1] ""
# 
# $port
# [1] ""
# 
# $sourcename
# [1] "zzz"
# 
# $servername
# [1] "zzz"
# 
# $drivername
# [1] "SQORA32.DLL"
# 
# $odbc.version
# [1] "03.52"
# 
# $driver.version
# [1] "19.23.0000"
# 
# $odbcdriver.version
# [1] "03.52"
# 
# $supports.transactions
# [1] TRUE
# 
# $supports.catalogs
# [1] FALSE
# 
# $supports.schema
# [1] TRUE
# 
# $getdata.extensions.any_column
# [1] TRUE
# 
# $getdata.extensions.any_order
# [1] TRUE
# 
```
