### ISSUE TITLE
dbRemoveTable doesn't seem to work on Teradata databases and may crash R

### ISSUE THREAD

**Issue by aschmu** [r-dbi/odbc#55]
### Database

Teradata 13.10.00

### Reproducible Example

Example:
```r
library(odbc)
library(DBI)

conn <- dbConnect(odbc::odbc(), "DWH", dbname = "db_esp")
create_tbl <- dbSendStatement(conn, 
                          "create table db_esp.am_test_tbl as 
                          (
                              select id,
                              day
                              from db_lam.vaf_mq
                              where day= date '2016-12-02'
                          ) with data;")
dbClearResult(create_tbl)
dbExistsTable(conn, "am_test_tbl") #returns TRUE
dbRemoveTable(conn, name = "am_test_tbl") #throws error
```
` Error in new_result(connection@ptr, statement) : 
  nanodbc.cpp:1344: 42S02: [Teradata][ODBC Teradata Driver][Teradata Database] Object 'am_test_tbl' does not exist. `

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> 
Session info ---------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.1 (2016-06-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  French_France.1252          
 tz       Europe/Paris                
 date     2017-04-23                  

Packages -------------------------------------------------------------------------------------------------
 package  * version date       source        
 blob       1.0.0   2016-12-29 CRAN (R 3.3.3)
 DBI        0.6-1   2017-04-01 CRAN (R 3.3.3)
 devtools   1.11.1  2016-04-21 CRAN (R 3.3.0)
 digest     0.6.10  2016-08-02 CRAN (R 3.3.2)
 memoise    1.0.0   2016-01-29 CRAN (R 3.3.0)
 odbc     * 1.0.1   2017-02-07 CRAN (R 3.3.3)
 Rcpp       0.12.10 2017-03-19 CRAN (R 3.3.3)
 tibble     1.3.0   2017-04-01 CRAN (R 3.3.3)
 withr      1.0.2   2016-06-20 CRAN (R 3.3.2)
```

</details>

I could of course just use sendStatement and that works fine. The annoying thing is also that it crashes Rstudio (it's probably the R session that's being crashed and in turn crashes Rstudio). I'm thinking there's some kind of segfault going on.
I also tested this on Linux Fedora 24 with the same results.

**Comment by jimhester** [comment]
The crash should be fixed by using the devel version of odbc, if you can please try it and let me know if this is not the case.

I think the issue may be more around creating a table in a schema. There unfortunately is not a clear DBI API for schemas currently.

**Comment by aschmu** [comment]
Unfortunately this didn't solve the issue. I can't connect to the database. I'm getting the following error on windows (probably due to the last commit ?) : 
`Error in connection_info(ptr) : 
  nanodbc/nanodbc.cpp:1039: HY090: [Teradata][ODBC Teradata Driver] Invalid buffer size (cbMaxValue < 0 or cbMaxValue < fInfoType) or (cbDescMax < 0) `

**Comment by aschmu** [comment]
Oops, didn't mean to close the issue.

**Comment by jimhester** [comment]
Could you try testing this with a more recent version of the odbc package. I unfortunately don't have a teradata database setup, so I am not able to test this issue locally.

**Comment by aschmu** [comment]
I reinstalled the master version from github and I'm getting the same error
 `Error in new_result(connection@ptr, statement) : nanodbc.cpp:1344: 42S02: [Teradata][ODBC Teradata Driver][Teradata Database] Object 'am_test_tbl' does not exist.`
However the following works : `dbSendStatement(conn, "drop table db_esp.am_test_tbl ;")` and the good news is I am no longer getting random r session crashes.

**Comment by jimhester** [comment]
I think this is overall an issue with the schema support, which should be fixed by https://github.com/r-dbi/odbc/commit/536ee60aee8727a0765691fecb90b664e27811a5
