### ISSUE TITLE
`dbListTables` only returns the first letter of each table name.

### ISSUE THREAD

**Issue by fh-afrachioni** [r-dbi/odbc#561]
### Issue Description and Expected Result
`dbListTables` only returns the first letter of each table name.

### Database
Both Snowflake (version 7.12.5, with Mac ODBC driver version 2.25.10) and Amazon Athena (Mac driver version 1.0.5)

### Reproducible Example
```r
odbc::dbListTables(
    conn,
    catalog_name = 'my_catalog',
    schema_name = 'my_database'
)
```

**Comment by fh-mthomson** [comment]
This issue appears to be now resolved for both Snowflake and Athena as of `odbc` 1.4.0 (perhaps as a side effect of clean #618?).

Note: tested using a Docker image with [Posit Pro 2022.11.0 drivers](https://docs.posit.co/drivers/2022.11.0/release-notes/)

**Comment by hadley** [comment]
That's great to hear!
