### ISSUE TITLE
Can't use Snowflake on MacOS ARM M1

### ISSUE THREAD

**Issue by malthe** [r-dbi/odbc#571]
### Issue Description and Expected Result
Running `myconn <- DBI::dbConnect(odbc::odbc(), "<driver-name>")` fails with:

> Error: nanodbc/nanodbc.cpp:1118: 00000: [<driver-name>][ODBC] (11560) Unable to locate SQLGetPrivateProfileString function: [Snowflake][DSI] An error occurred while attempting to retrieve the error message for key 'LibsLoadErr' with message parameters ['"", "libodbcinst.dylib"'] and component ID 3: Message not found in file "/opt/snowflake/snowflakeodbc/ErrorMessages/en-US/ODBCMessages.xml" 

I have tried adding `ODBCInstLib = /usr/local/iODBC/lib/libiodbcinst.dylib` in various places with no effect. Similarly, I have tried using `DYLD_LIBRARY_PATH`.

At first, I was unable to list the driver, but after installing using `install.packages('odbc', type="source")` the `odbcListDrivers()` call returns the driver.

```r
> odbc::odbcListDrivers()
          name attribute                                               value
1 ODBC Drivers Snowflake                                           Installed
2    Snowflake    Driver /opt/snowflake/snowflakeodbc/lib/libSnowflake.dylib
```

And I can list the data sources:
```r
> odbc::odbcListDataSources()
       name                                         description
1 Snowflake /opt/snowflake/snowflakeodbc/lib/libSnowflake.dylib
```

There's no difference between using RStudio and `Rscript` on the command-line.

### Database
Snowflake

**Comment by irenetlv** [comment]
Hi my coworker is running into the same error message.  What does it mean?  Is there a solution to this or should we try to use the original x86_64 architecture for now?

**Comment by jonathanleff** [comment]
I'm encountering the same issue. Is there a workaround?

**Comment by kpritam-tw** [comment]
I am also facing the same issue with macOS Sanoma. I get fatal (segfault) error which kills rstudio session.

**Comment by detule** [comment]
Hi - Thanks @jonathanleff 

Believe this to be an artifact of Homebrew not officially supporting `Sonoma` yet, not necessarily ARM vs x86.
In the meantime editing the `ini` file should work.

Thanks
