### ISSUE TITLE
package overview page is unaccessible from text/HTML help

### ISSUE THREAD

**Issue by bastistician** [r-dbi/odbc#582]
https://github.com/r-dbi/odbc/blob/fc10a195f2b4558e636d62ff02a48b6569eadd3d/man/odbc-package.Rd#L3-L5

The package overview help page lacks the conventional `\alias{<pkgname>-package}` topic, which means:

- it is missing from the HTML index
- it is not found via `package?<pkgname>` and cannot be easily accessed from text/HTML help

**Comment by hadley** [comment]
Looks like this has already been fixed: https://github.com/r-dbi/odbc/blob/main/man/odbc-package.Rd#L3-L5
