### ISSUE TITLE
Issues connecting to Oracle database where ROracle succeeds (`ORA-12504`, `"Data source name not found, and no default driver specified "`)

### ISSUE THREAD

**Issue by jemus42** [r-dbi/odbc#595]
### Issue Description and Expected Result

I am trying to connect to an Oracle database via ODBC, but I'm not having any luck so far.
I have used `RJDBC` in the past and after some headaches I managed to get `ROracle` running, but ODBC is giving me some trouble as I find e.g. inconsistent information online and am unfortunately not sure how to debug this as I can't simply `debugonce(debConnect)`.

For background, I have read among other resources:

- https://solutions.posit.co/connections/db/databases/oracle/#connection-settings and related docs
- https://r-dbi.github.io/odbc/index.html#connecting-to-a-database
- https://www.connectionstrings.com/oracle/
- https://docs.oracle.com/en/database/oracle/oracle-database/21/lnoci/build-and-configure-oci-applications.html#GUID-E97921AA-A166-44EB-97B7-9EEFE3A23ED3 and related docs

My successful connection via `ROracle` looks like this, with IP, DB etc changed:

```r
library(ROracle)
library(DBI)

con <- dbConnect(
  ROracle::Oracle(),
  username = "<user>", 
  password = "<password>",
  dbname = "12.345.67.89:1521/OurCoolDatabase"
)

con
```
```
User name:             <username> 
Connect string:        12.345.67.89:1521/OurCoolDatabase 
Server version:        11.2.0.2.0 
Server type:           Oracle RDBMS 
Results processed:     5 
OCI prefetch:          FALSE 
```

Translating to ODBC would be simple I thought, but I guess the fact that the `dbConnect()` arguments are different was the first hint that it's going to be harder than I hoped:

```r
library(odbc)

con <- DBI::dbConnect(
  odbc::odbc(),
  Driver = "Oracle21",
  Host   = "12.345.67.89",
  SVC    = "OurCoolDatabase", # I tried different things here to no avail.
  UID    = "<user>",
  PWD    = "<password>",
  Port   = 1521
)
```

This yields this error:

```
Error: nanodbc/nanodbc.cpp:1135: 00000: [Oracle][ODBC][Ora]ORA-12504: TNS:listener was not given the SERVICE_NAME in CONNECT_DATA
```

After some googling around I found that adding `dsn = "12.345.67.89:1521/OurCoolDatabase"` could work, which at least changed the error I guess:

```
Error: nanodbc/nanodbc.cpp:1135: 00000: [unixODBC][Driver Manager]Data source name not found, and no default driver specified 
```

I also tried connecting via a dedicated connection, so variations of this:

```r
con <- DBI::dbConnect(odbc::odbc(), "cooldb", pwd = "<password>")

con <- dbConnect(
  odbc::odbc(), "cooldb",
  UID = "<user>", PWD = "<password>",
  .connection_string = "DBQ=12.345.67.89:1521/OurCoolDatabase"
)
```

but did not receive any more useful results.

I am reasonably certain I have set up `odbcinst.ini` correctly, but not so much for `~/.odbc.ini`.
In any case, I would like to note that both of these find the entries I expect:

```r
odbc::odbcListDrivers()
odbc::odbcListDataSources()
```

<details>
<summary>Contents of <code>/etc/odbcinst.ini</code>:
</summary>

```ini
[Oracle21]
Description     = Oracle ODBC driver for Oracle 21.1
Driver          = /usr/lib/oracle/21/client64/lib/libsqora.so.21.1
Setup           =
FileUsage       =
CPTimeout       =
CPReuse         = 
```

I have installed the ODBC driver from Oracle and have verified that `/usr/lib/oracle/21/client64/lib/libsqora.so.21.1` exists. `unixodb{-dev}` are also installed.
</details>
  

<details>
<summary>Contents of <code>~/.odbc.ini</code> (schematically):
</summary>

```ini
[cooldb]
Description = "Our Cool Database"
Driver      = Oracle21
Database    = OurCoolDatabase
Servername  = 12.345.67.89
UserName    = <user>
Port        = 1521
```

I'd like to note that I have not fully understood what the correct names for these entries should be, as everything that comes up via google appears to use slightly different names
</details>

### Database
Oracle RDBMS 11.2.0.2.0

### Reproducible Example

Since I can not provide access to the database in question, I can't provide more of a reproducible example than the example `dbConnect` calls above I'm afraid.

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
─ Session info ─────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16)
 os       Ubuntu 20.04.6 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Berlin
 date     2023-08-16
 rstudio  2023.06.1+524 Mountain Hydrangea (server)
 pandoc   3.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/tools/ (via rmarkdown)

─ Packages ─────────────────────────────────────────
 package     * version date (UTC) lib source
 askpass       1.1     2019-01-13 [1] RSPM
 assertthat    0.2.1   2019-03-21 [1] RSPM
 bit           4.0.5   2022-11-15 [1] RSPM
 bit64         4.0.5   2020-08-30 [1] RSPM
 blob          1.2.4   2023-03-17 [1] RSPM
 cachem        1.0.8   2023-05-01 [1] CRAN (R 4.3.0)
 callr         3.7.3   2022-11-02 [1] RSPM
 cli           3.6.1   2023-03-23 [1] RSPM
 crayon        1.5.2   2022-09-29 [1] RSPM
 DBI         * 1.1.3   2022-06-18 [1] RSPM
 devtools      2.4.5   2022-10-11 [1] RSPM
 digest        0.6.31  2022-12-11 [1] RSPM
 DT            0.27    2023-01-17 [1] RSPM
 ellipsis      0.3.2   2021-04-29 [1] RSPM
 evaluate      0.21    2023-05-05 [1] CRAN (R 4.3.0)
 fastmap       1.1.1   2023-02-24 [1] RSPM
 filelock      1.0.2   2018-10-05 [1] RSPM
 fs            1.6.3   2023-07-20 [1] RSPM
 glue          1.6.2   2022-02-24 [1] RSPM
 hms           1.1.3   2023-03-21 [1] RSPM
 htmltools     0.5.5   2023-03-23 [1] RSPM
 htmlwidgets   1.6.2   2023-03-17 [1] RSPM
 httpuv        1.6.9   2023-02-14 [1] RSPM
 keyring     * 1.3.1   2022-10-27 [1] RSPM
 knitr         1.43    2023-05-25 [1] CRAN (R 4.3.0)
 later         1.3.0   2021-08-18 [1] RSPM
 lifecycle     1.0.3   2022-10-07 [1] RSPM
 magrittr      2.0.3   2022-03-30 [1] RSPM
 memoise       2.0.1   2021-11-26 [1] RSPM
 mime          0.12    2021-09-28 [1] RSPM
 miniUI        0.1.1.1 2018-05-18 [1] RSPM
 odbc        * 1.3.5   2023-06-29 [1] RSPM
 pak           0.5.1   2023-04-27 [1] CRAN (R 4.3.0)
 pkgbuild      1.4.0   2022-11-27 [1] RSPM
 pkgconfig     2.0.3   2019-09-22 [1] RSPM
 pkgload       1.3.2   2022-11-16 [1] RSPM
 prettyunits   1.1.1   2020-01-24 [1] RSPM
 processx      3.8.2   2023-06-30 [1] RSPM
 profvis       0.3.7   2020-11-02 [1] RSPM
 promises      1.2.0.1 2021-02-11 [1] RSPM
 ps            1.7.5   2023-04-18 [1] RSPM
 purrr         1.0.1   2023-01-10 [1] RSPM
 R6            2.5.1   2021-08-19 [1] RSPM
 rappdirs      0.3.3   2021-01-31 [1] RSPM
 Rcpp          1.0.10  2023-01-22 [1] RSPM
 remotes       2.4.2   2021-11-30 [1] CRAN (R 4.3.0)
 rlang         1.1.1   2023-04-28 [1] CRAN (R 4.3.0)
 rmarkdown     2.22    2023-06-01 [1] CRAN (R 4.3.0)
 ROracle     * 1.3-1.1 2021-11-10 [1] CRAN (R 4.3.1)
 rstudioapi    0.14    2022-08-22 [1] RSPM
 sessioninfo   1.2.2   2021-12-06 [1] RSPM
 shiny         1.7.4   2022-12-15 [1] RSPM
 shinyjs       2.1.0   2021-12-23 [1] CRAN (R 4.3.1)
 sodium        1.2.1   2022-06-11 [1] RSPM
 stringi       1.7.12  2023-01-11 [1] RSPM
 stringr       1.5.0   2022-12-02 [1] RSPM
 urlchecker    1.0.1   2021-11-30 [1] RSPM
 usethis       2.1.6   2022-05-25 [1] RSPM
 vctrs         0.6.2   2023-04-19 [1] RSPM
 xfun          0.39    2023-04-20 [1] RSPM
 xtable        1.8-4   2019-04-21 [1] RSPM
 yaml          2.3.7   2023-01-23 [1] RSPM

 [1] /home/burk/R/x86_64-pc-linux-gnu-library/4.3
 [2] /opt/R/4.3.1/lib/R/library

────────────────────────────────────────────────────
```
</details>

**Comment by simmwill** [comment]
I spent a few hours last night dealing with a similar (though not identical) issue with `odbc`. My connection had been working for years but stopped working yesterday. 

What finally worked for me was to revert my `odbc` version to 1.3.3 (2021-11-30 release):

`devtools::install_version("odbc", version = "1.3.3", repos = "http://cran.us.r-project.org")`

May be worth trying!

**Comment by detule** [comment]
Hi @jemus42 

Have you populated a `tnsnames.ora` file?  The OEM Oracle ODBC driver needs, I believe, connection properties to be specified in this file ( in addition to the driver being listed in odbcinst.ini and broad connection details in odbc.ini )

I can help you out more next week when I am around my oracle instance.

**Comment by jemus42** [comment]
> Have you populated a `tnsnames.ora` file?

I have not! I had found references to this file in various google results but not in the documentation I used to set things up, I might have just missed that.
A quick google brings up <https://www.orafaq.com/wiki/Tnsnames.ora>, and it looks like the contents of that file are similar (identical?) to these [connection strings](https://www.connectionstrings.com/oracle/)?
I'll take a look and play around with that a little, thanks!

**Comment by jemus42** [comment]
Alas, success! Even though I don't understand why.

Long story short: this works.

```r
con <- DBI::dbConnect(
  odbc::odbc(),
  "cooldb",
  UID = <user>,
  PWD    = <password>,
  .connection_string = "DBQ=12.345.67.89:1521/OurCoolDB;"
)
```

What I do not understand is why the `DBQ` part is necessary (my error was that I did not terminate it with `;` by the way, which lead to the wrong `connection_string` being pasted together in `odbc:::odbc_connect` (see also previous comment).)

And I don't know why I have to specify `UID = ...`, even though I have a `.odbc.ini`:

```ini
[cooldb]
Description = "Our Cool Database"
Driver      = Oracle21
Database    = OurCoolDB
Servername  = 12.345.67.89
Port        = 1521
UID     = <username>
```

I also tried the keys "UserName" or "User" or "LogonID" and each time I get an error about my credentials being incorrect. But anyway, at the very least I would like to suggest expanding the documentation of `dbConnect` to mention that the `.connection_string` argument's value will be pasted to the *beginning* of the connection string and **MUST** be terminated with a `;` if other arguments are used 😅

**Comment by detule** [comment]
Glad you were able to figure it out.

From what I can tell, the dbConnect documentation [does state ](https://github.com/r-dbi/odbc/blob/main/R/Driver.R#L68)that any other arguments are simply appended to this string.  IMO, that paints a clear enough picture.

Thanks again for following up with noting what worked for you.
