### ISSUE TITLE
dbWriteTable sets all column values to NULL if first value in dataframe is NA

### ISSUE THREAD

**Issue by bergatronic** [r-dbi/odbc#602]
### Issue Description and Expected Result

dbWriteTable sets all column values to NULL if first value in dataframe is NA
### Database

Oracle Database 18c Enterprise Edition Release 18.0.0.0.0 - Production Version 18.5.0.0.0
### Reproducible Example

```r
# Case 1 - Not working
# Connect to Oracle Database
con <- DBI::dbConnect(odbc::odbc(), "PDWH-DMT", timeout = 10) # Oracle ODBC connection

# Setting every other value in mtcars to NA starting with the first value
test <- mtcars |> dplyr::mutate(qsec = ifelse(dplyr::row_number() %% 2 == 0, qsec, NA_real_))
assertthat::assert_that(16 == sum(is.na(test$qsec)))

# Write the table to database
DBI::dbWriteTable(con, "mtcars", test, overwrite = TRUE)

# Read written table from database
test2 <- DBI::dbReadTable(con, "mtcars")
# Generates error
assertthat::assert_that(16 == sum(is.na(test2$qsec)))

# Case 2 - working

# Setting every other value in mtcars to NA starting with the second value
test3 <- mtcars |> dplyr::mutate(qsec = ifelse(dplyr::row_number() %% 2 == 1, qsec, NA_real_))
assertthat::assert_that(16 == sum(is.na(test3$qsec)))

DBI::dbWriteTable(con, "mtcars", test3, overwrite = TRUE)
test4 <- DBI::dbReadTable(con, "mtcars")

# Does not generate error
assertthat::assert_that(16 == sum(is.na(test4$qsec)))
```
<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> output
```
─ Session info ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.0 (2021-05-18)
 os       Red Hat Enterprise Linux 8.7 (Ootpa)
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Brussels
 date     2023-09-12
 rstudio  2022.02.3+492.pro3 Prairie Trillium (server)
 pandoc   2.17.1.1 @ /usr/lib/rstudio-server/bin/quarto/bin/ (via rmarkdown)

─ Packages ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version                date (UTC) lib source
 assertthat     0.2.1                  2019-03-21 [1] RSPM (R 4.1.0)
 bit            4.0.5                  2022-11-15 [1] RSPM (R 4.1.0)
 bit64          4.0.5                  2020-08-30 [1] RSPM (R 4.1.0)
 blob           1.2.3                  2022-04-10 [1] RSPM (R 4.1.0)
 cachem         1.0.6                  2021-08-19 [1] RSPM (R 4.1.0)
 callr          3.7.3                  2022-11-02 [1] RSPM (R 4.1.0)
 cli            3.4.1                  2022-09-23 [1] RSPM (R 4.1.0)
 codetools      0.2-18                 2020-11-04 [1] CRAN (R 4.1.0)
 crayon         1.5.2                  2022-09-29 [1] RSPM (R 4.1.0)
 DBI          * 1.1.3                  2022-06-18 [1] RSPM (R 4.1.0)
 devtools       2.4.5                  2022-10-11 [1] RSPM (R 4.1.0)
 digest         0.6.30                 2022-10-18 [1] RSPM (R 4.1.0)
 dplyr          1.0.10                 2022-09-01 [1] RSPM (R 4.1.0)
 dwhgenerator   3.7.8.0.0.0.1686747824 2023-06-14 [1] RSPM (R 4.1.0)
 dwhparser      0.3.2.0.0.0.1680099806 2023-05-16 [1] RSPM (R 4.1.0)
 ellipsis       0.3.2                  2021-04-29 [1] RSPM (R 4.1.0)
 evaluate       0.18                   2022-11-07 [1] RSPM (R 4.1.0)
 fansi          1.0.3                  2022-03-24 [1] RSPM (R 4.1.0)
 fastmap        1.1.0                  2021-01-25 [1] RSPM (R 4.1.0)
 foreach        1.5.2                  2022-02-02 [1] RSPM (R 4.1.0)
 fs             1.5.2                  2021-12-08 [1] RSPM (R 4.1.0)
 generics       0.1.3                  2022-07-05 [1] RSPM (R 4.1.0)
 glue           1.6.2                  2022-02-24 [1] RSPM (R 4.1.0)
 hms            1.1.2                  2022-08-19 [1] RSPM (R 4.1.0)
 htmltools      0.5.3                  2022-07-18 [1] RSPM (R 4.1.0)
 htmlwidgets    1.5.4                  2021-09-08 [1] RSPM (R 4.1.0)
 httpuv         1.6.6                  2022-09-08 [1] RSPM (R 4.1.0)
 iterators      1.0.14                 2022-02-05 [1] RSPM (R 4.1.0)
 knitr          1.41                   2022-11-18 [1] RSPM (R 4.1.0)
 later          1.3.0                  2021-08-18 [1] RSPM (R 4.1.0)
 lifecycle      1.0.3                  2022-10-07 [1] RSPM (R 4.1.0)
 lubridate      1.9.0                  2022-11-06 [1] RSPM (R 4.1.0)
 magrittr       2.0.3                  2022-03-30 [1] RSPM (R 4.1.0)
 memoise        2.0.1                  2021-11-26 [1] RSPM (R 4.1.0)
 mime           0.12                   2021-09-28 [1] RSPM (R 4.1.0)
 miniUI         0.1.1.1                2018-05-18 [1] RSPM (R 4.1.0)
 odbc           1.3.3                  2021-11-30 [1] RSPM (R 4.1.0)
 openxlsx       4.2.5.1                2022-10-24 [1] RSPM (R 4.1.0)
 pillar         1.8.1                  2022-08-19 [1] RSPM (R 4.1.0)
 pins           1.0.3                  2022-09-24 [1] RSPM (R 4.1.0)
 pkgbuild       1.4.0                  2022-11-27 [1] RSPM (R 4.1.0)
 pkgconfig      2.0.3                  2019-09-22 [1] RSPM (R 4.1.0)
 pkgload        1.3.2                  2022-11-16 [1] RSPM (R 4.1.0)
 prettyunits    1.1.1                  2020-01-24 [1] RSPM (R 4.1.0)
 processx       3.8.0                  2022-10-26 [1] RSPM (R 4.1.0)
 profvis        0.3.7                  2020-11-02 [1] RSPM (R 4.1.0)
 promises       1.2.0.1                2021-02-11 [1] RSPM (R 4.1.0)
 ps             1.7.2                  2022-10-26 [1] RSPM (R 4.1.0)
 purrr          0.3.5                  2022-10-06 [1] RSPM (R 4.1.0)
 R6             2.5.1                  2021-08-19 [1] RSPM (R 4.1.0)
 rappdirs       0.3.3                  2021-01-31 [1] RSPM (R 4.1.0)
 Rcpp           1.0.9                  2022-07-08 [1] RSPM (R 4.1.0)
 readr          2.1.3                  2022-10-01 [1] RSPM (R 4.1.0)
 remotes        2.4.2                  2021-11-30 [1] RSPM (R 4.1.0)
 rlang          1.0.6                  2022-09-24 [1] RSPM (R 4.1.0)
 rmarkdown      2.18                   2022-11-09 [1] RSPM (R 4.1.0)
 rstudioapi     0.14                   2022-08-22 [1] RSPM (R 4.1.0)
 sessioninfo    1.2.2                  2021-12-06 [1] RSPM (R 4.1.0)
 shiny          1.7.3                  2022-10-25 [1] RSPM (R 4.1.0)
 srba3          2.1.5.0.0.0.1659089774 2022-12-10 [1] RSPM (R 4.1.0)
 stringi        1.7.8                  2022-07-11 [1] RSPM (R 4.1.0)
 stringr        1.5.0                  2022-12-02 [1] RSPM (R 4.1.0)
 tibble         3.1.8                  2022-07-22 [1] RSPM (R 4.1.0)
 tidyr          1.2.1                  2022-09-08 [1] RSPM (R 4.1.0)
 tidyselect     1.2.0                  2022-10-10 [1] RSPM (R 4.1.0)
 tidyxl         1.0.8                  2022-09-01 [1] RSPM (R 4.1.0)
 timechange     0.1.1                  2022-11-04 [1] RSPM (R 4.1.0)
 tzdb           0.3.0                  2022-03-28 [1] RSPM (R 4.1.0)
 urlchecker     1.0.1                  2021-11-30 [1] RSPM (R 4.1.0)
 usethis        2.1.6                  2022-05-25 [1] RSPM (R 4.1.0)
 utf8           1.2.2                  2021-07-24 [1] RSPM (R 4.1.0)
 vctrs          0.5.1                  2022-11-16 [1] RSPM (R 4.1.0)
 vroom          1.6.0                  2022-09-30 [1] RSPM (R 4.1.0)
 withr          2.5.0                  2022-03-03 [1] RSPM (R 4.1.0)
 xfun           0.35                   2022-11-16 [1] RSPM (R 4.1.0)
 xtable         1.8-4                  2019-04-21 [1] RSPM (R 4.1.0)
 yaml           2.3.6                  2022-10-18 [1] RSPM (R 4.1.0)
 zip            2.2.2                  2022-10-26 [1] RSPM (R 4.1.0)

 [1] /opt/rstudio-shared/home/bergsjo@srb.europa.eu/R/x86_64-pc-linux-gnu-library/4.1
 [2] /opt/R/4.1.0/lib/R/library

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

</details>

**Comment by simonpcouch** [comment]
Thanks for the issue, @bergatronic. We have some changes for Oracle support in the dev version of the package. Could you install with `pak::pak("r-dbi/odbc")` and confirm whether those changes address your issue? If not, could you run your reproducible example with `reprex::reprex` so that we can see the errors you're mentioning?

Possibly related to https://github.com/r-dbi/odbc/pull/712.

**Comment by detule** [comment]
Simon: I am unable to reproduce this with the OEM driver; suggest we close, unless the user comes back with a follow up report.  If they do I would be interested in finding out which Oracle ODBC driver they are using.
```
 ┃  > mtcarsA <- mtcars
 ┃  > mtcarsA$qsec[seq(0, nrow(mtcars), 2)] <- NA_real_
 ┃  > head(mtcarsA)
 ┃                     mpg cyl disp  hp drat    wt  qsec vs am gear carb
 ┃  Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
 ┃  Mazda RX4 Wag     21.0   6  160 110 3.90 2.875    NA  0  1    4    4
 ┃  Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
 ┃  Hornet 4 Drive    21.4   6  258 110 3.08 3.215    NA  1  0    3    1
 ┃  Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
 ┃  Valiant           18.1   6  225 105 2.76 3.460    NA  1  0    3    1
 ┃  > dbRemoveTable(conn, "test_table")
 ┃  > dbWriteTable(conn, "test_table", mtcarsA)
 ┃  > head(DBI::dbReadTable(conn, "test_table"))
 ┃     mpg cyl disp  hp drat    wt  qsec vs am gear carb
 ┃  1 21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
 ┃  2 21.0   6  160 110 3.90 2.875    NA  0  1    4    4
 ┃  3 22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
 ┃  4 21.4   6  258 110 3.08 3.215    NA  1  0    3    1
 ┃  5 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
 ┃  6 18.1   6  225 105 2.76 3.460    NA  1  0    3    1
 ┃  > mtcarsB <- mtcars
 ┃  > mtcarsB$qsec[seq(1, nrow(mtcarsB), 2)] <- NA_real_
 ┃  > head(mtcarsB)
 ┃                     mpg cyl disp  hp drat    wt  qsec vs am gear carb
 ┃  Mazda RX4         21.0   6  160 110 3.90 2.620    NA  0  1    4    4
 ┃  Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
 ┃  Datsun 710        22.8   4  108  93 3.85 2.320    NA  1  1    4    1
 ┃  Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
 ┃  Hornet Sportabout 18.7   8  360 175 3.15 3.440    NA  0  0    3    2
 ┃  Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
 ┃  > dbRemoveTable(conn, "test_table")
 ┃  > dbWriteTable(conn, "test_table", mtcarsB)
 ┃  > head(DBI::dbReadTable(conn, "test_table"))
 ┃     mpg cyl disp  hp drat    wt  qsec vs am gear carb
 ┃  1 21.0   6  160 110 3.90 2.620    NA  0  1    4    4
 ┃  2 21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
 ┃  3 22.8   4  108  93 3.85 2.320    NA  1  1    4    1
 ┃  4 21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
 ┃  5 18.7   8  360 175 3.15 3.440    NA  0  0    3    2
 ┃  6 18.1   6  225 105 2.76 3.460 20.22  1  0    3    1
 ┃  >
```
