### ISSUE TITLE
RStudio's Connection Pane usability issues with thousands of objects

### ISSUE THREAD

**Issue by ThomasSoeiro** [r-dbi/odbc#605]
### Issue Description and Expected Result

(Please let me know if this should be reported to RStudio.)

When using `package:odbc`, RStudio's Connections Pane shows all schemas rather than the schema of the connected user by default. If the database contains thousands of objects, only some are shown (i.e. the first 512 schemas in alphabetical order in my case). If we use the search box to show the desired schema, we get a "Show more" button. Pressing the "Show more" button gets back to the initial state (i.e. it bypasses the filter and shows all schemas).

Currently, the only way to show the desired schema is to press  the "Show more" button many, many times. It is not possible to use the search box.

Expected results:

- Pressing the "Show more" button should not bypass the filter when using the search box.
- Connections Pane could show the schema of the connected user by default. [Other users expected that too.](https://community.rstudio.com/t/rstudio-oracle-db-connection/129118)

This was previously discussed on https://github.com/rstudio/rstudio/issues/12699. According to @ronblum:
> For what it's worth, showing all of the Oracle accounts had always been the behavior for Oracle and a couple of other data sources, but most only show the user tables.

### Database

```r
dbGetInfo(con)
# $dbname
# [1] ""
# 
# $dbms.name
# [1] "Oracle"
# 
# $db.version
# [1] "19.00.0000"
# 
# $username
# [1] ""
# 
# $host
# [1] ""
# 
# $port
# [1] ""
# 
# $sourcename
# [1] "xxx"
# 
# $servername
# [1] "yyy"
# 
# $drivername
# [1] "RStudio Oracle ODBC Driver"
# 
# $odbc.version
# [1] "03.52"
# 
# $driver.version
# [1] "2.0.2.1002"
# 
# $odbcdriver.version
# [1] "03.80"
# 
# $supports.transactions
# [1] TRUE
# 
# $getdata.extensions.any_column
# [1] TRUE
# 
# $getdata.extensions.any_order
# [1] TRUE
# 
# attr(,"class")
# [1] "Oracle"      "driver_info" "list"   
```

### Reproducible Example

```r
library(DBI)
con <- dbConnect(drv = odbc::odbc(), dsn = "xxx")

odbc::odbcListObjects(con) |> nrow()
# 21005
```

If the database contains thousands of objects, only some are shown (i.e. the first 512 schemas in alphabetical order in my case):
![default](https://github.com/r-dbi/odbc/assets/124079058/da0b9a17-57f4-4286-8e20-6ff6214acc6a)

If we use the search box to show the desired schema, we get a button "Show more": [Pressing the button gets back to the initial state (i.e. it bypasses the filter and shows all schemas).]
![search](https://github.com/r-dbi/odbc/assets/124079058/bd32f166-a0c2-46d6-be32-a47faf15498d)

<details>
<summary>Session Info</summary>

```r
sessionInfo()
# R version 4.1.2 (2021-11-01)
# Platform: x86_64-pc-linux-gnu (64-bit)
# Running under: Red Hat Enterprise Linux Server 7.8 (Maipo)
# 
# Matrix products: default
# BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so
# 
# locale:
#  [1] LC_CTYPE=fr_FR.UTF-8       LC_NUMERIC=C               LC_TIME=fr_FR.UTF-8        LC_COLLATE=fr_FR.UTF-8    
#  [5] LC_MONETARY=fr_FR.UTF-8    LC_MESSAGES=fr_FR.UTF-8    LC_PAPER=fr_FR.UTF-8       LC_NAME=C                 
#  [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=fr_FR.UTF-8 LC_IDENTIFICATION=C       
# 
# attached base packages:
# [1] stats     graphics  grDevices datasets  utils     methods   base     
# 
# other attached packages:
# [1] DBI_1.0.0
# 
# loaded via a namespace (and not attached):
#  [1] bit_1.1-14      odbc_1.3.5      compiler_4.1.2  ellipsis_0.3.2  hms_1.1.1       tools_4.1.2     Rcpp_1.0.7     
#  [8] bit64_0.9-7     vctrs_0.3.8     blob_1.2.2      lifecycle_1.0.1 pkgconfig_2.0.2 rlang_0.4.12   
```
</details>

**Comment by hadley** [comment]
It looks like this issue is actually two problems:

1. The connections UI is not well designed for large number of objects (https://github.com/r-dbi/odbc/issues/605)
2. In this case. odbc is returning too many objects because it's including too many schemas in the results. (#447)

Since these are both tracked elsewhere, I'm closing this issue.
