### ISSUE TITLE
R session crashes when sending query to closed connection

### ISSUE THREAD

**Issue by kummerer94** [r-dbi/odbc#607]
### Issue Description and Expected Result

When I send a query to a connection to a Azure SQL database that was closed by the database server, R crashes completely without any error message.

More details;

We recently switched to using `pool` to handle our database connections. Pool refreshes the connection in the background once it becomes invalid. To check the validity of the connection to the SQL server database, it sends a short query (`SELECT 1`) by default. This query crashes the R process / session.

### Database

Azure SQL Server

### Reproducible Example

1. Connect to the database.
2. Close the connection on the database side (either you wait or you force this by finding out the SPID of the connection with `sp_who2` and then using `KILL xx` where `xx` is the SPID of your connection).
3. Run any query: `DBI::dbGetQuery(conn, statement = "SELECT 1")` where `conn` is your connection object.

This will crash your R session.

### Next steps

I am very happy to help debug this further. However, I do not know how to do so. Is there a good way to see what is going on and why the R session is crashing / closing itself?

<details>
<summary>Session Info</summary>

```
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=en_US.UTF-8  LC_CTYPE=en_US.UTF-8    LC_MONETARY=en_US.UTF-8 LC_NUMERIC=C            LC_TIME=en_US.UTF-8    

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] frpm_1.3.4.40097

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11         urlchecker_1.0.1    compiler_4.2.3      later_1.3.1         AzureRMR_2.4.3      R.methodsS3_1.8.2   R.utils_2.12.2      remotes_2.4.2       prettyunits_1.1.1   profvis_0.3.8       tools_4.2.3         drat_0.2.3          digest_0.6.33       pkgbuild_1.4.2      pkgload_1.3.2.1    
[16] memoise_2.0.1       lifecycle_1.0.3     rlang_1.1.1         AzureAuth_1.3.3     shiny_1.7.4.1       cli_3.6.1           fastmap_1.1.1       stringr_1.5.0       desc_1.4.2          fs_1.6.2            vctrs_0.6.3         htmlwidgets_1.6.2   rappdirs_0.3.3      devtools_2.4.5      rprojroot_2.0.3    
[31] AzureKeyVault_1.0.5 glue_1.6.2          R6_2.5.1            processx_3.8.2      sessioninfo_1.2.2   purrr_1.0.1         callr_3.7.3         magrittr_2.0.3      promises_1.2.0.1    ps_1.7.5            ellipsis_0.3.2      htmltools_0.5.5     usethis_2.2.2       assertthat_0.2.1    mime_0.12
[46] xtable_1.8-4        renv_1.0.0          httpuv_1.6.11       keyring_1.3.1       AzureGraph_1.3.2    stringi_1.7.12      miniUI_0.1.1.1      cachem_1.0.8        crayon_1.5.2        R.oo_1.25.0        

```
</details>

**Comment by detule** [comment]
Hi -

I tried both with a local SQL Server instance, as well as with an Azure instance.  In both cases I KILL-ed the correct SPID (from a different/non-R session), and the subsequent `dbGetQuery` retrieved the simple result without an issue.

I am on a `debian` box, so it's possible there is a Windows contributing factor.  Aside from that, which driver are you using to connect? ( looks like i am using OEM driver 17.x )

**Comment by kummerer94** [comment]
Hi! Thank you for your answer. I appreciate the time you take to look into this.

I am on Windows 11 and I tried both with the 17.x and 18.x drivers. I was able to replicate the observed behaviour in both instances.

I have not tried this on Linux.

**Comment by detule** [comment]
Thanks for the update!  I can replicate.

Will follow up when fixed.

**Comment by kummerer94** [comment]
That is great news. Thank you so much for taking the time.

**Comment by detule** [comment]
Hey @kummerer94 

So I have some bad news: the segfault is not happening in any of our code - rather its in a call executed by the driver.  It's also the type of fault that we can't protect against - it's not an exception thrown that we can handle.

Only way to avoid is for us to check the status of the connection before every call:  as best as I can tell from reading the [docs on connection resiliency](https://learn.microsoft.com/en-us/sql/connect/odbc/connection-resiliency?view=sql-server-ver16),  we may have a way to detect when a connection is impaired via `SQLGetConnectiAttr`.  However this call is expensive, I think, since it would require a trip to the database, and I am hesitant to introduce that as a functional solution for what ultimately seems like a driver issue ( though sending a `SELECT 1` to the DB seems just as expensive as well ).

Alternatively, maybe can expose this status check in the return of say `dbGetInfo` - so that it's available on demand.  However, I think that is not something that will help with your issue with how these connections are checked for validity with `package:pool`.

**Comment by hadley** [comment]
@detule we can also attempt to escalate this to the folks who make our drivers. Let me follow up with you about that on slack.

**Comment by hadley** [comment]
@kummerer94 Based on the version numbers, it sounds like you're using the OEM driver from MS, which is not something we support. If you're a Posit customer we can get your set up with our pro drivers, which might either fix the problem, or if not, we can escalate to the people who make the drivers.

**Comment by kummerer94** [comment]
We are not a customer of Posit and therefore we are using the Microsoft ODBC Drivers. I was not even aware that there are other drivers specifically created by you / Posit for enterprise usage.
