### ISSUE TITLE
`dbConnect` segfaults for snowflake on R `4.3.1` (macOS Samona)

### ISSUE THREAD

**Issue by kpritam** [r-dbi/odbc#611]
### Issue Description and Expected Result
`dbConnect` throws `segfault` error on R version `4.3.1`.
I have tried switching to **R** version `4.2.3` and things work as expected.

### Database
Snowflake

### Reproducible Example
```r
# R --version
# R version 4.3.1 (2023-06-16) -- "Beagle Scouts"

# List Drivers returns configured dsn's
[ins] r|> odbc::odbcListDrivers()
#                name attribute                                                         value
# 1 ODBC Data Sources snowflake                                                     Snowflake
# 2         snowflake    Driver /opt/snowflake/snowflakeodbc/lib/universal/libSnowflake.dylib
# 3      ODBC Drivers Snowflake                                                     Installed

# Attempt to connect snowflake
con <- DBI::dbConnect(odbc::odbc(), dsn = "snowflake", uid = cfg$username, pwd = cfg$password)

# *** caught segfault ***
# address 0x2202, cause 'memory not mapped'

# Traceback:
# 1: connection_info(ptr)
#  2: OdbcConnection(dsn = dsn, ..., timezone = timezone, timezone_out = timezone_out,     encoding = encoding, bigint = # bigint, timeout = timeout,     driver = driver, server = server, database = database, uid = uid,     pwd = pwd, dbms.name = # dbms.name, attributes = attributes,     .connection_string = .connection_string)
#  3: .local(drv, ...)
#  4: DBI::dbConnect(odbc::odbc(), dsn = cfg$dsn, uid = cfg$username,     pwd = cfg$password)
#  5: DBI::dbConnect(odbc::odbc(), dsn = cfg$dsn, uid = cfg$username,     pwd = cfg$password)
```

### Works with **R** version `4.2.3`
```bash
R --version
R version 4.2.3 (2023-03-15) -- "Shortstop Beagle"
```
<img width="1089" alt="image" src="https://github.com/r-dbi/odbc/assets/17781757/fd56fde6-273b-4d9f-a31c-c8a71bbbc6e4">

### Note
`dbConnect` does work with `RODBC` on `4.3.1`

**Comment by detule** [comment]
Thanks:

* Is this an ARM or x86 Mac?
* What is the `Snowflake` driver version you are using?
* Did 4.3.1 work for you with Ventura?

I just tried 4.3.1 + Ventura + driver version `3.1.1` and was able to connect to a Snowflake instance on my x86 Mac.  Will try updating to `Sonoma` soon and see if I can replicate your issue.

**Comment by detule** [comment]
Hi - 

I believe this is an artifact from the fact that Homebrew [does not yet officially support Sonoma](https://brew.sh/2023/07/20/homebrew-4.1.0/).

While, I did not get a segfault, after the upgrade to Sonoma I saw:
```
[Snowflake][ODBC] (11560) Unable to locate SQLGetPrivateProfileString function: [Snowflake][Support] (50483) Could not load shared library, all attempted paths ("", "libodbcinst.dylib") failed
```
I was able to make the Snowflake connection work by editing `/opt/snowflake/snowflakeodbc/lib/universal/simba.snowflake.ini` and in particular specifying the full path to the shared library as the value to the `ODBCInstLib` key.

```
ODBCInstLib=/usr/local/lib/libodbcinst.dylib
```

**Comment by detule** [comment]
Hm - sounds like we have the exact same configuration: Intel Mac, both Sonoma, same driver however differing outcomes.

Can you try and installing `package:odbc` from source.  Something like
```
install.packages("odbc", type = "source")
```
After that, you may need to point the `ODBCSYSINI` environment variable to `/usr/local/etc` and try again.

**Comment by kpritam-tw** [comment]
Still getting the same error, 

<img width="1747" alt="image" src="https://github.com/r-dbi/odbc/assets/113362365/cb2762c9-39a2-446b-999a-0495cc29d801">

This does work without any changes as soon as I downgrade R to `4.2.2`. Not sure if there are any other ways to debug or get more logs.

![image](https://github.com/r-dbi/odbc/assets/113362365/3fd5d896-27db-4a55-9e10-2e5c276ff29a)

**Comment by detule** [comment]
Sorry, out of ideas ( other than maybe verifying it's not some strange interaction with `radian`, or trying to establish a connection without sourcing any scripts into the environment whatsoever ).  Checked with both the binary tarball from CRAN as well as the installed package from source and I can't see your issue on my x86/Sonoma Mac.

If we get reports of others seeing similar segfaults we can reopen the issue.
