### ISSUE TITLE
note need to configure `odbcinst.ini` in `setup.md` demo

### ISSUE THREAD

**Issue by simonpcouch** [r-dbi/odbc#637]
In `setup.md`, the server test setup only describes how to configure the `odbc.ini` but not `odbcinst.ini`.

https://github.com/r-dbi/odbc/blob/777b8636aeab4018962bef88084f533c23e7549b/setup.md#L26-L34

This doc should outline how to locate the newly installed driver and refer to it in `odbcinst.ini`.

I was able to locate the driver by running `brew info msodbcsql17`, navigating to the folder referred to in the output (for me, `/opt/homebrew/Cellar/msodbcsql17/17.10.5.1`), and copying the entry from the `odbcinst.ini` in that folder.

In that `brew info` output, I also see:

```
==> Options
--without-registration
        Don't register the driver in odbcinst.ini
==> Caveats
If you installed this formula with the registration option (default), you'll
need to manually remove [ODBC Driver 17 for SQL Server] section from
odbcinst.ini after the formula is uninstalled. This can be done by executing
the following command:
    odbcinst -u -d -n "ODBC Driver 17 for SQL Server"
```

If installing with `without-registration` set appropriately will drop the entry in the same `.ini` file that this package will look to, we should just set that option.

**Comment by simonpcouch** [comment]
Learnings from trying to make this work: there is not currently a native arm64 mssql container.

Also, I would guess that the second argument here:

https://github.com/r-dbi/odbc/blob/777b8636aeab4018962bef88084f533c23e7549b/setup.md#L47

should actually read `"sql1"`, given 

https://github.com/r-dbi/odbc/blob/777b8636aeab4018962bef88084f533c23e7549b/setup.md#L40

but can't test locally for now.

**Comment by detule** [comment]
I think second argument should match the name of the DSN entry in odbc.ini ---- so I think `MicrosoftSQLServer`

**Comment by detule** [comment]
Simon: I've found the[ pyodbc documentation on Drivers and Driver Managers](https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers) to be a good intro to the different actors in the ODBC connection stack.

**Comment by simonpcouch** [comment]
Much appreciated, @detule!
