### ISSUE TITLE
note that drivers may not be automatically entered in `odbcinst.ini` on install

### ISSUE THREAD

**Issue by simonpcouch** [r-dbi/odbc#638]
Much of the documentation I've found ([pyodbc docs](https://github.com/mkleehammer/pyodbc/wiki/Drivers-and-Driver-Managers#odbc-configuration-files-unix-only), [our docs](https://github.com/r-dbi/odbc/blob/777b8636aeab4018962bef88084f533c23e7549b/README.Rmd#L81-L98), for example) seems to suggest that `brew install`ing a driver will enter appropriate entries in the `odbcinst.ini` noted in `odbcinst -j` automatically. I've only seen this happen once after installing a few different drivers; it may be worth noting how to locate the install after `brew install`. I've been using `brew info` to get started.

**Comment by hadley** [comment]
Note the wrapper in https://github.com/r-dbi/odbc/issues/634#issuecomment-1846105882 that would be straightforward to adapt for any backend.
