### ISSUE TITLE
Look into apple + spark drive config issue

### ISSUE THREAD

**Issue by hadley** [r-dbi/odbc#651]
https://solutions.posit.co/connections/db/databases/databricks/#troubleshooting-apple-macos-users

Can we fix this automatically?

**Comment by detule** [comment]
Hey - yes I think so.

I thought about it very briefly: I am a fan of `homebrew`, but I wonder if it's worth trying to make the solution leverage the official CRAN/mac binary recipes, without the need for a third party application.  There is a pretty slick installer that might reduce installing the driver manager to something like :

```
source("https://mac.R-project.org/bin/install.R")
install.libs("unixodbc")
```

There are pros and cons - I am swamped until DEC 11, but can give it a shot after that.

**Comment by hadley** [comment]
Oh, interesting idea! That would simplify the odbc install problem. 

We'd still either need some hack for the ini file; either by supplying the value directly in the `dbConnect` call (I had some mixed results on whether this worked on not), automatically editing the `.ini` file, or figuring out how to get a fix pushed upstream.
