### ISSUE TITLE
add/update instructions for SQL Server test setup in `setup.md`

### ISSUE THREAD

**Issue by simonpcouch** [r-dbi/odbc#663]
The process to set up a Microsoft SQL Server is a bit different for M1, and we can also bump the versions on some of the installs.

Install Docker Desktop with:

```shell
brew install --cask docker
```

NOTE:
* You will need Docker 4.16 or higher
* You will need MacOS 13 Ventura (or higher)

For some reason I have trouble booting up `Docker.app` as usual, but the Docker Desktop app lives in `Docker.app > Show Package Contents > Contents > MacOS > Docker Desktop.app`.

For the driver and mssql install step,  bump to the most recent major driver version:

```shell
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
brew install msodbcsql18 mssql-tools
```

In `odbc.ini`, I ended up with:

```ini
[MicrosoftSQLServer]
driver = SQL Server Driver
Server = 127.0.0.1
port = 1433
Encrypt = no
```

The `Encrypt = no` seems to be key. In  `odbcinst.ini`:

```ini
[SQL Server Driver]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/homebrew/lib/libmsodbcsql.18.dylib
UsageCount=1
```

With dockers and the needed driver installed, I deployed the container with:

```shell
sudo docker run --platform linux/amd64 -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=BoopBop123!" \
   -p 1433:1433 --name sql1 --hostname sql1 \
   -d \
   mcr.microsoft.com/mssql/server:2022-latest
```

The `--platform` tag is correct for M1; if you see `Status: Exited (1)` in Docker Desktop or a warning about incompatible architectures, navigate to `Settings > General` and ensure that `Use Rosetta for x86/amd64 emulation on Apple Silicon` is checked. I'm not sure why we'd use `server:2022-latest` rather than 2018, but I see errors with 2018.

To connect via odbc, we need to pass the UID and PWD via the connection string; I tried to configure via `odbc.ini`, but it seems that's [not permitted](https://stackoverflow.com/questions/42387084/sql-server-odbc-driver-linux-username). U ise:

```r
mssql <- dbConnect(odbc::odbc(), dsn = "MicrosoftSQLServer", uid = "SA", pwd = "BoopBop123!")
```

**Comment by hadley** [comment]
Looks you need this before the install step:

```
brew tap microsoft/mssql-release https://github.com/Microsoft/homebrew-mssql-release
```

**Comment by simonpcouch** [comment]
> And bash doesn't seem to like ! in the password, so I dropped it.

Microsoft SQL Server requires special characters in the password, which might be part of the explanation: https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16

**Comment by simonpcouch** [comment]
> Should we be using msodbcsql18?

Yes, woops--typo.

**Comment by gaborcsardi** [comment]
FWIW there is also an `mssql-tools18` package, which MS suggests to install with `msodbcsql18`, but IDK if it makes any difference.

For the `!`, use a single quote instead of a double quote.
