### ISSUE TITLE
Error: Data source name too long

### ISSUE THREAD

**Issue by antlig** [r-dbi/odbc#686]
**Issue Description**
I just installed odbc 1.4.0 from CRAN, but now I'm having problems with Oracle databases. odbc::dbConnect() fails with the error indicated in the title. Everything works in version 1.3.5.

Error: nanodbc/nanodbc.cpp:1135: IM010 [Microsoft][ODBC Driver Manager] Data source name too long.
### Database
Oracle Database 19c Standard Edition
### Reproducible Example

```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), "DATAMART;UID=*****;PWD=*****")
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session. (You can delete your credentials, which TBH shouldn't really be in your connection string anyway, before pasting here).

**Comment by antlig** [comment]
Hi Hadley,
thanks for the reply, I reworked the reproducible example

``` r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), "dsn=******")
#> Error: nanodbc/nanodbc.cpp:1135: IM010
#> [Microsoft][Driver Manager ODBC] Data Source name too long.
```

<sup>Created on 2023-12-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Do either of these work?

```R
con <- dbConnect(odbc::odbc(), dsn="******")
con <- dbConnect(odbc::odbc(), .connection_string  = "dsn=******")
```

**Comment by antlig** [comment]
Hi,

the first option worked.

Thank you
