### ISSUE TITLE
Driver Keyword syntax error with new version of odbc with SQL SERVER

### ISSUE THREAD

**Issue by BenoitLondon** [r-dbi/odbc#696]
got this error suddenly with new odbc with either freeTDS and Microsoft drivers on linux

```
conn <- odbc::dbConnect(odbc::odbc(), dsn = "MSSQLTEST;usr=***;pwd=***")
Error: nanodbc/nanodbc.cpp:1135: 00000
[unixODBC][Driver Manager]DRIVER keyword syntax error 
```

my odbc file is

```
[MSSQLTEST]
Driver = /usr/lib64/libtdsodbc.so.0
Description = Connection to SQL server
Trace           = Yes
TraceFile       = /tmp/odbctest.trace
Server = ***
Database = ***
Port = ***
User = ***
Password = ***
```

Could not find any change that would change the connection process

Also, I can connect if I provide all the arguments instead of dsn.
It also workss fine with dsn for MYSQL and POSTGRE

**Comment by detule** [comment]
Hi - thanks for the report.

Can you try:
```
dbConnect(..., dsn = "MSSQLTEST", usr="<snip>", pwd="<snip")
```

**Comment by BenoitLondon** [comment]
was trying that before reading your message and yes this works....

**Comment by BenoitLondon** [comment]
so actually these work:
```
> conn2 <- RODBC::odbcConnect("MSSQLTEST", uid="**",pwd="**")
> dbConnect(..., dsn = "MSSQLTEST", usr="**", pwd="**")

> conn2 <- RODBC::odbcConnect("MSSQLTEST;uid=**;pwd=**")


```

but this doesn't:

```
conn <- odbc::dbConnect(odbc::odbc(), dsn = "MSSQLTEST;usr=***;pwd=***")
Error: nanodbc/nanodbc.cpp:1135: 00000
[unixODBC][Driver Manager]DRIVER keyword syntax error 
```

**Comment by detule** [comment]
Excellent.

The "dsn" argument is intended to point to the `Data Source Name` in your ini file - in your case this is `MSSQLTEST`.  I suspect it worked prior to https://github.com/r-dbi/odbc/commit/4379b1c211852df753fe7c7f0773fefb271f133f but I don't think that dsn="dsn;otherargs" is something we intentionally supported.

**Comment by BenoitLondon** [comment]
thanks for the link to the commit!

Is this a workaround? :
```
#'   Any argument values that contain `[]{}(),;?*=!@` will be "quoted" by
#'   wrapping in `{}`. You can opt-out of this behaviour by wrapping the
#'   value with `I()`.
```
how can I use the `I()` in my case?

**Comment by hadley** [comment]
@BenoitLondon you could do:

```R
conn <- odbc::dbConnect(odbc::odbc(), dsn = I("MSSQLTEST;usr=***;pwd=***"))
```

but that's fundamentally misleading since that's not actually a DSN.  So a better option would be to use the correct argument:

```R
conn <- odbc::dbConnect(odbc::odbc(), .connection_string = I("MSSQLTEST;usr=***;pwd=***"))
```

**Comment by BenoitLondon** [comment]
Thanks @detule and @hadley, very appreciated!

Unfortunately those still fail

```
> conn <- odbc::dbConnect(odbc::odbc(), dsn = I("MSSQLTEST;usr=**;pwd=**"))
Error: nanodbc/nanodbc.cpp:1135: 00000
[unixODBC][Driver Manager]DRIVER keyword syntax error

> conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "MSSQLTEST;usr=**;pwd=**")
Error: nanodbc/nanodbc.cpp:1135: 00000
[unixODBC][Driver Manager]Data source name not found and no default driver specified

> conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "dsn=MSSQLTEST;usr=**;pwd=**")
Error: nanodbc/nanodbc.cpp:1135: 00000
[FreeTDS][SQL Server]Unable to connect to data source 
[FreeTDS][SQL Server]Adaptive Server connection failed 
[FreeTDS][SQL Server]Adaptive Server connection failed

> conn <- odbc::dbConnect(odbc::odbc(), .connection_string = I("dsn=MSSQLTEST;usr=**;pwd=**"))
Error: nanodbc/nanodbc.cpp:1135: 00000
[FreeTDS][SQL Server]Unable to connect to data source 
[FreeTDS][SQL Server]Adaptive Server connection failed 
[FreeTDS][SQL Server]Adaptive Server connection failed
```

**Comment by hadley** [comment]
Ooops `I()` doesn't actually work 😞

**Comment by simonpcouch** [comment]
I think the second recommendation from Hadley is almost there, but you'd just need to specify the argument name of `dsn`. i.e. instead of:

``` r
conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "MSSQLTEST;usr=***;pwd=***")
```

you'd write:

``` r
conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "dsn=MSSQLTEST;usr=***;pwd=***")
```

**Comment by BenoitLondon** [comment]
> I think the second recommendation from Hadley is almost there, but you'd just need to specify the argument name of `dsn`. i.e. instead of:
> 
> ```r
> conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "MSSQLTEST;usr=***;pwd=***")
> ```
> 
> you'd write:
> 
> ```r
> conn <- odbc::dbConnect(odbc::odbc(), .connection_string = "dsn=MSSQLTEST;usr=***;pwd=***")
> ```

I tried this one  (3rd try in my last post) and it  fails. last one works meaning it's expecting the driver for some reason (although it is in my odbc.ini file , maybe because of the slashes...)

**Comment by BenoitLondon** [comment]
@simonpcouch your suggestion works if I use the driver name instead of the path in my .odbc.ini file  :+1: 
so I guess I ve found my solution

Thanks everyone!
