### ISSUE TITLE
odbcListDrivers() not finding registered drivers

### ISSUE THREAD

**Issue by gregorypenn** [r-dbi/odbc#709]
I am attempting to set up ODBC and it is unable to find my drivers. I have followed the guidance in the "Installing and Configuring Drivers" vignette, and I'm still stuck. If this is a simple case of user error and I should post on StackOverflow to ask for help instead of here, please just let me know.

My system setup is:

- Hardware: M2 Mac
- OS: Mac OS 14.2
- R.version: 4.3.2
- ODBC version: 1.4.1
- unixODBC version: 2.13.12

When I call `odbcListDrivers()`, I expect it to return a table with a single row for the single driver I have registered in `odbcinst.ini`, but instead it returns an empty table.

```
library(odbc)
odbcListDrivers()
#> [1] name      attribute value    
#> <0 rows> (or 0-length row.names)
```

I believe that I have unixODBC correctly installed. See the following terminal output for details.

```
% odbcinst -j
unixODBC 2.3.12
DRIVERS............: /opt/homebrew/etc/odbcinst.ini
SYSTEM DATA SOURCES: /opt/homebrew/etc/odbc.ini
FILE DATA SOURCES..: /opt/homebrew/etc/ODBCDataSources
USER DATA SOURCES..: /Users/gregory/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

I believe that I have a driver correctly registered. See the following for the contents of ` /opt/homebrew/etc/odbcinst.ini`.

```
% cat  /opt/homebrew/etc/odbcinst.ini
[ODBC Driver 18 for SQL Server]
Description=Microsoft ODBC Driver 18 for SQL Server
Driver=/opt/homebrew/lib/libmsodbcsql.18.dylib
UsageCount=1
```
It also appears that ODBC know where to find unixODBC on my system.

```
odbcListConfig()
#>                          drivers                       system_dsn 
#> "/opt/homebrew/etc/odbcinst.ini"     "/opt/homebrew/etc/odbc.ini" 
#>                         user_dsn 
#>       "/Users/gregory/.odbc.ini"

```

**Comment by simonpcouch** [comment]
I'm able to replicate this. Similar setup, though M1 chip.

With CRAN install via `install.packages("odbc")`:

``` r
nrow(odbc::odbcListDrivers())
#> 0
```

But, when installed from source with `pak::pak(r-dbi/odbc@v1.4.1)`:

``` r
nrow(odbc::odbcListDrivers())
#> 18
```

**Comment by detule** [comment]
Can you guys try manipulating your `ODBCSYSINI` environment variable to point to `/opt/homebrew/etc` ?

**Comment by gregorypenn** [comment]
@simonpcouch 

I reinstalled the dev version from source with `remotes::install_github("r-dbi/odbc")` and now it works.

```
odbc::odbcListDrivers()
#>                            name   attribute
#> 1 ODBC Driver 18 for SQL Server Description
#> 2 ODBC Driver 18 for SQL Server      Driver
#> 3 ODBC Driver 18 for SQL Server  UsageCount
#>                                     value
#> 1 Microsoft ODBC Driver 18 for SQL Server
#> 2 /opt/homebrew/lib/libmsodbcsql.18.dylib
#> 3                                       1

```

**Comment by simonpcouch** [comment]
@detule—yup, setting `ODBCSYSINI` fixes the issue with CRAN install.

(For folks who may have stumbled across this issue, that is running `Sys.setenv(ODBCSYSINI = "/opt/homebrew/etc")` before loading the odbc package.)

**Comment by detule** [comment]
Thanks @simonpcouch 

For some context: the CRAN built package is built against a statically linked `unixodbc` ( *not* provided by homebrew ) that has its configuration files elsewhere.  Those paths must bleed into our `.so`.

Possible alternatives are:
* Use the CRAN provided static distribution of `unixodbc`, rather than homebrew ( CRAN provides a very convenient installer ); or
* As above, manipulate the environment variables.

**Comment by gregorypenn** [comment]
Should I close this issue, or leave it open?

**Comment by detule** [comment]
I think we are good / you can close.

Thanks!

**Comment by hadley** [comment]
Is it too load to set the env var on package load? Or can we otherwise detect that we're not using the paths that `odbcListConfigs()` provides? This seems like it will be common failure mode, especially for odbc developers 😄

**Comment by simonpcouch** [comment]
I would totally support adding a few lines in `.onLoad()` to try and resolve that.🎄

**Comment by simonpcouch** [comment]
Some notes to self as I've tried to address this.

When installed from CRAN, `libs/odbc.so` has `ODBCSYSINI=[something]`, in my case `ODBCSYSINI=/opt/R/arm64/etc`. 

Finding the analogous, dynamically-linked version is a bit more difficult than we had thought when implementing `odbcListConfig()`, I guess. Other ways to locate that ODBCSYSINI setting could be in `dirname(system("odbc_config --odbcinstini", intern = TRUE))` OR by finding `define SYSTEM_FILE_PATH [something]` in `odbc_config.h` from `system("odbc_config --include-prefix", intern = TRUE)`.

> Is it too [late] to set the env var on package load? 

I'm still trying to understand how `odbc.so` is put together on build, but am hoping it's possible to set the `ODBCSYSINI` value to a function value (or a variable whose value we could update `.onLoad()`).

> Or can we otherwise detect that we're not using the paths that odbcListConfigs() provides?

It doesn't seem like the `ODBCSYSINI` entry that's written into `libs/odbc.so` is accessible after build. My thought here is that maybe we could somehow write that entry from `libs/odbc.so` into odbc's namespace as it's being built, and then check that it aligns (warning if not?) with the dynamically linked version `.onLoad()`?

**Comment by simonpcouch** [comment]
I guess another option is to just set `ODBCSYSINI` to `SYSTEM_FILE_PATH` in `.onLoad()` unless there's already an env variable with that name, regardless of the value in the statically linked unixodbc.

**Comment by simonpcouch** [comment]
I _think_ setting that value in `.onLoad()` does the trick. Some more details in #733.
