### ISSUE TITLE
DBI::dbAppendTable() Error in .local(conn, name, ...) : unused argument (exact = TRUE)

### ISSUE THREAD

**Issue by nauscj** [r-dbi/odbc#717]
``` r
library(reprex)
library(DBI)

# Set seed for reproducibility
set.seed(123)

# Choose a single date
single_date <- as.Date("2023-03-22")

# Repeat the date 10 times
dates <- rep(single_date, times = 10)

# Generate a vector of 10 random 5-digit numbers
random_numbers <- round(runif(10, min = 1e4, max = 1e5), digits = 0)

# Generate a vector of random order counts between 10 and 50
orders <- sample(x = 10:50, size = 10, replace = TRUE)

# Combine vectors into a data frame
df <- data.frame(date = dates, cust_id = random_numbers, orders = orders)

# Display the resulting data frame
print(df)
#>          date cust_id orders
#> 1  2023-03-22   35882     23
#> 2  2023-03-22   80947     34
#> 3  2023-03-22   46808     35
#> 4  2023-03-22   89472     36
#> 5  2023-03-22   94642     14
#> 6  2023-03-22   14100     36
#> 7  2023-03-22   57529     37
#> 8  2023-03-22   90318     18
#> 9  2023-03-22   59629     38
#> 10 2023-03-22   51095     44

# Establish Connection
con <- dbConnect(odbc::odbc(), "teradata_17.2", timeout = 5)

# Create Table
dbCreateTable(
  conn = con,
  name = Id(schema = "RSCHDB", table = "cust_orders"),
  df
  )
# Creates table, so I know there is a connection and I have write access to the database.

# Append Data to Table
dbAppendTable(conn = con, 
              name = Id(schema = "RSCHDB", table = "cust_orders"),
              value = df)
#> Error in .local(conn, name, ...): unused argument (exact = TRUE)
```

<sup>Created on 2024-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by nauscj** [comment]
I'll try again, but yesterday when I was trying to submit it with the reprex package our firewall wouldn't let me.

**Comment by nauscj** [comment]
Please let me know if adding the reprex did not work. The issue appears to be the odbc package. Yesterday I downgraded packages to make my updates and when I updated the packages to the new version it worked when only DBI was updated, but not when I updated odbc.

**Comment by hadley** [comment]
It looks like you only ran the last line in the reprex, instead of the whole example.

**Comment by nauscj** [comment]
My apologies, this is the first time submitting an issue. Let's try again. This is what I did. 
library(reprex)
reprex(input = "C:/Users/nauscj/Desktop/last_week_updates/example_db.R")

**Comment by hadley** [comment]
@nauscj that looks much better, thanks!

**Comment by hadley** [comment]
Could you please confirm that this simpler reprex gives you the same error?

```R
library(DBI)

con <- dbConnect(odbc::odbc(), "teradata_17.2", timeout = 5)

name <- Id(schema = "RSCHDB", table = "cust_orders")
df <- data.frame(x = 1, y = 2)

dbCreateTable(con, name, df)
dbAppendTable(con, name, df)
```

And if so, could you please also give me the result of running `traceback()`?

**Comment by nauscj** [comment]
9: odbcConnectionTables(conn, name = name, ..., exact = TRUE)
8: odbcConnectionTables(conn, name = name, ..., exact = TRUE)
7: dbExistsTable(conn, name = id_field(name, "table"), catalog_name = id_field(name, 
       "catalog"), schema_name = id_field(name, "schema"))
6: dbExistsTable(conn, name = id_field(name, "table"), catalog_name = id_field(name, 
       "catalog"), schema_name = id_field(name, "schema"))
5: dbExistsTable(conn, name)
4: dbExistsTable(conn, name)
3: stopifnot(dbExistsTable(conn, name))
2: dbAppendTable(con, name, df)
1: dbAppendTable(con, name, df)

**Comment by nauscj** [comment]
#' ---
#' output: reprex::reprex_document
#' ---

library(DBI)

con <- dbConnect(odbc::odbc(), "teradata_17.2", timeout = 5)

name <- Id(schema = "RSCHDB", table = "cust_orders")
df <- data.frame(x = 1, y = 2)

dbCreateTable(con, name, df)
dbAppendTable(con, name, df)
traceback()

**Comment by nauscj** [comment]
``` r
library(DBI)

con <- dbConnect(odbc::odbc(), "teradata_17.2", timeout = 5)

name <- Id(schema = "RSCHDB", table = "cust_orders")
df <- data.frame(x = 1, y = 2)

dbCreateTable(con, name, df)
dbAppendTable(con, name, df)
#> Error in .local(conn, name, ...): unused argument (exact = TRUE)
traceback()
#> No traceback available
```

<sup>Created on 2024-01-12 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by nauscj** [comment]
I finally got around to installing the dev version and did not have any problems writing to our databases. Thank you for your time and fixing the issue. I appreciate it.
