### ISSUE TITLE
Connection issues after 1.4.0 new default behavior of escaping passwords

### ISSUE THREAD

**Issue by wphampton** [r-dbi/odbc#718]
### Issue Description and Expected Result
When trying to connect to Oracle (as well as Intersystems Cache) using odbc 1.4.1 with passwords containing the characters targeted for escaping #656, I can not connect successfully without wrapping the password with `I()`. I'm confused at why this change in default behavior was just a minor version bump, but maybe more confused as to how my passwords with special characters were previously working without this necessary escaping. We have hundreds of these connection statements in all sorts of scripts and Shiny apps, it seems strange to have to wrap them all with `I()` so I feel I am missing something here or possibly this is a bug. With 1.4.0 it seems even wrapping with `I()` does not fix it, it just fails in all cases.  v1.3.5 works successfully with no wrapping of `I()` needed. Thanks! -Wes

### Database
Oracle Database 19c

### Reproducible Example
```r
library(odbc)
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "MyOracleDB", uid = "myusername", pwd = "My!SpecialPass")

Error: nanodbc/nanodbc.cpp:1138: IM006
[Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied
 
[Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed 
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
─ Session info ──────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.2 (2023-10-31 ucrt)
 os       Windows 10 x64 (build 19045)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       America/New_York
 date     2024-01-04
 rstudio  2023.09.1+494 Desert Sunflower (desktop)
 pandoc   NA
─ Packages ──────────────────────────────────────────────────────────────
 package     * version date (UTC) lib source
 DBI         * 1.2.0   2023-12-21 [1] RSPM (R 4.3.0)
 odbc        * 1.4.1   2023-12-21 [1] RSPM (R 4.3.0)
```
</details>

**Comment by atheriel** [comment]
Discussion in #616 seems to indicate that the ODBC spec requires escaping, but maybe Oracle's driver departs from the spec here. Could we have an Oracle-specific specialization for escaping like we do for some other features? Or is that not architecturally feasible?

**Comment by wphampton** [comment]
I honestly don't feel too knowledgeable here, I just know that it broke connections to two different database systems. I guess I was surprised no one was complaining and it made me wonder if I was doing something not mainstream in my usage of this package.

I saw the original work seemed to spawn from a complaint about Redshift I think, just wondering if we changed a long-standing default behavior in a highly used library trying to be compliant in an area where there are a lot different implementations. 

I think it would have been good to maybe have a new parameter to opt-in to the escaping, where the default is not to auto escape. Just my two cents, from a user who has benefitted greatly and freely from all the efforts of all the contributors. Thanks for listening! -Wes

**Comment by hadley** [comment]
Just confirming that your call generates this connection string: `dsn=MyOracleDB;uid=myusername;pwd={My!SpecialPass}`, which looks correct to me. I find it hard to believe that the Oracle odbc driver would completely deviate from the standard escaping, but stranger things have happened. 

@wphampton can you point me to the specific oracle odbc driver that you're using?

**Comment by wphampton** [comment]
Well, I could certainly be messing something up...I am puzzled as I'm not often the first to stumble on problems like this. Would feel better if someone outside my org confirmed this problem as well. I can just use the connection string without escaping, but just was surprised.

This works: `DBI::dbConnect(odbc::odbc(), .connection_string = "dsn=MyOracleDB;uid=myusername;pwd=MySpecialPass!"`

This fails: `DBI::dbConnect(odbc::odbc(), .connection_string = "dsn=MyOracleDB;uid=myusername;pwd={MySpecialPass!}"`
`Error: nanodbc/nanodbc.cpp:1138: IM006
[Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied`

It's failing for me on Windows, though I am using an old driver for Oracle 11g 11.02.00.01.

However, it's also exhibiting the same behavior within the Docker rocker image when I install these drivers from the oracle website, which I believe are pretty current:
https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-basiclite-linux.x64-21.1.0.0.0.zip
https://download.oracle.com/otn_software/linux/instantclient/211000/instantclient-odbc-linux.x64-21.1.0.0.0.zip

**Comment by hadley** [comment]
Oracle docs (https://docs.oracle.com/en/database/oracle/oracle-database/19/adfns/odbc-driver.html#GUID-F141C2E1-BA44-4399-B72A-3B1FBA2BC750) have this as an example `DRIVER={Oracle ODBC Driver};UID=Kotzwinkle;PWD=whatever;DBQ=instl_alias;DBA=W;` so looks like `{}` works in at least some places.

@wphampton would you mind trying these connection strings?

```R
DBI::dbConnect(odbc::odbc(), .connection_string = "dsn={MyOracleDB};uid=myusername;pwd=MySpecialPass!"
DBI::dbConnect(odbc::odbc(), .connection_string = "dsn=MyOracleDB;uid={myusername};pwd=MySpecialPass!"
```

**Comment by hadley** [comment]
I don't know how much I trust an 8 year old SO answer, but https://stackoverflow.com/a/40092628/16632 implies that you use double quotes.

**Comment by wphampton** [comment]
Yes, totally happy to try.

This does not work:
`DBI::dbConnect(odbc::odbc(), .connection_string = "dsn=MyOracleDB;uid={myusername};pwd=MySpecialPass!"`
`Error: nanodbc/nanodbc.cpp:1138: IM006
[Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied`

Removing the curly braces works as it did earlier.

I also tried wrapping the DSN in curly braces:
``DBI::dbConnect(odbc::odbc(), .connection_string = "dsn={MyOracleDB};uid=myusername;pwd=MySpecialPass!"``
`Error: nanodbc/nanodbc.cpp:1138: IM002
[Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified `

Which I suppose just means I don't have an ODBC entry of that name...guessing if I put curly braces in the actual ODBC entry name it might match.

**Comment by hadley** [comment]
@wphampton thanks! This seems like it's a bug in the Oracle ODBC driver, which I think means auto-escaping isn't a viable strategy 😞

**Comment by capitantyler** [comment]
I used this before mi DSN stopped to work on odbc@1.4.1, and worked:  double {{  in the driver's name
```

mode <- "conn_str"
usr <- "myusr"
pwd <- "mypwd"
conn_str <- "Driver={{Oracle en OraClient12Home1}};DBQ=ALIAS_DB_blablabla.com.ar:1521/SOPSRV;UID={usr};PWD={pwd}"

if(mode == "conn_str"){           
    con <- DBI::dbConnect(
       drv = odbc::odbc(), 
      .connection_string = glue::glue(conn_str )
    )
 }
```

Note that the Driver is not a variable, it is read as {Oracle en OraClient12Home1} by the ODBC Driver

**Comment by wphampton** [comment]
@capitantyler I tried double {{ }} on the password and it gave me the same error, but it's interesting that you were having problems with the Driver even though there are no special characters in there.

@hadley Thank you for investigating. Just to add more context, we're experiencing the same behavior with our ODBC connections to **Intersystems Cache** (https://www.intersystems.com/cache/) and it's replacement **Intersystems IRIS** (https://www.intersystems.com/data-platform/) which power the health/medical systems (e.g. Epic) at our hospital.

I tested a connection string against **Microsoft SQL Server**, and it was successful -- the curly braces around the password do not negatively affect login, so it seems SQL Server might be fine as it stands. 

I also tested an **ASE Sybase** connection, however it did _not_ succeed when wrapping the password with curly braces.

So, it seems a mixed bag in my experience so far. I do hope that before any changes are made someone on your core team can perhaps confirm some of these observations, I just don't want to be the single cause of rework, but I did want to report the behavior. Happy to help test.

Wes

**Comment by hadley** [comment]
@capitantyler it looks like that's because you're using glue

**Comment by WilDoane** [comment]
Replicated the failure with MS SQL Server 2019. May depend on the characters in the passphrase: { } or \ may be issues. Wrapping the passphrase in I(passphrase) resolved it.

**Comment by hadley** [comment]
@WilDoane can you please provide a reprex. This issue is about problems with Oracle, not SQL server.

**Comment by WilDoane** [comment]
@wphampton noted: "I tested a connection string against Microsoft SQL Server, and it was successful -- the curly braces around the password do not negatively affect login, so it seems SQL Server might be fine as it stands."

I posted to disagree... under some conditions.

On Windows 11 connecting to a remote MS SQL Server, behavior changed with the odbc 1.4.1 release and appears to be the same escaping issue.

```library(odbc)
library(DBI)
```

Success (simple password):
```
conn <- DBI::dbConnect(odbc::odbc(),
                   Driver = "ODBC Driver 18 for SQL Server",
                   Server = "sampleserver",
                   Database = "sampledb",
                   UID = "testuser",
                   PWD = "testpassword",
                   TrustServerCertificate = "yes"
    )
```

Fails (note the changed password):
``` 
conn <- DBI::dbConnect(odbc::odbc(),
                   Driver = "ODBC Driver 18 for SQL Server",
                   Server = "sampleserver",
                   Database = "sampledb",
                   UID = "testuser",
                   PWD = "test}}password",
                   TrustServerCertificate = "yes"
    )
```

The error message: 

```
Attempt to connect to SQL Server failed.
nanodbc/nanodbc.cpp:1138: 01S00
[Microsoft][ODBC Driver Manager] Invalid connection string attribute 
```


Success (note the use of `I( )` ):
```
conn <- DBI::dbConnect(odbc::odbc(),
                   Driver = "ODBC Driver 18 for SQL Server",
                   Server = "sampleserver",
                   Database = "sampledb",
                   UID = "testuser",
                   PWD = I("test}}password"),
                   TrustServerCertificate = "yes"
    )
```

Windows 11
RStudio 2023.12.0 build 369
DBI v1.20
odbc v1.41

**Comment by simonpcouch** [comment]
I can reproduce @WilDoane's issue.

``` r
library(odbc)
library(DBI)
 
con <- dbConnect(
  odbc::odbc(), 
  dsn = "MicrosoftSQLServer", 
  uid = "SA", 
  pwd = "Gnarly}}Pass12"
)
#> Error: nanodbc/nanodbc.cpp:1138: 00000
#> [Microsoft][ODBC Driver for SQL Server][SQL Server]Login failed for user 'SA'.

con <- dbConnect(
  odbc::odbc(), 
  dsn = "MicrosoftSQLServer", 
  uid = "SA", 
  pwd = I("Gnarly}}Pass12")
)
```

<sup>Created on 2024-01-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I don't seem to have trouble with special characters in passwords other than curly braces.

DBI 1.20, odbc 1.41, MacOS aarch64, SQL Server 2022, deployed on docker with:

```sh
sudo docker run \
  --platform linux/amd64 \
  -e "ACCEPT_EULA=Y" \
  -e 'MSSQL_SA_PASSWORD=Gnarly}}Pass12' \
  -p 1433:1433 \
   --name sql1 \
   --hostname sql1 \
   -d mcr.microsoft.com/mssql/server:2022-latest
```

**Comment by erinsteiner-NOAA** [comment]
I can also reproduce the issue:

```
DBI::dbConnect(odbc::odbc(),
  UID    = "erin",
  PWD    = "something***",
  dsn    = "oracleDB")

```
```
Error: nanodbc/nanodbc.cpp:1138: IM006
[Oracle][ODBC][Ora]ORA-01017: invalid username/password; logon denied

[Microsoft][ODBC Driver Manager] Driver's SQLSetConnectAttr failed
```
VSCode: 1.85.1 (user setup)
OS: Windows_NT x64 10.0.19045
R version 4.3.2 (2023-10-31 ucrt)
DBI 1.2.0
odbc 1.4.1

**Comment by hadley** [comment]
@WilDoane what about a `;` in the password? Do you know how to escape that so it work in the connection string?

**Comment by WilDoane** [comment]
In general, I think you're stuck with content-sensitive delimiter collision checking, aqs far as I've every understood the MS dox:

* if PWD contains no punctuation characters, OK: `abc123`
* if PWD contains leading or trailing whitespace, delimit it: `  abc123  ` -> `{  abc123  }` or `'  abc;123  '` or `"  abc;123  "`
* if PWD contains semicolon, delimit it: `{abc;123}` or `'abc;123'` or `"abc;123"`
* if PWD contains punctuation characters, delimit PWD: `abc!123` -> `{abc!123}` or `'abc!123'` or `"abc!123"`
* if PWD contains the delimiter you intend to use, choose a different delimiter: `{abc}123}` -> `"abc}123"` or `"abc"123"` -> `'abc"123'` etc
* if PWD contains all the delimiters, use double quote and double the double-quotes in PWD: `"abc'"};123"` -> `"abc'""};123"`

You might get away with doubling the included delimiter in general, but I haven't tested that or noticed it as approved in the dox: {abc}}123} (maybe‽)

Always double any existing double-quotes and then use double quote as delimiters seems to be the safest answer.

**Comment by hadley** [comment]
Thanks @WilDoane. My read of the ODBC docs is that even `"` isn't a standard delimiter, so I don't want to rely on that for other backends. I _suspect_ doubling the delimiter is probably reasonably safe as that's how ANSI SQL handles escapes in character literals, but this thread has taught me that for ODBC reasonably safe just means that some driver is bound to be unsafe.

But while I was walking the dogs I think I came up with an approach that gives us most of the benefits of automatic escaping without the downsides — just warn the user when one of the values contains a character that's likely to need escaping. Something like this:

```R
dbConnect(odbc::odbc(), user = "user name")
#> Warning: 
#> `user` parameter uses a special character and may require escaping:
#>  i If the connection worked, escaping isn't needed and you can use `I()` to suppress this warning.
#>  i Otherwise, wrap the value in `odbc_escape()` to automatically handle special characters.
```

**Comment by erinsteiner-NOAA** [comment]
@hadley I can't quite tell from your proposed solution - does it rely on trying to connect to DB to find out that the connection doesn't work and there is a character that requires escaping? If so, at least on our system, you could easily get locked out of your account (only three attempts allowed) before noticing the warning and implementing the workaround.

**Comment by hadley** [comment]
@erinsteiner-NOAA this is the best we can do given that some backends (like Oracle) don't follow the ODBC standard.,

**Comment by WilDoane** [comment]
@erinsteiner-NOAA Also worth noting (perhaps), @hadley's solution is not an ADDITIONAL probe of the DB server just to test whether the username/password needs escaping. It's an honest attempt to connect to the DB, which may fail, and the warning is just a client-side convenience to tell the programmer what they may need to do, if the connection does fail.

**Comment by wphampton** [comment]
I don't fully understand the improvement that was originally intended or the scope of the original problem it was trying to solve, but this seems like a situation where the fix of auto-escaping has a deeper impact that the original problem. Is there a need to do any auto-escaping in this situation -- for the odbc library to step in and do anything here? Couldn't this be an opt-in situation instead of opt-out? If you have a password or parameter with special characters then either escape it yourself, or ask the odbc library to attempt to escape it (if that feature is developed). For everyone else it will just pass the parameters exactly as you enter them, which is likely what most people are expecting. Even having to type `I()` to make a warning go away is suboptimal in my opinion. As much as we might want the opposite, it seems that there is not enough consistency in how drivers handle ODBC calls (not just Oracle) to necessitate a change in the default historical behavior. 

I'm glad there are so many hard working, forward-thinking people in the R space, and I at least now know how to work around this issue whichever direction the library goes. -Wes

**Comment by hadley** [comment]
The problem I am worried about is folks who have special characters in their passwords who don't know anything about ODBC escaping rules. If you're in that situation it's extremely difficult to find out why your connection is failing. I think that's worth a little extra typing for the folks who do understand the problem.

**Comment by wphampton** [comment]
Well, I certainly respect your position and have personally benefited great amounts from the helps like this in many R libraries. Perhaps the check for special characters and the suggested warning/info message above would be more appropriate on _failed_ connections only?

**Comment by hadley** [comment]
@wphampton while that would be possible, it would substantially complicate the code and I don't think it's worth it.

**Comment by wphampton** [comment]
Based on the varying behavior among ODBC drivers (which we can't control and are not drivers of that change) and the observations and opinions above, my personal opinion now is:

1. These helpful connection tips about special characters should move to the documentation for the `odbc` library, and perhaps be considered as part of `DBI::dbConnect()` function docs.
2. No auto-escaping should be done due to inconsistent behavior in ODBC drivers. I'd argue a correctly typed password rendered invalid by this library is far more confusing and frustrating than a new user learning for the first time that passwords might need to be escaped. How does one even troubleshoot that without knowing what connection string actually got sent?
3. An opt-in parameter or helper function like `odbc_escape()` as Hadley mentioned above would likely be helpful.
4. No "warnings" should display for normal use (there's no imminent danger). There are endless tips we could provide every time someone uses a function, let's not add unnecessary noise. Helpful hints when _connection errors occur_ is certainly welcome, but sounds complicated in this case. If it's not important enough to push through that barrier then I think that should give us some indication of the value here.

I don't know what is the most common use cases are for using this library, but I know we have a couple hundred usages of `dbConnect(odbc(), ...)` across many various scripts and apps and a change to the default behavior (and on a minor version bump) is not trivial. I think in my practice I will encourage usage of the `.connection_string` parameter going forward, to avoid future problems. I was naïve and didn't realize that passing parameters like username and password were at risk of mutation like this, so I think a direct route is better if the parameter values are subject to changing. -Wes

**Comment by hadley** [comment]
@wphampton thanks for sharing your thoughts. I have a plan forward, and while I appreciate your detailed feedback, I don't think it's going to change my mind at this time.

**Comment by wphampton** [comment]
@hadley I appreciate the dialogue, thanks for your hard work.

**Comment by hadley** [comment]
Based on https://www.connectionstrings.com/formating-rules-for-connection-strings/, I'm going to try using quotes instead of `{}`.

@wphampton I'll also constrain the warning to character that are most like to need escaping (i.e. `{`, `}`, `=`, `;`, or ` `).

**Comment by hadley** [comment]
I finally found the spec for the connection string at https://learn.microsoft.com/en-us/openspecs/sql_server_protocols/ms-odbcstr/13b4e848-b36c-4b11-acce-d6bf199d5391. It doesn't mention using single or double quotes at all, but given my experiences so far, I'm more inclined to follow the practical advice from connectionstrings.com.
