### ISSUE TITLE
Update issue template?

### ISSUE THREAD

**Issue by ThomasSoeiro** [r-dbi/odbc#739]
The issue template currently reads as:

> ```r
> library(odbc)
> library(DBI)
> con <- dbConnect(odbc::odbc(), dsn = "PostgreSQL")
> # ...
> ```

Maybe `library(odbc)` should be removed?

Note: Here is a [related question](https://stackoverflow.com/q/75657373) on SO.

**Comment by hadley** [comment]
Good idea, thanks!
