### ISSUE TITLE
id_field maybe should use names provided by DBI::Id instead of using order?

### ISSUE THREAD

**Issue by meztez** [r-dbi/odbc#762]
``` r
id <- DBI::Id(catalog = "BOB", table = "HENRY")
id@name[["catalog"]]
#> [1] "BOB"
odbc:::id_field(id, "catalog")
#> NULL
odbc:::id_field(id, "schema")
#> [1] "BOB"
```

<sup>Created on 2024-02-20 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

In this case the catalog gets mapped to the schema. There is probably a good reason. I just get confused when things get remapped.

**Comment by hadley** [comment]
I think the naming of `Id()` was poorly thought out and we're generally moving away from it. We could certainly make this an error if needed, but my sense is that it's sufficiently uncommon to not be worth it.
