### ISSUE TITLE
Add support for `dsn` argument to `databricks()`

### ISSUE THREAD

**Issue by blairj09** [r-dbi/odbc#775]
An ODBC connection from R can either create the connection string manually via function arguments to `odbc()` or pass in a DSN:
```r
con <- DBI::dbConnect(odbc::odbc(), dsn = "My Databricks DSN")
```
However, `odbc::databricks()` doesn't support a `dsn` argument:
```r
> con <- dbConnect(
+   odbc::databricks(),
+   dsn = "databricks"
+ )
Error in `.local()`:
! One of `httpPath` or `HTTPPath` must be supplied.
Backtrace:
 1. DBI::dbConnect(odbc::databricks(), dsn = "databricks")
 2. odbc::dbConnect(odbc::databricks(), dsn = "databricks")
 3. odbc (local) .local(drv, ...)
```

**Comment by hadley** [comment]
What are you looking for here? One of the main drivers of the `databricks()` helper was to generate the DSN so that you don't have to 😄

**Comment by simonpcouch** [comment]
Going to go ahead and close—feel free to holler if you'd like to revisit and we can reopen.

**Comment by blairj09** [comment]
Apologies for the delay - my thinking here was this:
One of the main benefits of `databricks()` is the ability to easily use the Databricks credentials managed by Posit Workbench when connecting to Databricks. I'm wondering if there's value in being able to define a DSN that includes connection details _except_ for authentication and then allow `databricks()` to supply those credentials alongside DSN details making a connection.

The more I think about this, the more it feels like this is probably an anti-pattern for DSNs, which are meant to be centrally defined and managed. If a user wants to use user credentials for access, they should define the entire connection. To Hadley's point, this is what `databricks()` already does. I'm fine to keep this closed :grin:
