### ISSUE TITLE
Package hex logo

### ISSUE THREAD

**Issue by blairj09** [r-dbi/odbc#821]
Given the significance of this package in the R community, it would be great to see it include a [hex logo](https://github.com/rstudio/hex-stickers).

See @simonpcouch comment in #626:

              re: `usethis::use_tidy_logo()`, should this package have a hex? Let's spin this into a new issue if so.

_Originally posted by @simonpcouch in https://github.com/r-dbi/odbc/issues/626#issuecomment-1829995399_

**Comment by simonpcouch** [comment]
Thanks for opening the issue—looks like I forgot to do so when closing!

I'm game to spend a couple hours in Illustrator putting something together (or we can get in touch with a contractor). Any ideas/inspiration on what it ought to look like?

**Comment by edgararuiz** [comment]
Here are a couple of suggestions: 

![odbc (1)](https://github.com/r-dbi/odbc/assets/77294576/81b563ea-f138-4d64-8655-5f3a6bb19efc)
![odbc (2)](https://github.com/r-dbi/odbc/assets/77294576/c78df91e-e939-4e17-89f6-13ecdf4b433b)

**Comment by simonpcouch** [comment]
Loooove these so much! My preference is toward the blue option.

**Comment by hadley** [comment]
LGTM!!
