### ISSUE TITLE
Syntax fail on upload to Impala database

### ISSUE THREAD

**Issue by gloopy** [r-dbi/odbc#83]
### Issue Description and Expected Result
Write Data frame to Imapa fails at row 1024 with 

Error in result_insert_dataframe(rs@ptr, values) : 
  nanodbc/nanodbc.cpp:1587: HY000: [Cloudera][ImpalaODBC] (110) Error while executing a query in Impala: [HY000] : AnalysisException: Target table 'test.odbc_largetest' is incompatible with source expressions.
Expression 'cast('5.04648303985596À€' as string)' (type: STRING) is not compatible with column 'esp_flow_rate' (type: DOUBLE) 

however the first 1023 were written ok.
### Database
Cloudera Impala

### Reproducible Example

Example:
```r
library(odbc)
library(DBI)

connect_impala_odbc <- function(db = NULL){
  user <- options()$user
  pass <- options()$pass

  if (is.null(db) ) {
    db <- "default"
    warning("Default Database selected")
  }

  con <- tryCatch(odbc::dbConnect(odbc::odbc(),

                   driver = "Cloudera ODBC Driver for Impala",
                   database = db,
                   uid = user,
                   pwd = pass,
                   host = "host",
                   port = 25004),

     error = function(e){

       #debug
       print("Connection failed")
                     warning(e)
                     return(FALSE)
                   })
        #debug
        print("Connection made")

  return(con)
}



con <- connect_impala_odbc(db = database)
print(paste0("rowcount:",nrow(table)))

 dbWriteTable(con,tablename,table,overwrite = overwrite)
```

<details>
<summary>Session Info</summary>

```r
devtools::session_info()
#> setting  value                       
 version  R version 3.3.3 (2017-03-06)
 system   x86_64, mingw32             
 ui       RStudio (1.0.143)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Denver              
 date     2017-06-29                  

Packages --------------------------------------------------------------------------------------
 package   * version    date       source                   
 base      * 3.3.3      2017-03-06 local                    
 bit         1.1-12     2014-04-09 CRAN (R 3.3.2)           
 bit64       0.9-7      2017-05-08 CRAN (R 3.3.3)           
 blob        1.1.0      2017-06-17 CRAN (R 3.3.3)           
 datasets  * 3.3.3      2017-03-06 local                    
 DBI       * 0.7        2017-06-18 CRAN (R 3.3.3)           
 devtools    1.13.2     2017-06-02 CRAN (R 3.3.3)           
 digest      0.6.12     2017-01-27 CRAN (R 3.3.3)           
 graphics  * 3.3.3      2017-03-06 local                    
 grDevices * 3.3.3      2017-03-06 local                    
 hms         0.3        2016-11-22 CRAN (R 3.3.3)           
 memoise     1.1.0      2017-04-21 CRAN (R 3.3.3)           
 methods   * 3.3.3      2017-03-06 local                    
 odbc        1.1.0.9000 2017-06-29 local (rstats-db/odbc@NA)
 Rcpp        0.12.11    2017-05-22 CRAN (R 3.3.3)           
 rJava       0.9-9      2017-03-30 local                    
 RJDBC       0.2-6      2017-03-31 local                    
 rlang       0.1.1      2017-05-18 CRAN (R 3.3.3)           
 stats     * 3.3.3      2017-03-06 local                    
 tibble      1.3.3      2017-05-28 CRAN (R 3.3.3)           
 tools       3.3.3      2017-03-06 local                    
 utils     * 3.3.3      2017-03-06 local                    
 withr       1.0.2      2016-06-20 CRAN (R 3.3.3)     
```
</details>

Error Data

"","surface_pad","drain_area","well_pair_id","tag_entity_identifier","measurement_date","esp_flow_rate","esp_frequency","hour_num","minute_num","prod_heel_press","prod_toe_press","steam_inj_heel_press","surf_steam_inj_heel_choke_open","surf_steam_inj_heel_flow","surf_steam_inj_heel_press","surf_steam_inj_toe_choke_open","surf_steam_inj_toe_flow","surf_steam_inj_toe_press"
"1","LL-013","LL-013","LL-013-06","LL-013-06","2016-04-28",8.02054500579834,44.3806495666504,19,8,946.036315917969,1697.22094726562,1654.21203613281,5,0,1640.85095214844,30,0,1993.86096191406

Thanks

**Comment by gloopy** [comment]
Hi I have run it though a logging process and have confirmed that the first 1024 rows have valid insert statements. However the second batch has  a incorrect insert statement.
`Jun 30 08:05:57.817 DEBUG 9060 ImpalaTCLIServiceThreadSafeClient::ExecuteStatement: TExecuteStatementReq
sessionHandle.sessionId.guid = 674a158a8e22432ba0409e5088035e82
statement = INSERT INTO "test"."odbc_largetest"(
"surface_pad", 
"drain_area", 
"well_pair_id", 
"tag_entity_identifier", 
"measurement_date", 
"esp_flow_rate", 
"esp_frequency",
"hour_num",
"minute_num", 
"prod_heel_press", "prod_toe_press", "steam_inj_heel_press", "surf_steam_inj_heel_choke_open", "surf_steam_inj_heel_flow", "surf_steam_inj_heel_press", "surf_steam_inj_toe_choke_open", "surf_steam_inj_toe_flow", "surf_steam_inj_toe_press") 
VALUES (
CAST('LL-010' AS STRING), 
CAST('LL-010W' AS STRING), 
CAST('LL-010-04' AS STRING), 
CAST('LL-010-04' AS STRING), 
CAST('2016-05-03' AS STRING), 
CAST('0.000760000024457
runAsync = true`
#Error is here however the rest of the statement is not in the log .
#I am guessing that it throws a parse error Exception of some kind 
Error Message
Expression 'cast('0.000760000024457À€' as string)' (type: STRING) is not compatible with column 'esp_flow_rate' (type: DOUBLE) 

Thanks
Drystan

**Comment by aschmu** [comment]
FWIW, the implyr package connects to Impala databases through the DBI interface.

**Comment by jimhester** [comment]
As mentioned I would recommend using [implyr](https://github.com/ianmcook/implyr) package, which uses DBI / odbc as one of the backends when dealing with impala.

**Comment by ValeriVoev** [comment]
As far as I can see in the `implyr` documentation, the `copy_to` function only handles data frames up to 1000 rows (https://rdrr.io/cran/implyr/man/copy_to.html) - that will not apply in the majority of the cases.
