### ISSUE TITLE
helpers to open `.ini` files for editing

### ISSUE THREAD

**Issue by simonpcouch** [r-dbi/odbc#839]
Nearly every time I use `odbcListConfig()`, I end up actually wanting `file.edit(unname(odbcListConfig()[1]))` or `file.edit(unname(odbcListConfig()[2]))`. Should we extract that out into `odbcEditDrivers()` / `odbcEditSystemDSN()` or similar? `odbcConfigure*()`?

**Comment by hadley** [comment]
Oooh, that would be nice.
