### ISSUE TITLE
dbDataType chooses `VARCHAR(255)` even when `nchar` > 255

### ISSUE THREAD

**Issue by metanoid** [r-dbi/odbc#841]
For a connection of type `NetezzaSQL`, the `dbDataType` function returns `"VARCHAR(255)"` for seemingly all character vectors, regardless of the number of characters of the longest string in that vector

```r
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "Netezza")
test <- paste0(rep("a", 1000), collapse = "")
inferred_type <- dbDataType(con, test)
```
This returns: `"VARCHAR(255)"` even though there are clearly more than 255 characters required

**Comment by detule** [comment]
Hi @metanoid:

I don't have a `Netezza` instance around so shooting from the hip a bit.  Do you have the ability to test a development branch?  If so, can you see if [this version](https://github.com/detule/odbc/tree/testing/netezzaDataType) performs better with your mini example?

Thanks

**Comment by metanoid** [comment]
Hi,

Thanks for trying!  I think something is missing from the commit.  See output message:

``` r
devtools::load_all(".")

#>ℹ Loading odbc
#>Error in add_classes_to_exports(ns = nsenv, package = package, exports = exports,  : 
#>  in package ‘odbc’ classes NetezzaSQL were specified for export but not defined
#>In addition: Warning message:
#>package ‘testthat’ was built under R version 4.3.3 
```

**Comment by detule** [comment]
Sorry about that @metanoid.
Should be better now, hopefully.  Let me know what you find.

Thanks again for testing.

**Comment by metanoid** [comment]
It works!
```r
library(DBI)
con <- dbConnect(odbc::odbc(), dsn = "Netezza")
test <- paste0(rep("a", 1000), collapse = "")
inferred_type <- dbDataType(con, test)


#"varchar(1000)"
```

I'd be interested to hear why this works?  

Thanks!
