### ISSUE TITLE
dbWriteTable uses `BIT` datatype instead of `BOOL`

### ISSUE THREAD

**Issue by metanoid** [r-dbi/odbc#849]
When the `dbms.name` is `NetezzaSQL` then `dbWriteTable` should write a logical TRUE/FALSE data column as type `BOOL` as per this list of supported data types: https://www.ibm.com/docs/en/netezza?topic=vc-data-types-aliases

Instead, it seems to be trying to use the `BIT` datatype, which is not supported by Netezza.

Example:
```r
a = data.frame(Test = runif(100) > 0.5)
dbWriteTable(n_con, "TEST_DELETE", a)
```
results in
```r
Error in `dbWriteTable()`:
! ODBC failed with error HY000 from .
✖ ERROR: transformColumnType: error reading type 'BIT'
• <SQL> 'CREATE TABLE "TEST_DELETE" (
•  "Test" BIT
• )
• '
```

**Comment by detule** [comment]
Thanks!

Would you be willing, once again to help us test?

https://github.com/detule/odbc/tree/netezza/odbcDataType_bool

Thanks again

**Comment by metanoid** [comment]
Working, thank you!
