### ISSUE TITLE
Teradata Database Schema Not Accessible 

### ISSUE THREAD

**Issue by chrisg1536** [r-dbi/odbc#98]
### Teradata Database Tree Not Visible in Rstudio's Connection Pane and Through Function Calls 

`odbcListObjects`, `odbcListObjectTypes`, and `dbConnect()` all return:

```r
warning messages from top-level task callback '1'
Warning message:
Could not notify connection observer. nanodbc/nanodbc.cpp:4274: HYC00: [Teradata][ODBC Teradata Driver] Catalogs Not Supported  
```

Ultimately would like to view my server's database tree in the new connection pane in Rstudio's upcoming 1.1.x release. I initially submitted this issue to Rstudio here:

https://support.rstudio.com/hc/en-us/community/posts/115007215007-Using-Connections-Rstudio-Preview-Version-1-1-322-with-Teradata

### Database
Teradata 15.10.04.06

### Reproducible Example

```r
library(DBI)
con <- dbConnect(odbc::odbc(), "TDPRA")
# nor do the following commands work after connecting:
odbcListObjects(con)
odbc::odbcListObjectTypes(con)
```

<details>
<summary>Session Info</summary>

```r
setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.1.329)           
 language (EN)                        
 collate  English_United States.1252  
 tz       America/New_York            
 date     2017-08-08                  

Packages ------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package       * version    date       source                         
 bit             1.1-12     2014-04-09 CRAN (R 3.3.2)                 
 bit64           0.9-7      2017-05-08 CRAN (R 3.4.0)                 
 blob            1.1.0      2017-06-17 CRAN (R 3.4.1)                 
 DBI           * 0.7        2017-06-18 CRAN (R 3.4.1)                 
 devtools        1.12.0     2016-06-24 CRAN (R 3.3.1)                 
 digest          0.6.12     2017-01-27 CRAN (R 3.3.2)                 
 hms             0.3        2016-11-22 CRAN (R 3.3.2)                 
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.1)                 
 odbc          * 1.1.1.9000 2017-08-04 Github (rstats-db/odbc@4aa0629)
 Rcpp            0.12.12    2017-07-15 CRAN (R 3.4.1)                 
 RevoUtils       10.0.4     2017-05-05 local                          
 RevoUtilsMath * 10.0.0     2017-04-19 local                          
 rlang           0.1.1      2017-05-18 CRAN (R 3.4.1)                 
 tibble          1.3.3      2017-05-28 CRAN (R 3.4.1)                 
 withr           1.0.2      2016-06-20 CRAN (R 3.3.1)                 
 yaml            2.1.14     2016-11-12 CRAN (R 3.3.2)           
```
</details>

**Comment by chrisg1536** [comment]
Good news, I can now view tables using the interface! 
Bad news, I get back 1600 tables, mostly database users, and many other tables I would expect to see are missing. I am not sure which database object ```dbListTables``` returns, but it is a bit of a firehose. I was expecting somthing more along the lines of Database -> Table. Perhaps I asked for the wrong thing in the thread. In my Teradata environment, this database / table relationship can be found in ```
dbc.tablesvx```. Thank you so much for your help.

**Comment by jimhester** [comment]
Teradata is working on making this more tractable by changing which tables are returned, so will close this as it will be fixed elsewhere.
